### ISSUE TITLE
Is simba compatible with Drosophila?

### ISSUE THREAD

**Issue by turtlelover426** [sgoldenlab/simba#103]
Is this program compatible with studying fruit flies without making any modifications to the program?

**Comment by sgoldenlab** [comment]
Hello @turtlelover426 - it comes down to how many flies you have I think. I have not used it with flies myself - it might be relevant thought: [Matěj Šmíd](https://github.com/smidm) used it with 6 ants, and [Caleb Voight](https://github.com/calebvogt) was using flies - you might want to reach out to them. I don't for-see any issues, but if you have dozens of animals it will be terribly slow..
