### ISSUE TITLE
Heat maps for each individual.

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#105]
Hello, it is me again.

Just one small question:  it seems that I cannot generate a heat map for my second mouse since only the body parts belonging to mouse 1 appear in the drop-down menu: 

![Untitled](https://user-images.githubusercontent.com/66886884/115939676-1f7d6900-a49f-11eb-86a1-6d317808126b.png)

Is there a way to generate a map for mouse 2?

Thank you, 
Best, 
Dorian

**Comment by sgoldenlab** [comment]
Hi @DorianBattivelli - again many thanks for reporting, much appreciated - keep em coming please. Can you update simba - `pip install simba-uw-tf-dev --upgrade` (version 0.83.2) and let me know if it works now?

I'm very aware that these heatmaps aren't the pretties.. would probably take some post-editing to make them presentable, this function have not been a priority.

**Comment by DorianBattivelli** [comment]
Hello @sgoldenlab , I'm happy to help you in the development of SimBA which is an amazing tool. 
I upgraded the version and can now generate heat maps for both animals, thank you !

Best, 
Dorian
