### ISSUE TITLE
Issue when defining identities

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#106]
Hello!

Everything worked well from yesterday, until this new project for which I have a problem when importing the h5 file for one video. The previous h5 files for the other videos worked well (I assigned successfully the IDs) but when the program switches to this video, I get a grey screen with error msg in terminal: 

![Untitled](https://user-images.githubusercontent.com/66886884/115957236-669c4600-a501-11eb-89d0-37f46909d951.png)

Would you have a suggestion to solve this?
Thank you, 
Best, 
Dorian

**Comment by sgoldenlab** [comment]
Thanks @DorianBattivelli! I'm not sure why the body-part tracking would be placed at infinity, so watch out of there is something odd going on at the pose-estimation end. 

I've inserted a fix that replaces the inf's (like the NaN's) with zeros which should prevent SimBA from stopping, but the first frame is likely to look a little odd go pass that when when assigning identities. 

Update SimBa to version 0.83.3 and please let me know if it works -  `pip install simba-uw-tf-dev --upgrade`

**Comment by DorianBattivelli** [comment]
Thank you again @sgoldenlab , it works now !
