### ISSUE TITLE
error when trying to upload the H5 file from my DLC files 

### ISSUE THREAD

**Issue by sinal23** [sgoldenlab/simba#108]
**Describe the bug**
error when trying to upload the H5 file from my DLC files 

**To Reproduce**
1. open simba and create a new project using 1 classifier with multi tracking of 2 animals with 4 body parts each
2. add single video 
3. trying to import h5 using multi animal model 

**Screenshots**
![image](https://user-images.githubusercontent.com/79872083/116130666-e06b3580-a6a1-11eb-9789-7995e97d0470.png)
![image](https://user-images.githubusercontent.com/79872083/116130700-e95c0700-a6a1-11eb-8c65-bdf1fedbc592.png)

**Desktop (please complete the following information):**
using anaconda with python 3.6 on windows 10

**Comment by sinal23** [comment]
Additionally, I had a few questions regarding the software.
How long will it take to build a new classifier database? 
If I do have a classifier database (or imported the Resident-intruder protocol), how long will it approximately take to analyze a 10 minute video? do I still need to extract frames and label behavior for each video if I am using imported classifiers?

Thank you!

**Comment by DorianBattivelli** [comment]
Hi @sinal23 , check if it's not the same issue as there: 
https://github.com/sgoldenlab/simba/issues/104#issuecomment-825952356

**Comment by sinal23** [comment]
hi @DorianBattivelli , I updated to simba-uw-tf-dev, it did not work.

**Comment by sinal23** [comment]
hi @DorianBattivelli , I updated to simba-uw-tf-dev, and unfortunately, it sill does not work..

**Comment by DorianBattivelli** [comment]
In my case even after the update, I had to change the appended string manually in my H5 title. Did you try this?

**Comment by sgoldenlab** [comment]
Hello @sinal23! this error is produced as SimBA can't find this file in your project folder:
![image](https://user-images.githubusercontent.com/50497030/116143594-2e773d80-a690-11eb-8cec-e018bfebbc13.png)

Could you have a look manually and check if it exists?

**Comment by sinal23** [comment]
@sgoldenlab no, the file does not exist. Could I have missed a step?

I was also wondering if you know the approximate time it takes to create a new classifier model vs the time it takes to analyze videos using the mouse resident intruder model. and if I would need to label behaviors, extract figures ext each time I want to analyze a new video when I use a trained model. I apologize for the many questions, I am a new user. 
thank you!

**Comment by sgoldenlab** [comment]
Hello @sinal23 - many are new, no worries, I hope we can get it running!

Yes, this file, and your SimBA project folder structure, is created when you Create a project in SimBA, as described here: https://github.com/sgoldenlab/simba/blob/master/docs/Scenario1.md#step-1-generate-project-config, did you click on the `Generate Project Config` button? 

No, once you have your classifier working, you will not have to extract any frames or label any behaviors. To generate a classifier, however, you will need to annotate frames (unless you have reliable annotations generated in other tools like described [HERE](https://github.com/sgoldenlab/simba/blob/master/docs/third_party_annot.md) )

**Comment by sinal23** [comment]
hello @sgoldenlab, 
yes, I followed the steps in that tutorial and created a project. I got a conformation that the project has been generated as followed:
![image](https://user-images.githubusercontent.com/79872083/116161712-a82c1d00-a6ca-11eb-801d-b3048d52900f.png)


So, if I have a classifier working or if I am using the trained model you have provided, can I skip step c (ran analyze models and data) entirely in the simba GUI workflow, and just upload the new videos and the DLC tracks, and run the classifier to visualize the results?

**Comment by sgoldenlab** [comment]
@sinal23 - if you go to the directory where the project was created: 

![image](https://user-images.githubusercontent.com/50497030/116243532-e271da80-a71b-11eb-99ac-4059c6a15845.png)

Is it there? Was there any error/warning msgs printed in the terminal when you clicked on `Create Project Config`? 

>So, if I have a classifier working or if I am using the trained model you have provided, can I skip step c (ran analyze models and data) entirely in the simba GUI workflow, and just upload the new videos and the DLC tracks, and run the classifier to visualize the results?

You have to 1) correct outliers or click to indicate to skip the outlier correction step, and 2) extract features. Once those two steps are complete you can run the pre-generated classifier. If your setup is not identical to the one that was used to generate the classifier, you are likely to have to tinker a little with the [classification thresholds](https://github.com/sgoldenlab/simba/blob/master/docs/tutorial.md#optional-step-before-running-machine-model-on-new-data) to get it right.

**Comment by sinal23** [comment]
@sgoldenlab is that was there, all the folders have been created when I pressed create project, and no errors were shown. The error only showed when I tired importing my files from the DLC files. 
![image](https://user-images.githubusercontent.com/79872083/116270999-fc301380-a755-11eb-8019-16041daa619c.png)
this pathway does exist, however, the file - project_pb_names.csv does not.

**Comment by sgoldenlab** [comment]
Thanks, you are using user-defined body-parts? I will try and replicate.

**Comment by sgoldenlab** [comment]
@sinal23 - I've been trying to play around trying to recreate what you're seeing - with a project being created while the `project_bp_names` is **not** created, and I can't manage to do it. Could you try and delete the project and start again and see if that does it? First define your pose estimation configuration. 


![Untitled1](https://user-images.githubusercontent.com/50497030/116499338-ccb9fd80-a860-11eb-9d21-a99691215201.png)

Then select it from the drop down:

![Untitled2](https://user-images.githubusercontent.com/50497030/116499362-db081980-a860-11eb-9b80-2906fed9b49d.png)

Then click `Generate project Config`
