### ISSUE TITLE
Erorr on "Extract the flames"

### ISSUE THREAD

**Issue by Soengzaak** [sgoldenlab/simba#114]
**Describe the bug**
Hi guys,I started the software normally and used DLC to load project.But when I tried to extracted the flames in it, it poped up an error in SimBA GUI:
```
C:/Users/tearc/Desktop/Project/f-ff-2021-06-01/config.yaml automatic uniform 1 50 False False
Config file read successfully.
Imageio: 'ffmpeg-win32-v3.2.4.exe' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error [Errno 11004] getaddrinfo failed>.
Error while fetching file: <urlopen error [Errno 11004] getaddrinfo failed>.
Error while fetching file: <urlopen error _ssl.c:835: The handshake operation timed out>.
Error while fetching file: <urlopen error timed out>.
Fail to extract frames, please make sure all the information is filled in
```

**I'm sure I have installed the FFmpeg according to the tutorials step by step.In powershell I entered ` ffmpeg --version` it could show its version.**
So,are there any thing I could do to solve it?
Thanks you!

**Desktop (please complete the following information):**
 - OS: [win10]
 - Python Version [3.6]
 - Are you using anaconda? yes

**Comment by inoejj** [comment]
When you import the videos to the project did you check the copy videos box or did you left it uncheck? Do you want to try to make a new project and check the box to make sure it copy the videos.

Please make sure to add ffmpeg to the windows environment path as well.

If you need me to zoom and walk you through this please let me know.

Best,
JJ

**Comment by Soengzaak** [comment]
> When you import the videos to the project did you check the copy videos box or did you left it uncheck? Do you want to try to make a new project and check the box to make sure it copy the videos.
> 
> Please make sure to add ffmpeg to the windows environment path as well.
> 
> If you need me to zoom and walk you through this please let me know.
> 
> Best,
> JJ

Thanks for your attention.It is indeed PATH problems,I have solved it,Thank you!
