### ISSUE TITLE
Editing GUI Not Reflected When Running App

### ISSUE THREAD

**Issue by joseph-yclam** [sgoldenlab/simba#120]
**Describe the bug**
I'm trying to edit some aspects of the GUI by editing the "SimBA.py" file. However, when I try to make a change, it does not reflect when I run the app.

**To Reproduce**
1. Open the "SimBA.py" file using Visual Studio code.
2. Edit some lines, for example, "Welcome fellow scientists :)" to "Welcome fellow scientists!"

**Expected behavior**
I expected the text to be changed when I ran the GUI. 

**Screenshots**
For example, trying to change a simple thing:
![image](https://user-images.githubusercontent.com/76238646/121599549-6f3cd300-ca00-11eb-9cce-945cfa5dfa55.png)

And it does not reflect in the GUI:
![image](https://user-images.githubusercontent.com/76238646/121599595-811e7600-ca00-11eb-993c-b87083f11cf6.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Python 3.6.0 64-bit
 - Using anaconda
 
**Additional context**

**Comment by inoejj** [comment]
Maybe you have to change it in on the right script that you are running or make sure that you are saving your script :)

**Comment by joseph-yclam** [comment]
@inoejj Hi! I'm so sorry, but I think this should be the correct script? And I am positive that I have saved it. I run the project using the "App.py" file!

**Comment by inoejj** [comment]
Hrm.. it seems like you are using anaconda, did you change the SimBA.py that is located in the envs/yourenvironmentname/Lib/site-packages/simba/SimBA.py?
