### ISSUE TITLE
Error running SimBA for the first time: ModuleNotFoundError: No module named 'deeplabcut'

### ISSUE THREAD

**Issue by CorinneAKelly** [sgoldenlab/simba#123]
I have just installed the latest version of SimBA following the instructions for installing with anaconda here: https://github.com/sgoldenlab/simba/blob/master/docs/installation.md

When I did this I had a dependency error, which I resolved using the no-dependencies download instructions on question 11 of the FAQ: https://github.com/sgoldenlab/simba/blob/master/docs/FAQ.md

Now that I am trying to run SimBA for the first time I am getting the following error:
```
(simba) C:\WINDOWS\system32>simba
Traceback (most recent call last):
  File "c:\users\ckelly\anaconda3\envs\simba\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ckelly\anaconda3\envs\simba\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ckelly\Anaconda3\envs\simba\Scripts\simba.exe\__main__.py", line 4, in <module>
  File "c:\users\ckelly\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 8, in <module>
    import deeplabcut
ModuleNotFoundError: No module named 'deeplabcut'
```

How do I fix this?

**Comment by inoejj** [comment]
Please follow the instruction in the given link to install simba.

It seems like you install the version with tensorflow. I recommend you to install the development version of simba (simba-uw-tf-dev)

https://simba-docs.readthedocs.io/en/latest/docs/intro/installation.html#install-simba-dev-using-anaconda-does-not-support-dlc

**Comment by CorinneAKelly** [comment]
I see, thanks! I am wanting to use deeplabcut separately anyway. Is the development version just as stable?

**Comment by inoejj** [comment]
Yes it is stable and up to date.

**Comment by CorinneAKelly** [comment]
Excellent. Thank you so much! I did this and it worked perfectly.
