### ISSUE TITLE
Instalation error because of conflicting dependencies

### ISSUE THREAD

**Issue by aXcELLcore** [sgoldenlab/simba#124]
**Describe the bug**
Hi, I tried to install Simba using the command pip install Simba-uw-tf but I got a dependency conflict error between deeplabcut 2.0.9 has requirement scikit-learn ~ = 0.19.2, but you have scikit-learn 0.19.2 and simba-uw-tf 1.0.3 depends on sikit-learn==0.22.2.
In issue # 63 I read that these warnings would not affect Simba's performance, but when I wanted to check its installation it gave me an error of not being able to find the specified module, which is why I have not been able to install Simba successfully.

Could you please help me

**To Reproduce**
1. pip install simba-uw-tf
2. See error

**Expected behavior**

**Screenshots**
I add two screenshots, the first shows the error when wanting to install Simba and the second screenshot corresponds to the verification of the installation

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.6.0
 - Are you using anaconda: Yes
![thumbnail_image](https://user-images.githubusercontent.com/56560672/126027335-24e634a7-f300-48b2-8ecf-9c9e09f25d10.png)
![thumbnail_image (1)](https://user-images.githubusercontent.com/56560672/126027340-2cd60518-3320-470d-890c-ae000de8fd74.png)

 

**Additional context**

**Comment by sgoldenlab** [comment]
Hello @aXcELLcore ! Check this faq entry: https://github.com/sgoldenlab/simba/blob/master/docs/FAQ.md#11-when-i-install-or-update-simba-i-see-a-bunch-or-messages-in-the-console-telling-there-me-about-some-dependency-conflicts-the-messages-may-look-a-little-like-this

The missing package in your python environment is `Shapely`. I would suggest to first try the second suggestion in the faq link: downgrade pip, then try to install SimBA again. Let me know how it goes.

**Comment by aXcELLcore** [comment]
Thank you very much for answering me, for me your help is very valuable and especially being able to use Simba. I have tried the suggestion to downgrade pip to 20.1.1 but have not been successful, I also tried to install simba via pip install simba-uw-tf --no-dependencies but I get the same error (OSError (WinError 126))
Could you guide me on how I can solve this error please
![111](https://user-images.githubusercontent.com/56560672/126054276-620ecc58-5c6d-42cc-a93a-57f6db68bfaa.png)
![thumbnail_image (2)](https://user-images.githubusercontent.com/56560672/126054290-e3ed6676-1172-4712-b26f-aea0035fe568.png)

**Comment by sronilsson** [comment]
Hello @aXcELLcore - those screenshot are helpful, cheers. So this red `ERROR` messages you see related to dependency incompatibilities are just warning without consequence here and the problem launching SimBA comes from not having having installed the `Shapely` library properly. 

There are a few ways to fix this, I have listed the threads which helped other to solve it here:

https://github.com/sgoldenlab/simba/blob/master/docs/FAQ.md#5-simba-wont-launch---theres-an-error-with-some-complaint-about-shapely

You are using conda, so also see Steps 7-8 in this tutorial for how to get Shapely working:

https://github.com/sgoldenlab/simba/blob/master/docs/anaconda_installation.md

**Comment by aXcELLcore** [comment]
Thank you very much for your answer sronilsson has worked perfectly and now it's time to have fun doing my first project in Simba

**Comment by sronilsson** [comment]
Thanks! Let us know if you jave any other issues popping up
