### ISSUE TITLE
Unable to install due to error

### ISSUE THREAD

**Issue by MasahiroMorsihita** [sgoldenlab/simba#133]
I would like to thank you for developing open-source software.
I tried to install using Anaconda following the instructions, but could not do so due to an error.
The error message is as follows.  I hope the problem is resolved and the software is usable.

ERROR: Cannot install simba-uw-tf==1.0.3, simba-uw-tf==1.0.4, simba-uw-tf==1.0.5, simba-uw-tf==1.0.6, simba-uw-tf==1.0.7, simba-uw-tf==1.0.9, simba-uw-tf==1.1.0, simba-uw-tf==1.1.1, simba-uw-tf==1.1.6, simba-uw-tf==1.1.7, simba-uw-tf==1.2.0, simba-uw-tf==1.2.1, simba-uw-tf==1.2.10, simba-uw-tf==1.2.11, simba-uw-tf==1.2.12, simba-uw-tf==1.2.12.1, simba-uw-tf==1.2.13, simba-uw-tf==1.2.14, simba-uw-tf==1.2.15, simba-uw-tf==1.2.16, simba-uw-tf==1.2.17, simba-uw-tf==1.2.18, simba-uw-tf==1.2.19, simba-uw-tf==1.2.2, simba-uw-tf==1.2.20, simba-uw-tf==1.2.21, simba-uw-tf==1.2.22, simba-uw-tf==1.2.23, simba-uw-tf==1.2.24, simba-uw-tf==1.2.26, simba-uw-tf==1.2.27, simba-uw-tf==1.2.28, simba-uw-tf==1.2.29, simba-uw-tf==1.2.3, simba-uw-tf==1.2.3.10, simba-uw-tf==1.2.3.11, simba-uw-tf==1.2.3.12, simba-uw-tf==1.2.3.13, simba-uw-tf==1.2.3.3, simba-uw-tf==1.2.3.4, simba-uw-tf==1.2.3.5, simba-uw-tf==1.2.3.6, simba-uw-tf==1.2.3.7, simba-uw-tf==1.2.3.8, simba-uw-tf==1.2.3.9, simba-uw-tf==1.2.30, simba-uw-tf==1.2.31, simba-uw-tf==1.2.4.1, simba-uw-tf==1.2.4.2, simba-uw-tf==1.2.4.3, simba-uw-tf==1.2.5, simba-uw-tf==1.2.6, simba-uw-tf==1.2.7, simba-uw-tf==1.2.8, simba-uw-tf==1.2.9, simba-uw-tf==1.2.9.2 and simba-uw-tf==1.3.12 because these package versions have conflicting dependencies.

The conflict is caused by:
    simba-uw-tf 1.3.12 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.31 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.30 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.29 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.28 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.27 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.26 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.24 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.23 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.22 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.21 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.20 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.19 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.18 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.17 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.16 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.15 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.14 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.13 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.12.1 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.12 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.11 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.10 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.9.2 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.9 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.8 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.7 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.6 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.5 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.4.3 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.4.2 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.4.1 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.13 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.12 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.11 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.10 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.9 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.8 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.7 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.6 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.5 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.4 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3.3 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.3 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.2 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.1 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.2.0 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.1.7 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.1.6 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.1.1 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.1.0 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.0.9 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.0.7 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.0.6 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.0.5 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.0.4 depends on tensorflow-gpu==1.14.0
    simba-uw-tf 1.0.3 depends on tensorflow-gpu==1.14.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by sgoldenlab** [comment]
Hello @MasahiroMorsihita! 

For a solution, check out entry `11` of the FAQ: https://github.com/sgoldenlab/simba/blob/master/docs/FAQ.md#11-when-i-install-or-update-simba-i-see-a-bunch-or-messages-in-the-console-telling-there-me-about-some-dependency-conflicts-the-messages-may-look-a-little-like-this

I would recommend using possible solution 3, i.e add the no dependencies flag at install:

Type `pip install simba-uw-tf --no-dependencies`, `pip install simba-uw-no-tf--no-dependencies` or `pip install simba-uw-tf-dev --no-dependencies` dependening on which version you are installing. 

Let me know if that works!
