### ISSUE TITLE
H5 - how to import tracking type "ellipse"?

### ISSUE THREAD

**Issue by carlitomu** [sgoldenlab/simba#143]
Hi,
I'm trying to import some H5 files with tracking type "ellipse" in the "import tracking data" tab, but the tracking type options available are "skeleton" and "box". So there'sn't "ellipse" option. 
![Schermata 2021-10-21 alle 16 03 35](https://user-images.githubusercontent.com/85634193/138293887-e72a0c92-e3a0-44e0-a6e4-b0eb589e12d5.png)

How can import these "ellipse" H5 files correctly?

Thanks,
Carlo.

**Comment by sgoldenlab** [comment]
Hello @carlitomu ! There is an ellipse option - it was added 4-5 months ago, you would not see it if you were running an older version of SimBA. Could you upgrade SimBA with `pip install simba-uw-tf-dev --upgrade` or `pip install simba-uw-tf-dev==0.87.7` and let me know if you see it?

**Comment by carlitomu** [comment]
Thanks.

I used "pip install simba-uw-tf-dev==0.87.7" (in the terminal in the Anaconda environment, working with OSX).
and now I get this:
![Schermata 2021-10-21 alle 16 32 25](https://user-images.githubusercontent.com/85634193/138301955-b59ae3fa-f032-4fba-a40a-2b8425feeda5.png)

I tried to follow the instructions for the installation on mac (https://simba-docs.readthedocs.io/en/latest/docs/intro/installation.html), but I can't solve the problem: i can't launch simba again :(

**Comment by sgoldenlab** [comment]
Hi,
Please start a new environment and follow the steps, make sure that the version of python that you are using is 3.6.13.

One quick note is to make sure in your conda environment, tk has a version of 8.6.10


<img width="1398" alt="Screen Shot 2021-10-21 at 2 19 47 PM" src="https://user-images.githubusercontent.com/50497030/138358432-eb065392-d621-4e7b-8d9a-13539fd59b28.png">

https://simba-docs.readthedocs.io/en/latest/docs/intro/installation.html#installing-on-macos
