### ISSUE TITLE
Issue with video_info.csv an validating the model. 

### ISSUE THREAD

**Issue by yana-yuhai** [sgoldenlab/simba#151]
When I try to validate the model, I get the message:
 
Error: make sure all the videos that are going to be analyzed are represented in the project_folder/logs/video_info.csv file. SimBA could not find No file selected in the video_info.csv file. 

I noticed that my videos end in "el.h5.mp4" whereas their names in the csv file end in "el". However, the csv file will not let me change the endings of the video in Excel. I tried generating a new Excel file with the same data as the video_info.csv file, but that di not work.

**Comment by yana-yuhai** [comment]
Update: I got Excel to work and edited the names. Everything was working until I tried to Run the model. Then I had to go back and change the names back. 

Is there any way to circumvent this in the future? Is this because of an error I made in an earlier step?

**Comment by sronilsson** [comment]
Hi @yana-yuhai ! Do you have a screenshot of the error message? Would help to locate where it went wrong. The `No file selected` part of the message suggests that there is an entry box that you may have missed filling in.
