### ISSUE TITLE
ModuleNotFoundError when trying to open Plotly

### ISSUE THREAD

**Issue by yana-yuhai** [sgoldenlab/simba#152]
When I try to open Plotly, I'm getting this error message: 

<img width="676" alt="Screen Shot 2021-12-10 at 3 52 03 PM" src="https://user-images.githubusercontent.com/93780252/145639997-f91fd682-967a-46ad-b163-5d509eded6a1.png">

I tried to fix this by installing dash-daq, but doesn't seem to work.

**Comment by sronilsson** [comment]
Hey @yana-yuhai - `pip install dash-daq` should solve it, make sure you're in the `simbaenv` environment when you type it. Could you do `pip show dash-daq` to make sure it's installed?

**Comment by yana-yuhai** [comment]
Yes, this worked. Thank you!
