### ISSUE TITLE
Docs link broken

### ISSUE THREAD

**Issue by catubc** [sgoldenlab/simba#157]
Hello
The link to the behavior annotation GUI seems to be broken.

![Screenshot from 2021-12-24 11-51-09](https://user-images.githubusercontent.com/4267452/147346695-9de2307f-1955-40f9-8865-5a1dd698c317.png)

I think the correct link is this:

https://simba-docs.readthedocs.io/en/latest/docs/tutorials/b_annotation.html?highlight=annotation#simba-behavioral-annotator-gui

**Comment by sronilsson** [comment]
Thanks - if you can, use [THIS DOCUMENTATION](https://github.com/sgoldenlab/simba/blob/master/docs/tutorial.md#step-6-label-behavior) - I don't really know where the readthedocs.io comes from, I have not written it and I can't find time to maintain. If you find any errors in the tutorial markdowns on the github repo though then I will fix it.
