### ISSUE TITLE
Pose Configuration: Window sizing bug

### ISSUE THREAD

**Issue by JensBlack** [sgoldenlab/simba#16]
**Describe the bug**
When importing a small image to create a pose configuration (96x161) the autosizing of the window is buggy (see image below).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44863941/77520404-74f0dc00-6e81-11ea-8646-e4bea9eb1f60.png)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
- Anaconda
- simba_no_tf

**Additional context**
I guess you will run into this issue with apps if you autosize and go to the limits of tkinter and such. So this is more of a note, than a real big issue. But as the original video resolution was 848x480 (quite common for tracking) the cut out might be something that happens more than once :)

**Comment by JensBlack** [comment]
additional note: maximizing the window does not solve the issue, but expands the window with additional grey areas.

**Comment by sgoldenlab** [comment]
Hi @JensBlack - many thanks for reporting this! I've inserted a fix - could you download it again and check if its working on your end? In the fix, small images (less than 300px width) are resized to 800px wide. So you should be able to place out your dots appropriately but - beware, it will look rather grainy!

**Comment by JensBlack** [comment]
Thanks for the fast reply! The hotfix works.
I just tested it. The image is displayed in maximized window mode and is quite stretched (as you mentioned) but the window can be resized, so the mouse is miceshaped again! See screenshots below:

maximized window:
![grafik](https://user-images.githubusercontent.com/44863941/77635854-7b4f8880-6f53-11ea-8a66-3112346a2209.png)
windowed window:
![grafik](https://user-images.githubusercontent.com/44863941/77635906-95896680-6f53-11ea-81af-177d133c3975.png)

I will close the "issue". Thank you again for the hotfix!
