### ISSUE TITLE
Error when analysing ROI 

### ISSUE THREAD

**Issue by gabrieltofani** [sgoldenlab/simba#175]
Hi, I'm testing simba to be able to analyze behavior data using the ROI. Everything is going fine up to the step where I actually run the ROI analysis and I get an error that says the FPS and pixel/mm info can't be found in the video_info.csv file, but when I check the file all the information is there. 

Screenshots:
![image](https://user-images.githubusercontent.com/102673091/160846105-e63fd8ed-2a26-41d7-9e9e-c575ac88c22d.png)
![image](https://user-images.githubusercontent.com/102673091/160846213-e3448b07-fc79-4033-9905-0fd4e1910310.png)
![image](https://user-images.githubusercontent.com/102673091/160846526-ac3e427e-0c66-4bfd-bf11-ca3216cc840d.png)

**Desktop:**
 - OS: Windows 10
 - Python Version 3.6
 - I am using anaconda

**Comment by sgoldenlab** [comment]
Hello @gabrieltofani ! it is possible SimBA is having issues with your integer file name `74`. I will check the code for ROI analysis and make sure it can handle it. But in meantime, can you check if that is the case and rename / or analyze a different video which could not be mistaken as an integer (e.g., video74, v74) ?

Thanks for reporting!

**Comment by gabrieltofani** [comment]
Hi! Thanks for the rapid response! I changed the file I'm getting a different error. (Feels like progress though)
![image](https://user-images.githubusercontent.com/102673091/160851490-dd4e18dd-acdd-4a77-a797-1b00edac2524.png)
![image](https://user-images.githubusercontent.com/102673091/160851650-2127ae30-dd4e-4878-84af-1a00d77a635e.png)

**Comment by sgoldenlab** [comment]
Oh, can you check inside the `project_config.ini` file, under the `probability_threshold `value. You should a number written there, a float between 0 and 1. Like in the screenshot, But in your file, SimBA says its a string. 

![image](https://user-images.githubusercontent.com/50497030/160853487-6afaf350-7f31-4ceb-a21c-69007d491d2d.png)

**Comment by gabrieltofani** [comment]
Oh I forgotten to fill the bp probability_threshold this last try time! that is why! It's all working now. 
Thanks so much!

**Comment by sgoldenlab** [comment]
Ah OK, yes, it needs a number.
