### ISSUE TITLE
Feature: Skip outlier correction

### ISSUE THREAD

**Issue by JensBlack** [sgoldenlab/simba#18]
**Is your feature request related to a problem? Please describe.**
This feature request is in direct connection to this [issue](https://github.com/sgoldenlab/simba/issues/17#issue-593348435)

**Describe the solution you'd like**
As this is mainly a copy/paste of data, plus some minor adjustments to the additional logs you create: 
My suggestion would be a button in the outlier correction tab that creates a dummy outlier correction (without the calculations) file and handles the data movement/creation just as the normal function would. 
Another alternative would be to allow the import of filtered/corrected files that will be transformed into your style of logging/handling these kinds of files.
It probably depends if there is any use for a truly raw tracking file in SimBa's workflow if the advanced user has already the abililty to filter/correct them disconnected from SimBa.

**Describe alternatives you've considered**
An easy alternative is to set the parameters given to the correction higher than the max resolution of the video, so that no bodypart can ever reach that distance.

**Additional context**
I understand that this is a feature that helps refining raw tracking data further and is therefore intentionally not skippable. This is a minor request and the community can probably live without it for sure. But, as many groups work with tracking data like the one from DLC, some adapted their own tricks to handle outliers. Therefore it might be a usefull feature, for advanced users.

Thank you for your hard work so far.

**Comment by sgoldenlab** [comment]
Hi @JensBlack - thanks for this! We have created a button for completely skipping outlier corrections in the `outlier correction tab`:

![Skip](https://user-images.githubusercontent.com/50497030/78675276-a910c780-7899-11ea-960b-c7107c244cdb.JPG)

Clicking this button corrects the header rows of the input CSVs (from DLC multi-index-style to single-level style) and copies the CSVs to the `outlier_corrected_movement_location` folder in the project, without checking/correcting outliers in the tracking, and you can proceed extracting features / analyzing ROIs. Let me know if it works! Thanks!

**Comment by JensBlack** [comment]
I tried the new function and it did work out of the box! Just as a note: It only created the outlier csv in the folder 'outlier_corrected_movement_location' ( not in 'outlier_corrected_movement'). I processed the files using the extract feature function, so i guess everything is working!
