### ISSUE TITLE
Training Machine Model TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by slin02** [sgoldenlab/simba#181]
**Describe the bug**
Hi, I am trying to use simBA to automate behavioral analysis in rats. I am ready to begin training after the annotation step, but running into a TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer. I've tried downgrading numpy with no success.

**To Reproduce**
1. loaded in 6 videos and their h5 files. each video has one rat filmed from a side angle
2. completed outlier correction and feature extraction
3. moved 2 of the feature extraction files outside of proj folder for later model validation
4. Under train machine model, saved two settings, one for each classifier
5. Clicked "train machine models, one for each saved settings"

**Screenshots**
![image](https://user-images.githubusercontent.com/77797963/169869892-755ba354-da0c-4b39-859a-3783b3133828.png)
![image](https://user-images.githubusercontent.com/77797963/169868406-3296047c-e932-4e04-aded-45542d577c46.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.6.10
 - Are you using anaconda? yes
 - using simba-ew-tf-dev 0.90.7
 - numpy 1.18.1
 

**Additional context**

**Comment by slin02** [comment]
update, no longer getting this error after unchecking "generate sklearn learning curves"

**Comment by sronilsson** [comment]
Thanks for reporting! I will look into this.
