### ISSUE TITLE
Error during outlier correction step

### ISSUE THREAD

**Issue by fon215** [sgoldenlab/simba#193]
**Describe the bug**
I am working through the SimBA pipeline and I am working on the Outlier correction step following the tutorial steps on the documentation page. I am getting this error when I set the settings. The distance between ears is about 31.75mm for the location criterion and the distance between nose and tail base is about 63.5mm for the movement criterion. I put these values in the Outlier settings. I am a little confused of how this step works, did I do this properly and did I put the right numbers? When I go to run the outlier correction this is what I see in the command window. Could anyone be helpful in understanding what is happening?

`Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\tools\anaconda3\envs\simbaenv\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\simba\SimBA.py", line 6279, in correct_outlier
    dev_move_user_defined(configini)
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\simba\outlier_scripts\movement\correct_devs_mov_user_defined.py", line 120, in dev_move_user_defined
    csv_df.columns = colHeads
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\pandas\core\generic.py", line 5192, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\pandas\core\generic.py", line 690, in _set_axis
    self._data.set_axis(axis, labels)
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\pandas\core\internals\managers.py", line 183, in set_axis
    "values have {new} elements".format(old=old_len, new=new_len)
ValueError: Length mismatch: Expected axis has 18 elements, new values have 27 elements`

**To Reproduce**
1. Go to 'Outlier correction' step
2. Click on 'Settings"
3. Enter values, click 'Confirm"
4. Press 'Run Outlier Correction'
5. See error

**Expected behavior**
Outlier correction should properly remove outliers.

**Desktop (Lenovo P340 Workstation (ThinkStation) - Type 30DH (Tower Form Factor)):**

- OS build: 19043.1706 (Processor: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz 3.70 GHz)
- Python Version 3.10.4
- Are you using anaconda? - Yes

Additional context
I am working through a remote desktop while using this software.

**Comment by sronilsson** [comment]
Hi @fon215! Thanks for reporting. First, the menus circled below, they want a **multiplier**, not a distance value. SimBA will calculate the mean (or median value) between the two body-parts (in this example, the right ear and the tail). SimBA will then use the entered multiplier to get a threshold value. For example, for the movement criterion, if the median distance between  the right ear and the tail is 100mm, and the **multiplier** is set to 2, then any body-part movement larger than 100mm*2 is treated as an outlier movement, and the movement is removed, and the body-part is placed back in the most recent reliably coordinate before the movement. There is more info on this [here](https://github.com/sgoldenlab/simba/blob/master/misc/Outlier_settings.pdf)

The error you are seeing however is unrelated to this. After correcting the outliers, SimBA will modify the heading of the file so it is standardized regardless from whi
![Untitled 2](https://user-images.githubusercontent.com/34761092/177791973-735269f8-5a3c-441b-bc26-4c790520d45c.png)
ch pose-estimation package the data comes from. SimBA wants to insert 27 new headings, and believes that you are tracking 9 bodyparts (27 / 3). However, the file only contains 6 body-parts (18 /3). How many body-parts does your data contain, and what did you specify in the drop-down menues for body-part configuration when creating your project? If you open the `project_config.ini` and scroll down to ` pose_estimation_body_parts =` what do you see it equal?

**Comment by sronilsson** [comment]
Hi @fon215!

Correct! There are a few “built-in” pose-estimation body-part configurations in SimBA, that you can choose from the drop-downs. You can see what kind of data they anticipate in the images that are showed below the dropdowns where you create your project. You can also read about them here: https://github.com/sgoldenlab/simba/blob/master/docs/Tutorial_DLC.md

Your body-parts, e.g., `hand paws`, is not available in these built-in configurations. That means we have to create and choose to use a `user-defined body-part configuration` in the SimBA dropdown menu when we create our project. There is a tutorial for how to do that here: https://github.com/sgoldenlab/simba/blob/master/docs/Pose_config.md Let me know if that makes sense!

**Comment by sronilsson** [comment]
If you change it to `6`, the SimBA will think its one of the default "in-built" settings with 6 body-parts, rather than a user-defined body-part configuration. I recommend creating a new project with user-defined body-part configuration!

**Comment by sronilsson** [comment]
SimBA will ask you to create an image, however, it is just a place holder, and not used for anything important in SimBA. You can grab any image and select the locations of your body-parts.

**Comment by fon215** [comment]
Okay, thanks so much, again!
