### ISSUE TITLE
Error opening file during feature extraction

### ISSUE THREAD

**Issue by fon215** [sgoldenlab/simba#197]
Hello again, sorry for all the questions, but I am new to SimBA and trying to learn how it works. In the most recent issue I submitted, I was having trouble getting the Feature Extraction feature to work, and I solved that issue by using the proper videos and making sure the `video_info.csv` file has the correct information. However, now that all of that is fixed, I can complete feature extraction but in the SimBA command window I am seeing this stating that no features were extracted: 
`Pose-estimation body part setting for feature extraction: user_defined
Applying settings for classical tracking...
Extracting features from 0 file(s)...
SIMBA COMPLETE: Feature extraction complete for 0 video(s). Results are saved inside the project_folder/csv/features_extracted director.`

Also, in the Anaconda Prompt command window I am seeing this error message:

`warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:901)
warning: N:/Ross/1Tayler Sheahan/Automated Behavioral Analysis/Madeline Fontana/SimBA\Full_SimBA\project_folder\videos\0 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:902)`

I was researching this error and I think it has something to do with it not being able to open a video, but could someone please help me understand what is happening here so that I can get it to work? Thanks!

**Comment by sronilsson** [comment]
No worries @fon215! This suggests that simba cannot find any files inside the `project_folder/csv/outlier_corrected_movement_location` folder. 

After importing your data, SimBA expects you to correct outliers, and then extract features. Did you click to correct outliers or alternatively clicked skip outlier correct to confirm no outlier correction needed?

**Comment by fon215** [comment]
Okay, I must have made some strange minor mistake but I just went through the steps again and the features were extracted for all of my videos. 

Thanks again, anyway!

**Comment by sronilsson** [comment]
Nice!
