### ISSUE TITLE
Machine Model Training Issue

### ISSUE THREAD

**Issue by n-zeng** [sgoldenlab/simba#199]
I have an odd error message when I try to run the model.

Everything worked fine up to "Run Machine Model", except the training didn't put 2 of my classifiers into .sav. I just ran it again with only those two classifiers, and that worked.

When I press "Run RF model", I get this in the GUI terminal -
![Screen Shot 2022-07-14 at 3 07 45 PM](https://user-images.githubusercontent.com/109232212/179063731-58f558d9-f550-49b0-9754-f4db0e7f2af1.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Anaconda
 - Python 3.6.10

**Comment by sronilsson** [comment]
Hi @n-zeng I did notice the bug where it was only creating the first two models, it should be fixed now if you update simba. 

However, I am not sure why your model only would be base don 5 features, let me check how this could happen.

**Comment by sronilsson** [comment]
I was just updating these scripts to make name a little more resilient to errors, so its possible another bug sneaked in.

**Comment by sronilsson** [comment]
yeah, sorry, found it: while writing the scripts and troubleshooting and cleaning, I limited myself to create only 2 models, based on 5 features, to save time and not have to watch too much processing. And it appears I failed to remove to part of the code that did those limitations 🙃. Big thank you for reporting.

**Comment by sronilsson** [comment]
Yes, if you update to simba 0.93.3 with `pip install simba-uw-tf-dev`, then train the models again (it is likely to be a little slower now) and the issues should be fixed. Make sure you get 0.93.3, because I updated it just seconds ago.

**Comment by sronilsson** [comment]
But please let me know how it goes

**Comment by n-zeng** [comment]
> pip install simba-uw-tf-dev --upgrade

I'm not sure what happened, but I can't seem to open the set video parameters window?

**Comment by sronilsson** [comment]
Do you see an error msg in the terminal?

**Comment by n-zeng** [comment]
> Do you see an error msg in the terminal?

Yes, it said something about mp4 and float, sorry I closed the terminal.

**Comment by sronilsson** [comment]
It sounds like the `project_folder/logs/video_config.csv` file may have some incorrect values.

**Comment by n-zeng** [comment]
> But please let me know how it goes

Alright, the training took a good bit since I was using 4 classifiers, but yes it works now! I'll let you know about that other bug in a minute.

**Comment by n-zeng** [comment]
> But please let me know how it goes

Sorry for sending so many messages, but everything I reported works now!

**Comment by sronilsson** [comment]
Nice please let me know if anything else pops up
