### ISSUE TITLE
Error during train machine model step/need help understanding hyperparameters

### ISSUE THREAD

**Issue by fon215** [sgoldenlab/simba#201]
Hello! I completed the labeling of videos in my project and I am trying to do the `Train Machine Model` step in the pipeline but I am having trouble understanding how it works. I read the documentation and followed the guide, using the generic hyperparameter settings listed in this document `BtWGaNP_meta.csv` that is provided in the guide but I am getting the error listed below. Could you help me understand this step and the hyperparameters so I can complete this successfully? I am new to SimBA and I just want to make sure I am doing everything correctly! For context, my videos have one mouse in each video where I am using 6 body parts (nose, left forepaw, right forepaw, left hind paw, right hind paw, and tail base) to analyze left and right nape scratching. Thanks!

`[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 20 concurrent workers.
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done 160 tasks      | elapsed:    1.8s
[Parallel(n_jobs=-1)]: Done 410 tasks      | elapsed:    4.7s
[Parallel(n_jobs=-1)]: Done 760 tasks      | elapsed:    8.5s
[Parallel(n_jobs=-1)]: Done 1210 tasks      | elapsed:   13.6s
[Parallel(n_jobs=-1)]: Done 1760 tasks      | elapsed:   19.8s
[Parallel(n_jobs=-1)]: Done 2000 out of 2000 | elapsed:   22.5s finished
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\tools\anaconda3\envs\simbaenv\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\simba\SimBA.py", line 4088, in <lambda>
    button_trainmachinemodel = Button(label_trainmachinemodel,text='Train single model from global environment',fg='blue',command = lambda: threading.Thread(target=self.train_single_model(config_path=self.projectconfigini)).start())
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\simba\SimBA.py", line 4539, in train_single_model
    model_trainer.train_model()
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\simba\train_single_model.py", line 132, in train_model
    create_x_importance_bar_chart(self.rf_clf, self.feature_names, self.clf_name, self.eval_out_path, feature_importance_bars)
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\simba\train_model_functions.py", line 217, in create_x_importance_bar_chart
    create_x_importance_log(rf_clf, x_names, clf_name, save_dir)
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\simba\train_model_functions.py", line 208, in create_x_importance_log
    df.to_csv(save_file_path, index=False)
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\pandas\core\generic.py", line 3228, in to_csv
    formatter.save()
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\pandas\io\formats\csvs.py", line 183, in save
    compression=self.compression,
  File "c:\tools\anaconda3\envs\simbaenv\lib\site-packages\pandas\io\common.py", line 399, in _get_handle
    f = open(path_or_buf, mode, encoding=encoding, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'N:/Ross/1Tayler Sheahan/Automated Behavioral Analysis/Madeline Fontana/SimBA\\Full_SimBA\\models\\generated_models\\model_evaluations\\leftnapescratch_feature_importance_log.csv'`

<img width="394" alt="Screen Shot 2022-07-20 at 9 55 25 PM" src="https://user-images.githubusercontent.com/99504167/180114944-7c8beb2c-9374-474a-b5ff-5dc91eca0d4d.png">

<img width="651" alt="Screen Shot 2022-07-20 at 10 05 41 PM" src="https://user-images.githubusercontent.com/99504167/180114991-645d6c2e-5642-40e4-b4a7-e4c5b5e2d060.png">

I was able to exit still and this error was no longer in the command windows so I should be able to do that step successfully again once I fix the issue.

**Comment by sronilsson** [comment]
Hi @fon215 ! Thanks for reporting, and, my bad. I was just updating these scripts, and I forgot the line of code that creates the folder, before saving the file in that folder :) Can you update to simba 0.93.6 with `pip install simba-uw-tf-dev --upgrade` and see if that fixes it? If it doesn't, or any other errors come up, please let me know.

**Comment by fon215** [comment]
That's alright! I upgraded my version of SimBA but when I use the generic settings above I am still getting the same error. Along with fixing that issue, I was wondering if I will need to create 2 models and train on two different specific models because I am checking for both left and right nape scratch, or is that not how this works?

**Comment by sronilsson** [comment]
If I understand correctly, "nape scratch" is a behavior you want to classify, and you want to know how much left-side nape scratching the animal is doing, and how much right-side nape scratching the animal is doing? If so then yes, in SimBA we need two classifiers.

**Comment by sronilsson** [comment]
Oh I noticed you still see the error.. I will have to check again why that is.

**Comment by sronilsson** [comment]
Yes, I think the model settings will be very similar, if the scratching is very similar, just mirrored. But you will need annotations for both behaviors. 

That is just a message, no error or warning. 

That said, I can't recreate your error. Would you mind running the code again and send me a screengrab of the error msg in the windows terminal?

**Comment by fon215** [comment]
Okay so this time, I am no longer getting the error because I made two specific models, one for each side, saved those metadata setting files, and trained on multiple models and that seems to have worked and successfully and completed. Let me know if something still does not look right and thanks for your help!

![left_and_right_models_saved](https://user-images.githubusercontent.com/99504167/180230948-cbdedf31-dc05-486c-a1bc-c98ddf355793.JPG)
![training_models_anaconda_prompt_window](https://user-images.githubusercontent.com/99504167/180230965-a494bac0-fc36-4d42-bb43-aabe21716723.JPG)
![left_model_complete](https://user-images.githubusercontent.com/99504167/180230981-e2cdb44b-a27b-461c-8c73-73615802c2ad.JPG)
![right_model_complete](https://user-images.githubusercontent.com/99504167/180231000-73befb24-4823-47b3-9b61-50814d570be5.JPG)

**Comment by fon215** [comment]
Here is one of the csv files and what the features extracted folder looks like for me.
[Bottom up comp 48-80 050721 mouse 2 part 2_Trim7.csv.zip](https://github.com/sgoldenlab/simba/files/9160195/Bottom.up.comp.48-80.050721.mouse.2.part.2_Trim7.csv.zip)
<img width="771" alt="Screen Shot 2022-07-21 at 10 31 23 AM" src="https://user-images.githubusercontent.com/99504167/180240521-d4caf947-ef19-40eb-bdd4-ea2b8f757087.png">

**Comment by sronilsson** [comment]
False alarm, I think you should be good :)
