### ISSUE TITLE
Mismatch in ROI data analysis.

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#202]
Hello,

First of all thank you again for providing these amazing data analyzes tools. 

I would like to report several mistakes I observed while analysis ROI data.
I'm working on Windows 10, and I use 0.92.2 version of Simba (installed with simba-uw-tf-dev command 2 months ago)

I used el.h5 files from DLC-multi animal project, including 2 mice to track simultaneously.

Among the errors I noticed:
- The IDs of the mice are wrong in the resulting ROI-time_data file. Data labelled for mouse 1 are actually related to my mouse 2 and vice versa. 
- The IDs are also reversed when I generate a path plot video, So the error seems constant. 
- When I analyze ROI only for one animal at a time, only the Movement_within_ROIs file generates indeed data for one animal, but the ROI_entry_data and ROI_time_data still present data for both animals.

How can I fix these issues?

Thank you,
Best,
Dorian

**Comment by sronilsson** [comment]
Hi @DorianBattivelli! Many thanks for reporting! First, can up update to the latest version of simba-uw-tf-dev (should be version 0.93.8) with `pip install simba-uw-tf-dev --upgrade`, and see if you still see the same issues?

**Comment by DorianBattivelli** [comment]
Thank you for the help.
I managed to update the version. 
Though, the 3 mentioned mistakes still appear if I launch the Analyze ROI data process.
I precise that I did not recreate a project from scratch and only tried to run the analysis from my existing project. 

Best,

**Comment by sronilsson** [comment]
Thanks for testing - when you import the data from multi-animal DLC, there is an interface to specify which animal is which by clicking the animals in the (image)[https://github.com/sgoldenlab/simba/blob/master/docs/Multi_animal_pose.md#step-5-assigning-tracks-the-correct-identities]. Is it possible that the mouse click for animal 1 was closer to a body-part of animal 2, and vice versa?

**Comment by DorianBattivelli** [comment]
So, I did a new project from scratch to be sure about the ID attributions. 
And again, even with this last version, I confirm that the IDs either in the ROI csv files, and in the path plots videos are inverted.

**Comment by sronilsson** [comment]
Thanks @DorianBattivelli for digging! I appreciate it. I can't immediately replicate it in my troubleshooting projects, but need to figure this one out. Can you help me with two more things? 

If you visualize the ROI calculations using the `Visualize ROI tracking` menu, does it also look inverted? 

Can you share your SimBA project with me? It is enough with the single video inside it. But I also need the DLC 'el.h5` to import it, be be able to follow your steps.

**Comment by DorianBattivelli** [comment]
Running Visualize ROI tracking returns the following error:
![ROI_Tracking](https://user-images.githubusercontent.com/66886884/181258880-17b2bad6-9155-4684-8acf-9360b5d1e237.png)

I will upload the project on Drive and share it with you asap,

Best,

**Comment by sronilsson** [comment]
Yes! No need for the frames at all.

**Comment by sronilsson** [comment]
Thanks @DorianBattivelli!

**Comment by DorianBattivelli** [comment]
To which email adress can I share the folder?

**Comment by sronilsson** [comment]
Thanks! I will test it asap, and figure out why you see the visualization error (as its not showing for me either). Can you share it with sronilsson@gmail.com ?

**Comment by DorianBattivelli** [comment]
Done, thanks!

**Comment by sronilsson** [comment]
Great, is the `_el.h5` in there too? At quick browse I can't see it

**Comment by DorianBattivelli** [comment]
No my mistake, I added them now and updated the sharing,

Thanks!

**Comment by sronilsson** [comment]
Got it!

**Comment by sronilsson** [comment]
@DorianBattivelli, if you check the video at https://drive.google.com/file/d/1HvbWTV8e1SCb9XIqFnFyb00QsTx8_4Xa/view?usp=sharing, are animal IDs inverted? (watch out it is large..).

**Comment by DorianBattivelli** [comment]
Yes, they are inverted

**Comment by DorianBattivelli** [comment]
@sronilsson thank you very much, it solved the issue. Now the ID are right ! Thank you again.

Also, I wanted to ask you how to improve the quality of the distance measurment? I suspect that the variation of the exact location of the center body part label from one frame to the other is considered as displacement / movement, so that even when the animal is immobile, this artificial displacement of the body label is considered as locomotion. I tried to change the movement criterion parameter but it does not look to change the distance measurment. Is there something I can do? 

Thank you again! 
Best,

**Comment by sronilsson** [comment]
Hi @DorianBattivelli - one possible way is to use [smoothing](https://github.com/sgoldenlab/simba/blob/master/docs/Scenario1.md#to-import-multiple-dlc-csv-files) when you import your data. There are two options (Gaussian, Savitzky-Golay). After you've imported your data, you can visualize it using this [tool](https://github.com/sgoldenlab/simba/blob/master/docs/Tutorial_tools.md#visualize-pose-estimation-in-folder) from the `Tools` dropdown to check if it looks less jumpy. There is a video example here of the expected results: https://www.youtube.com/watch?v=d9-Bi4_HyfQ

**Comment by DorianBattivelli** [comment]
Amazing, thank you very much, 

Best!
