### ISSUE TITLE
Impossible to import h5 elipse data from DLC

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#210]
Hello,

Sorry for reporting this small bug but I can't import my el.h5 file, the terminal reports:

![H5-error](https://user-images.githubusercontent.com/66886884/188630959-812469e3-f21e-4cd9-8ed4-ab2208226e7c.png)

What could be the error?
FYI, I'm using 0.95.9 simba version on windows.
Thank you, 
Best,

**Comment by DorianBattivelli** [comment]
I precise that it's a second importation of h5 file for the same video, since the first h5 contained some mistakes. I erased the coresponding csv file (from the first h5 file in the csv folder.

**Comment by sronilsson** [comment]
Hi @DorianBattivelli thanks for reporting! Is it possible that you have some hidden files located within the directory you are importing the files from, or hidden files within your SimBA `project_folder/videos` directory? https://support.microsoft.com/en-us/windows/show-hidden-files-0320fe58-0117-fd59-6851-9b7f9840fdb2#:~:text=Select%20the%20Start%20button%2C%20then,drives%2C%20and%20then%20select%20OK.

**Comment by DorianBattivelli** [comment]
Thank you for the answer. 
I checked and I don't have any hidden in these directories

**Comment by sronilsson** [comment]
I bumped into this error myself a few times when I was troubleshooting something different. It happened when I have a file in the videos folder that does not have a file extension (or only an extension, no file-name) and I was about to insert a fix. Here, in the image, for example, there is a file called `.DS_store` in my videos directory that is hidden which is causing the code to fail (it can't find the video's name, only extension). I will insert a fix for this now, and let's see if it fixes the issue on your end, if not we can dig more. 




![image](https://user-images.githubusercontent.com/34761092/188641974-8fb76144-766e-4933-82e6-163d35fe6b28.png)

**Comment by sronilsson** [comment]
@DorianBattivelli - if you update to `0.97.4` - do you still see the error?

**Comment by DorianBattivelli** [comment]
Thank you, unfortunatly the update did not fix the bug.
Here the files and corresponding paths I use to import the h5 file:
![Schermata 2022-09-06 alle 16 28 16](https://user-images.githubusercontent.com/66886884/188661682-0d73633c-5620-44cb-a01c-298536819a9e.png)

**Comment by sronilsson** [comment]
Thanks @DorianBattivelli - I cant see the entire file explorer window. To troubleshoot, could you also tick the `File name extensions` box next to the `Hidden items` box and send me the screengrab? 

If you move the `Bh5` folder to a different location, does the error persist?

**Comment by DorianBattivelli** [comment]
I also tried by moving the folder on the desktop, and the problem persists.
![Schermata 2022-09-06 alle 16 42 06](https://user-images.githubusercontent.com/66886884/188664689-eac23623-6418-4077-81a2-47d3a3a0832d.png)

I precise that I do not import the video since it is already present in the video folder. Could that create the error?

**Comment by sronilsson** [comment]
Yes, that should not cause an issue. In version `0.97.4`, I inserted a print statement, that shows all the files SimBA finds in the video folder, before it starts to scan which one belongs to your `el.h5` file. 

Did you see that print statement?

**Comment by DorianBattivelli** [comment]
I also tried by moving the folder on the desktop, and the problem persists.
![Schermata 2022-09-06 alle 16 42 06](https://user-images.githubusercontent.com/66886884/188664689-eac23623-6418-4077-81a2-47d3a3a0832d.png)

I precise that I do not import the video since it is already present in the video folder. Could that create the error? 

> Yes, that should not cause an issue. In version `0.97.4`, I inserted a print statement, that shows all the files SimBA finds in the video folder, before it starts to scan which one belongs to your `el.h5` file.
> 
> Did you see that print statement?

Not sure to understand, I should find the statement in the error that returns the terminal?

**Comment by DorianBattivelli** [comment]
After updating, here what I get:
![Schermata 2022-09-06 alle 17 50 04](https://user-images.githubusercontent.com/66886884/188680056-f3c164b7-8d12-454b-bb1e-26e1b34ebb80.png)

**Comment by sronilsson** [comment]
@DorianBattivelli - I've inserted some code that should filter out all subdirectories and hidden files, and show you the name of the offending file if you still hit an error. Can you update SimBA to `0.97.5` and let me know how it goes?

**Comment by DorianBattivelli** [comment]
Amazing, it solved the issue, thank you very much!

**Comment by DorianBattivelli** [comment]
Well actually I am stuck at the next tab, when trying to set the video parameters:
![Schermata 2022-09-07 alle 00 20 23](https://user-images.githubusercontent.com/66886884/188750907-95ad73d6-710e-40d7-823e-bfcbb152fe77.png)

**Comment by sronilsson** [comment]
Alright - hang on, I will insert a more solid fix. There is likely to be some hidden file in that folder.

**Comment by sronilsson** [comment]
I'm sorry I don't have a fix. But hopefully I have an update that can help us figure out what is going on. If you update to version `0.97.7`, and repeat the same process, what is the error message you see in the main SimBA terminal? 

What you should see something like this - `SIMBA ERROR: ThisFilename is not a valid filepath`

**Comment by DorianBattivelli** [comment]
Thank you for the update, Indeed the error message is as you  said

Loading F:/Territorial_Arena/Paper/Protocol_1/CD1/Simba/B1-MS_US/project_folder/project_config.ini...
SIMBA ERROR: F:/Territorial_Arena/Paper/Protocol_1/CD1/Simba\B1-MS_US\project_folder\videos\Bh5 is not a valid filepath

**Comment by DorianBattivelli** [comment]
Okm annd removing the h5 folder fixed the problem ,) thank you!
