### ISSUE TITLE
Analyze ROI with specific time frame

### ISSUE THREAD

**Issue by Destiny-123** [sgoldenlab/simba#222]
Hello,

Is there a way to analyze time spent and entry ties of specific ROIs for a specific time? For example, if I have a 5 minute video and want to also analyze ROIs for the first 2 minutes of video.

**Comment by sronilsson** [comment]
Hi @Destiny-123, yes there is a method to split the results into time-bins, see screenshot below. To get the results in the first 2 minutes, set the bin size to 120s, and look at the results in the very first time bin in the output results file.

![image](https://user-images.githubusercontent.com/34761092/206601530-663506c2-d6e0-4946-9dd5-cbd813f36b4d.png)
