### ISSUE TITLE
Problem with sklearn visualization 

### ISSUE THREAD

**Issue by Urimons** [sgoldenlab/simba#223]
**Describe the bug**
When I try to "visualize classification results" for all my videos I get an error "TypeError: __init__() missing 1 required positional argument: 'video_file_path'", although when I do the same for only one video ("apply to single video")  at the time it seems to work just fine.

**To Reproduce**
1. Go to 'visualizations'
2. Click on 'visualize classification results'

**Screenshots**
![image](https://user-images.githubusercontent.com/86400083/207390236-a4ecac9e-dd56-474c-8fe4-c17140394a0e.png)

![image](https://user-images.githubusercontent.com/86400083/207540282-3da647fa-faaa-4593-82c0-d267efb332ef.png)

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Python Version [e.g. 3.6.0]
 - Are you using anaconda? yes
 

**Additional context**
Is the problem with my config?  (pics added)
![image](https://user-images.githubusercontent.com/86400083/207540685-bc5a359b-5f8c-4252-b029-efdf48b727e4.png)
![image](https://user-images.githubusercontent.com/86400083/207540835-fe7fc539-a768-4731-bce9-601f9b4c6b2e.png)

**Comment by sronilsson** [comment]
Hi @Urimons - thanks for reporting!

If you update to latest version `1.30.2` with `pip install simba-uw-tf-dev --upgrade`, do you still see the error?

**Comment by Urimons** [comment]
No I do not!
It seems to work just fine :)
Thanks!

**Comment by sronilsson** [comment]
Thanks for letting me know!
