### ISSUE TITLE
Error when Generating Project Config and Importing Videos

### ISSUE THREAD

**Issue by mrnels19** [sgoldenlab/simba#225]
**Describe the bug**
Whenever I click on the buttons titled Generate Project Config and Import Video, I receive errors in the terminal. The errors I receive are found in the screenshots titled Generate Project Config Error and Import Video Error. In the Import Video Error screenshot, the error is inside the white box. I am wondering what is causing these errors, since I need to import videos before I can import any tracking data. 

**To Reproduce**
1. Open SimBA and create a new project. Say the number of predictive classifiers is equal to 1 (I was going through the tutorial) and give it a name.
2. In the Type of Tracking menu, select Multi Tracking
3. In  the # config  menu, select Multi-animals, 8bps.
4. Press Generate Project Config. When I press this button, I get an error as described in the Generate Project Config Error screenshot. 
5. Then, I go to the [Import videos into project folder] tab and go to the Import single video sub menu. I am going to import an .avi video. I then press the button that says Import a video, and I get the error in the white box in the Import Video Error screenshot (this error is also displayed right above the white box in the screenshot because I clicked this button twice). 

**Expected behavior**
There should not be any error messages when these buttons are pressed.

**Screenshots**
The screenshots titled Generate Project Config Error and Import Video Error are attached. 

**Desktop (please complete the following information):**
 - Windows operating system
 - Python 3.6.13
 - I used Anaconda to install SimBA. When installing, Python 3.6.13 was the closest option to Python 3.6 that I could select from the Python dropdown menu.
 
![Generate Project Config Error](https://user-images.githubusercontent.com/121840032/210297630-9affeb39-fdec-4767-9f02-f53ced042092.PNG)
![Import Video Error](https://user-images.githubusercontent.com/121840032/210297638-d9753443-6ab5-4f52-8815-97cf11190b7c.png)

**Comment by mrnels19** [comment]
I realize that the names of the screenshots do not appear when I add them into my post. The screenshot titled Generate Project Config Error is the one with the mouse images in it. The screenshot titled Import Video Error has the white box.

**Comment by sronilsson** [comment]
Hi @mrnels19 - many thanks for reporting. You caught this bug very quickly, it was introduced just before you opened the issue. 

If you update to version 1.30.7 with `pip install simba-uw-tf-dev --upgrade`, does that fix the issue?

**Comment by mrnels19** [comment]
Yes, this helped! Thank you.
