### ISSUE TITLE
Error in Train model

### ISSUE THREAD

**Issue by JensBlack** [sgoldenlab/simba#23]
**Describe the bug**
After getting the error in issue #22 , I toggled both boxes (see below) to circumvent the error #22 .
The following error occured after initializing training (or rather before it). I checked the code and it's the exception for an error in training (fitting), so could be anything? I checked both csv files if they contained the array and if it was valid (see further below).

_simba/train_model_2.py:237_
```
        try:
           clf.fit(data_train, target_train)
        except ValueError:
           print('ERROR: The model contains a faulty array. This may happen when trying to train a model with 0 examples of the behavior of interest')
```

I tried both train methods using global environment for 1 model and specific for 3 seperate models (as visible in the SimBa log). The console output is the same, so i didn't post the second.
Removing both boxes (Generate Features Importance Log and Graph) does not change the error (tested in the global settings method).

Settings:

![grafik](https://user-images.githubusercontent.com/44863941/78661892-ccef0000-78cf-11ea-9cac-83b152c86228.png)

SimBa - Log:

![grafik](https://user-images.githubusercontent.com/44863941/78661547-41756f00-78cf-11ea-8867-d6c758622a07.png)

Console output:

```
(simba-gpu) C:\Users\schwa\PycharmProjects\simba\simba>python simba.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Anaconda\envs\simba-gpu\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\envs\simba-gpu\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "simba.py", line 3734, in trainmultimodel
    train_multimodel(self.projectconfigini)
  File "C:\Users\schwa\PycharmProjects\simba\simba\train_multiple_models_from_meta.py", line 263, in train_multimodel
    generateClassificationReport(clf, class_names, classifierName, saveFileNo)
  File "C:\Users\schwa\PycharmProjects\simba\simba\train_multiple_models_from_meta.py", line 51, in generateClassificationReport
    visualizer.score(data_test, target_test)
  File "D:\Anaconda\envs\simba-gpu\lib\site-packages\yellowbrick\classifier\classification_report.py", line 130, in score
    y_pred = self.predict(X)
  File "D:\Anaconda\envs\simba-gpu\lib\site-packages\sklearn\ensemble\_forest.py", line 612, in predict
    proba = self.predict_proba(X)
  File "D:\Anaconda\envs\simba-gpu\lib\site-packages\sklearn\ensemble\_forest.py", line 654, in predict_proba
    check_is_fitted(self)
  File "D:\Anaconda\envs\simba-gpu\lib\site-packages\sklearn\utils\validation.py", line 967, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
sklearn.exceptions.NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
```

pd.Dataframe.describe() and np.sum() for both target_inserted csv files over all labelled frames (model names: 'active', 'resting' and 'inner_circle')

**Dataframe 1**
```
Dataframe.describe()
            Active       Resting  Inner_circle
count  54892.000000  54892.000000  54892.000000
mean       0.750000      0.250000      0.394065
std        0.433017      0.433017      0.488653
min        0.000000      0.000000      0.000000
25%        0.750000      0.000000      0.000000
50%        1.000000      0.000000      0.000000
75%        1.000000      0.250000      1.000000
max        1.000000      1.000000      1.000000

np.sum()
Active          41169.0
Resting         13723.0
Inner_circle    21631.0
```
**Dataframe 2**

```
Dataframe.describe()
             Active       Resting  Inner_circle
count  54892.000000  54892.000000  54892.000000
mean       0.750000      0.250000      0.394065
std        0.433017      0.433017      0.488653
min        0.000000      0.000000      0.000000
25%        0.750000      0.000000      0.000000
50%        1.000000      0.000000      0.000000
75%        1.000000      0.250000      1.000000
max        1.000000      1.000000      1.000000

np.sum()
Active          41169.0
Resting         13723.0
Inner_circle    21631.0
dtype: float64
```
As you can see both Dataframes (csv files) have labelled frames (with both True/1 and False/0 values). As I did the exact same thing, but with 1 csv file less, just yesterday. I am confused.

**Additional context**
The additional csv file was added using the provided functions. It's noteworthy that I did not label the csv file manually but added columns to the outlier corrected version via some automatic labelling method. This method worked before.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SimBa-GPU install (newest version 07.04.2020) with Anaconda

**Comment by JensBlack** [comment]
This is a print out from the function simba/train_model_2.py just before the try (mentioned above).

```
print(data_train)
        Deviation_from_median_Movement_difference_movement_center_movement_left_hip  ...  movement_tail_tip
89150                                            0.548807                            ...           4.247683
104100                                          -0.112851                            ...           0.638911
56938                                            0.541995                            ...           1.495396
74278                                            0.249147                            ...           0.541398
69342                                            0.345994                            ...           0.886768
...                                                   ...                            ...                ...
48366                                           -1.046650                            ...           2.202447
27243                                            0.826896                            ...           1.022565
79840                                            0.674166                            ...           1.100300
35520                                            0.391709                            ...           2.451280
83918                                            0.488544                            ...           1.342929

[91256 rows x 763 columns] 

print(target_train)
[1. 1. 1. ... 1. 1. 1.]
```

**Comment by JensBlack** [comment]
Update:
Removing the additional csv file (by deleting it in the target_inserted folder) and keeping the original csv file did not raise the error.
Removing the original csv file (but keeping the additional) raised the error.

Therefore I will add information about my procedure of adding the additional csv file:

1. Import csv file using the "import single csv file" in the "further imports" tab.
2. Copying video and frames (manually into the corresponding folders)
3. setting video parameters
4. outlier correction (parameter set to 1000; above resolution): No Correction
5. feature extraction
6. Addition of label columns for 3 models in both csv files via custom script (result see above)
7. Set Settings and train model

**Comment by JensBlack** [comment]
i solved the issue.... it was an error in my labelling method. I will close the issue.

**Comment by benlansdell** [comment]
Hi @JensBlack, I may be having the same issue as you. What was the error you were making in your labeling method?

Thanks.

**Comment by benjaws** [comment]
Hi @benlansdell, 
I have the same problem, did you solved it ?

Many thanks
