### ISSUE TITLE
Model Training Error

### ISSUE THREAD

**Issue by kylethieringer** [sgoldenlab/simba#235]
**Describe the bug**
When trying to train new model I am running into an error in the random under sampling function.  

**To Reproduce**
1. load project config
2. train single model 

**Screenshots**
<img width="1667" alt="Screenshot 2023-03-02 at 1 28 01 AM" src="https://user-images.githubusercontent.com/61333066/222348638-81b07152-56f0-404f-941f-17a3d1f80314.png">

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Python Version 3.6
 - Are you using anaconda? yes
 

**Additional context**
Im not sure if this is important but I uploaded tracks from sleap h5 files and labels from deepethogram. I have 2 animals with 13pts each. I am trying to classify a sparse behavior <10% of frames.

**Comment by sronilsson** [comment]
Thank you @kylethieringer! I inserted the bout sampler train/test option recently, haven't had any feedback yet, so might be a few bugs to clean up, so this is helpful. 

The error came from the bout sampling function returning arrays, and the downstream `random undersampler` accepting dataframes. If both bout sampling and the random undersampler was used, you'd bump into that error. 

I fixed it in version `1.51.4` - could you update with `pip install simba-uw-tf-dev --upgrade` and see if it works on your end?

**Comment by kylethieringer** [comment]
Thanks so much for your speedy response and fix! No issues anymore!
