### ISSUE TITLE
question about pseudo labelling

### ISSUE THREAD

**Issue by ayakab0619** [sgoldenlab/simba#237]
Hi,
Thank you for developping nice tools.
I'm trying pseudo labelling, but I have an erorr.
SimBA said 
SIMBA WARNING: Video xxxxxx has fps of 0.
after clicking 'Correct labels'.
video_info.csv in logs folder show fps is 15, not 0.
Can you help me with this issue?

Thank you.

**Comment by sronilsson** [comment]
Hi @ayakab0619! This error suggest that simba is having trouble to read the video file meta data you specify at this path. Is there anything odd with this video? Can you open it OK outside of simba? Is it a mp4 or avi video? 

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/34761092/224714731-05b3a159-5615-4178-8784-3b2558d77501.png">

**Comment by ayakab0619** [comment]
Hi,
Exactly, my video path was wrong. It now works.
Thank you so much!

**Comment by sronilsson** [comment]
🚀
