### ISSUE TITLE
Report: Upper Limit in Memory with pandas [MemoryError]

### ISSUE THREAD

**Issue by JensBlack** [sgoldenlab/simba#24]
**Disclaimer**
This is not a SimBa code bug. But probably a pandas or system specific behavior. This is why I called this "Report". Please feel free to close the issue if you see fit.

**Describe the bug**
As with all machine learning problems, I thought the best way to solve accuracy problems is to throw data at it:

Trying out 10 csv files from my experiments (about 600k frames in total) resulted in this error popping up. 
I included my system info to give you a better overview. As mentioned below this might happen from overcommitment protection within the OS.

```
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:   46.8s
Exception in thread Thread-20:
Traceback (most recent call last):
  File "D:\Anaconda\envs\simba-gpu\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\envs\simba-gpu\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "simba.py", line 3764, in trainmultimodel
    train_multimodel(self.projectconfigini)
  File "C:\Users\schwa\PycharmProjects\simba\simba\train_multiple_models_from_meta.py", line 164, in train_multimodel
    features = baseFeatureFrame.copy()
  File "D:\Anaconda\envs\simba-gpu\lib\site-packages\pandas\core\generic.py", line 5996, in copy
    data = self._data.copy(deep=deep)
  File "D:\Anaconda\envs\simba-gpu\lib\site-packages\pandas\core\internals\managers.py", line 788, in copy
    return self.apply("copy", axes=new_axes, deep=deep, do_integrity_check=False)
  File "D:\Anaconda\envs\simba-gpu\lib\site-packages\pandas\core\internals\managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\Anaconda\envs\simba-gpu\lib\site-packages\pandas\core\internals\blocks.py", line 771, in copy
    values = values.copy()
MemoryError: Unable to allocate 3.22 GiB for an array with shape (787, 549864) and data type float64
```
**Simba console output**

![grafik](https://user-images.githubusercontent.com/44863941/78978150-9278a380-7b19-11ea-876e-4033929234c3.png)

**What google says:**
A quick google hints at a OS issue/safety mechanism for memory allocation (although the thread is originally for Linux). [Stackoverflow](https://stackoverflow.com/questions/57507832/unable-to-allocate-array-with-shape-and-data-type). There are a few provided solutions (including for windows) but I have not tried them yet.

**Desktop (please complete the following information):**

Simba-GPU installation with Anaconda
Operating System: Windows 10 Home 64-bit (10.0, Build 18362) (18362.19h1_release.190318-1202)
System Manufacturer: LENOVO
System Model: 81UH
Processor: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
Memory: 16384MB RAM
 

**Additional context**
As I was writing this issue, I restarted the process and I was able to reproduce the same result. But to my confusion the training continued despite of the memory issue.

![grafik](https://user-images.githubusercontent.com/44863941/78977589-a40d7b80-7b18-11ea-9946-2734d5d1be75.png)

**Comment by JensBlack** [comment]
**Follow up**
Same training (several moments later).
I was training with the "multi model setting" and encountered another issue after a while.
It completed the first model without any further error, although the console tells me that it created several other 2000 task jobs over and over. The SimBa console tells me that it just started the second model (which seems to have crashed now completely, although i will leave it running for a while to see whether anything changes). Interestingly the 2nd model has less positive training data then the first and this is a similiar but different error.

![grafik](https://user-images.githubusercontent.com/44863941/78987348-0ae95f80-7b2e-11ea-80c7-4e3dc04c560d.png)

**SimBa console ouput**

![grafik](https://user-images.githubusercontent.com/44863941/78987393-26ed0100-7b2e-11ea-81ca-bb398b8d7d64.png)

**Comment by sgoldenlab** [comment]
Thanks @JensBlack - I think it's in part relate to the large number of features created by SimBA when training on user-defined body-parts, combined with the number of targets, and the 16GB RAM - I will wok to reduce the sizes of the arrays and dataframe.

**Comment by inoejj** [comment]
@JensBlack , what version of python is in your machine? Python 3.6 32 bit or Python 3.6 64 bit?

**Comment by JensBlack** [comment]
I will post `conda info` just to give you the full overview, but i am pretty sure that I have 64bit.

```
     active environment : simba-gpu
    active env location : D:\Anaconda\envs\simba-gpu
            shell level : 2
       user config file : C:\Users\schwa\.condarc
 populated config files : C:\Users\schwa\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
       base environment : D:\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\schwa\.conda\pkgs
                          C:\Users\schwa\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\schwa\.conda\envs
                          C:\Users\schwa\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by inoejj** [comment]
@JensBlack , let's try to change your python to 3.6, in conda and give it a shot.
