### ISSUE TITLE
Problem training single model (global enviroment)

### ISSUE THREAD

**Issue by gemajpg** [sgoldenlab/simba#246]
**Describe the bug**
I follow the steps of this guide: https://github.com/sgoldenlab/simba/blob/master/docs/Scenario1.md

Yet, when I finally get to train the model, it gives me the following error: 

![image](https://user-images.githubusercontent.com/126618342/230721756-cd96fce9-35fb-450f-a276-b60fde6d8b63.png)

![image](https://user-images.githubusercontent.com/126618342/230721770-097ea81e-0965-4a54-894d-447eb60c7b89.png)

Am I doing something wrong?

This is what I put on settings:
![image](https://user-images.githubusercontent.com/126618342/230722036-9a6c6626-590d-43fd-8c02-de4c381e57af.png)

I tried downloading the file with the example for the hyper-parameters but I don't really know how.

**Desktop:**
 - OS: Windows 10.
 - Python Version 3.6.0
 - Are you using anaconda? Yes

**Comment by sronilsson** [comment]
Hi @gemajpg ! How many body-parts and animals does your tracking data track? Something goes wrong early in training, when SimBA is trying to split the body-part coordinates data columns from the rest of the columns. One body-part, `Right_ear` of animal 2 is expected but can't be found in the data. The data is stored in the `project_folder/csv/targets_inserted` directory. I see you have one file in there, if you check it, what column headers do you see?

**Comment by gemajpg** [comment]
@sronilsson  Hi! Four body parts for two animals. I actually made them just like the standard simBA has (nose, two ears and tail base). 

This is what is shown in the file. 
![image](https://user-images.githubusercontent.com/126618342/230897800-343be42c-b03b-4f23-a1fb-bd3d52f92978.png)

**Comment by sronilsson** [comment]
Thanks @gemajpg, got it, just to confirm, you selected the built in simba default 2 animal with four body-parts on each?

If you upgrade to simba 1.55.8 with `pip install simba-uw-tf-dev --upgrade`, do you still see the error?

**Comment by gemajpg** [comment]
@sronilsson Yes, that's what I selected. 

I upgraded it but I still see the error. 

![image](https://user-images.githubusercontent.com/126618342/230906103-1cbbfe0d-00ef-47f8-91f7-f80ab7e2eb3e.png)

**Comment by sronilsson** [comment]
Thanks @gemajpg - is your project small? Can it be zipped up and shared, and I can take a look?

**Comment by sronilsson** [comment]
Got it thanks!

**Comment by sronilsson** [comment]
For whatever reason (maybe bug from using multiple SimBA versions in your project.. that I will look into) your SimBA project has a body-part called `Right_ear_2`, while in the actual data in your project, the same body-part is named `Ear_right_2`. 

To fix this: 

1) Go to `prueba/project_folder/logs/measures/pose_configs/bp_names` and change `Right_ear_2` to `Ear_right_2` as in screengrab below.
<img width="409" alt="image" src="https://user-images.githubusercontent.com/34761092/230920764-dd2e9072-3159-4bdf-b960-c3e7f435cf54.png">

2). Update simba again, should be version `1.55.9` now. 

3). Run simba with `simba`. 

Let me know how it goes!

**Comment by gemajpg** [comment]
@sronilsson it worked! Thank you!
