### ISSUE TITLE
Impossible to analyse ROI with 1 FPS video

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#249]
Hello, 

I'm trying to analyze ROI from csv files obtained from DLC, for single animal, on Windows 10. 
My videos are 1 fps, and after I drew the ROIs, prompt returns: " Videos in your SimBA project have an FPS of 1 or less. Please use videos with more than one frame per second, or correct the inaccurate fps inside the `project_folder/logs/videos_info.csv` file " 

I was thinking to convert all my videos to >1 fps, but maybe there is a way to analyze 1 fps videos direclty?

Thank you, 
Best,

**Comment by sronilsson** [comment]
Hi @DorianBattivelli - do you have a traceback copy paste or screengrab of the OS terminal of the error and I will have a look around where it is thrown? I want to see why I put the limit at 1 FPS: you should be able to run it at 1 FPS although you may miss some events and velocity / movement can be off a bit at that resolution.

**Comment by DorianBattivelli** [comment]
Thanks for the quick answer, here what returns the terminal after I converted one video in 2 fps. Apparently it does like this frequency either :)
![Simba_Error_1fps](https://user-images.githubusercontent.com/66886884/236454412-b3ea54c5-c9e2-4626-8643-dc19d8fb9562.png)

**Comment by sronilsson** [comment]
Thanks @DorianBattivelli - for troubleshooting, would you mind using latest SimBA? If you don't want to upgrade, could you test in a new conda environment with the latest SimBA and check how the error looks like?

**Comment by DorianBattivelli** [comment]
![Simba_Error_1fps](https://user-images.githubusercontent.com/66886884/236456449-b235902e-6c65-434a-bf37-4b0459564248.png)

**Comment by sronilsson** [comment]
Ah thank you! Just to confirm, SimBA grabs the file from the `project_folder/csv/outlier_corrected_movement_location` folder to perform the ROI analysis, do you have files representing your videos in this directory?

**Comment by DorianBattivelli** [comment]
No I don't... Should I run outlier correction again?

**Comment by sronilsson** [comment]
Yes, or click to skip - make sure the videos that you want analyzed are represented in that directory.

**Comment by DorianBattivelli** [comment]
Everything works fine, it looks we did not run the outlier step properly, 

Thank you!

**Comment by sronilsson** [comment]
Cheers @DorianBattivelli ! Let me know if any other errors pop up!

**Comment by sronilsson** [comment]
Ah got it, you should not have to re-draw, maybe there is a key name mis-match between versions I haven't taken care off. 

Can you drop your `project_folder/logs/measures/ROI_definitions.h5` files here and I can see if I can replicate it and fix?

**Comment by sronilsson** [comment]
Does it work if you zip the file and drop it here?

**Comment by DorianBattivelli** [comment]
[ezyzip.zip](https://github.com/sgoldenlab/simba/files/11407552/ezyzip.zip)

**Comment by sronilsson** [comment]
@DorianBattivelli - unzip this one try replacing your `project_folder/logs/measures/ROI_definitions.h5` with this it and let me know if that fixes it:

[ROI_definitions.h5.zip](https://github.com/sgoldenlab/simba/files/11407720/ROI_definitions.h5.zip)

**Comment by DorianBattivelli** [comment]
Amazing, everything is now working fine! Thank you

**Comment by sronilsson** [comment]
Cheers! I will insert a fix in simba next week to make sure this can't happen again.
