### ISSUE TITLE
Problem with Analyse ROI Data

### ISSUE THREAD

**Issue by 2909ft** [sgoldenlab/simba#25]
Hello everybody!

First of all, thank you so much for implementing the new features on simba! I can also see that you have added a lot of new (very clear!) documentation, and I really appreciate your effort, as I am sure it took a lot of hours. Thank you so much!

That being said, I am having some issues running the analysis of the ROI Data. All of the steps ran smoothly until then, but when I click the Analyse ROI Data button, the cmd terminal displays this:
<img width="441" alt="Screen Shot 2020-04-25 at 22 12 05" src="https://user-images.githubusercontent.com/57539512/80291025-dc7c9e80-8741-11ea-838d-8ba68cfacdf6.png"> 
The steps before this ran correctly, I believe, as an ROI_definitions h5 file was created 
<img width="616" alt="Screen Shot 2020-04-25 at 22 09 20" src="https://user-images.githubusercontent.com/57539512/80291042-0a61e300-8742-11ea-9fe5-d7bca9363e8f.png">

Any idea how to solve this? I am using Python 3.6.4

**Comment by sgoldenlab** [comment]
Hi @2909ft ! This TypeError  happens when SimBA can't find the frame rate of the video it is trying to analyze. The frame-rate is saved in the video_info.csv in the project_folder/logs directory. 

I'd suggest open this csv file and make sure that your videos are represented as single row with a frame rate number in the frame rate column. Also make sure that you don't have two rows with the same video name: "the series to class int" suggests that SimBA finds multiple rows in the video_info.csv file with the same video name, and can't convert the multiple instances to a single fps integer number. 

If the error still persists, then also make sure that your video file names does not contain any spaces.

Let me know id that fixes the issue!

**Comment by 2909ft** [comment]
Hello!

Thank you so much for the reply! The names are different for each video, and there are no spaces on them. Any other suggestion?

<img width="954" alt="Screen Shot 2020-04-26 at 02 25 32" src="https://user-images.githubusercontent.com/57539512/80294889-8588c080-8765-11ea-8000-4754aea41491.png">

**Comment by sgoldenlab** [comment]
Hmm.. would you have a screenshot of the content of your project_folder/csv/outlier_correction_movement_location folder? Could it be that you have any files in there, that are not represented in the video_info.csv file?

**Comment by 2909ft** [comment]
It seems like everything matches 
<img width="811" alt="Screen Shot 2020-04-26 at 03 04 16" src="https://user-images.githubusercontent.com/57539512/80295457-ae5f8480-876a-11ea-95b6-8a98b96580f6.png">
Do I need to remove the "DLC_resnet50_DeepLabCut_Labels_ACC_PAGJan21shuffle1_24500" bit?

**Comment by 2909ft** [comment]
Ah nevermind, just realised I placed them there manually. I have created a new simba project, this time using the import tracking data feature of the GUI, and the names match. Thank you for your patience and apologies for the inconvenience :)

**Comment by sgoldenlab** [comment]
No trouble at allow, just ask if anything else pops up @2909ft  SimBA removes the long dlc model iteration reference from the filename when it's imported. It makes the file names and paths more straightforward to handle in python, and easier to look at

**Comment by 2909ft** [comment]
Hello again!

This time I was trying to generate the data plots, and this error occured 
<img width="436" alt="Screen Shot 2020-04-27 at 21 27 27" src="https://user-images.githubusercontent.com/57539512/80417796-43c75980-88ce-11ea-94fd-496b9c4730c3.png">
It seems like simba is looking for the column "Movement_mouse_1_centroid", right? However, on the machine results folder, the files have a column called "Movement_mouse_centroid". Could this be the reason why I got this error? (I'm only using 1 mouse)

**Comment by sgoldenlab** [comment]
Yes, that's definitely the reason and this shouldn't happen - I will look over the code. 

First can you tell me what body part pose configuration you are using, and how many animals you are tracking? 

Also, when was the last time you downloaded SimBA? A similar bug, that could cause this error, was fixed last week.

**Comment by 2909ft** [comment]
Thanks for the reply! I am using the built in body-pose configs (the 8bp one, for 1 animal). I downloaded simba last Friday again.

**Comment by sgoldenlab** [comment]
Thanks, I can spot the bug in the plot script :) let me just confirm that the script is working before I upload it. I'll let you know when done.

**Comment by sgoldenlab** [comment]
@2909ft - I've made an update , can you download SimBA again, load your project, and let me know if it works? Thanks for reporting this.

**Comment by 2909ft** [comment]
Yes! It works! Thanks a bunch!

**Comment by 2909ft** [comment]
Another issue has popped up, it seems. I was trying to merge the Sklearn results with the Path and the live data and everything works fine until the second-to-last frame of the first video being analysed.

**Comment by 2909ft** [comment]
Another issue has popped up, it seems. I was trying to merge the Sklearn results with the Path and the live data and everything works fine until the second-to-last frame of the first video being analysed, when I get the following error message:
<img width="830" alt="Screen Shot 2020-04-28 at 01 34 15" src="https://user-images.githubusercontent.com/57539512/80434651-42a82380-88f2-11ea-948b-d0e6ca52cc5d.png">
If I check the results on the output/merged folder, there is one video which seems to have something merged, but it is very blurry (see screenshot). Both the Sklearn results, the path, and the live data seem to have been generated correctly, so I don't really know what the issue is here. Any suggestions?

**Comment by sgoldenlab** [comment]
Hey @2909ft - the error, when trying to merge the sklearn, path and live plots, would happen if there is an unequal number of frames in the three folders. Let's say there are 14108 frames of sklearn, but 14107 'live data' plots, then this error would pop up on the last frame. Could you open the project_folder/frames/output/sklearn and so on, and for each of your, and check that the folders named after your videos contain any equal number of frames? 

It is very grainy indeed - I have not seen that before I will have to have a think

**Comment by 2909ft** [comment]
The folders all have 14106 frames, including the input one. I just checked and this is also the number of frames on the DLC csv file for that video. Weird

**Comment by sgoldenlab** [comment]
Hmm, could it be that some frames in the middle of the video has been removed/renamed for some reason? E.g., does it say 14106 at the bottom of the window for each video frame folder like this below? It's likely you do but I can see no other reason for this to happen. 

Is it possible for you to merge other combinations of frames into a video?

![image](https://user-images.githubusercontent.com/50497030/80437607-de1ba300-88b6-11ea-8e52-2ac206960c3e.png)

**Comment by sgoldenlab** [comment]
You don't happen to have any other files, or folders, hidden or otherwise, in the first videos Sklearn output frames folder do you?

**Comment by 2909ft** [comment]
The number of files is indeed 14108 for all of the folders (14107 png, if we count the 0 frame, and one system Thumbs.db file). Could this db file be the source of the issue?

**Comment by sgoldenlab** [comment]
Ah I don't know what "Thumbs.db" is, or where it comes from, it should not be there - it is not part of SimBA. Could you delete it or move it and try gain?

**Comment by 2909ft** [comment]
Thumbs.db seems to be a system file that Windows uses to store tumbnails for all the files on a given folder, it was automatically generated, I did not put it there. I have now deleted all of them and the merge seems to work correctly until the bit where it actually merges. This is the video result, with the error message on the side. The error appears once all the image frames for the first video have been processed.
<img width="1207" alt="Screen Shot 2020-04-28 at 13 52 21" src="https://user-images.githubusercontent.com/57539512/80489635-06a7a980-8958-11ea-8eb0-24492823552b.png">

**Comment by sgoldenlab** [comment]
Interesting - I won't be able to re-create this error but will make a few updates to the code to count / merge only image files and disregard anything else

**Comment by 2909ft** [comment]
Brilliant thanks!

**Comment by sgoldenlab** [comment]
Hi @2909ft - I've introduced some fixes, that should avoid the issues you are having with the .db files. And it now catches the errors if the number of files don't add up. 

Would you mind downloading SimBA again, load your project, and see if it works? I am not sure what's going on with the grainy messed up frames. Let's see if this fixes it first.

**Comment by 2909ft** [comment]
Yes it works!! The merged video is now fine, no grainy textures :)) However (this is something minor, but I think you ought to know), the sklearn results and the path plots are on a different orientation- when the mouse is going south on the video, the path shows a dot going north etc.

Thank you so much!! I have done a correlation analysis between what I behaviours I had scored on a given video and what SimBA scored, and I got a 0.998 correlation value! Truly impressive!!

**Comment by sgoldenlab** [comment]
Nice one! Thanks for letting me know - it makes me happy to hear it's working. I'll look in to the rotation of the path plot. I suspect it's line 131 in path_plot.py, and a quick fix would be setting it to  270 rather than 90, but I'll insert something more robust. 

![image](https://user-images.githubusercontent.com/50497030/80598844-cb03f280-89de-11ea-9283-135eebfebd76.png)

**Comment by sgoldenlab** [comment]
Nice on! Thanks for letting me know - makes me happy to hear that it is working. For the path plot, I will insert a fix - I suspect it is line 128 in merge_frames_movie.py, that should be 270 rather than 90, but ill look it over and make sure it is robust

![image](https://user-images.githubusercontent.com/50497030/80599630-136fe000-89e0-11ea-9a37-dc697912c481.png)

**Comment by 2909ft** [comment]
Hello again! 

I have created a new project but when I run the Outlier Correction step, everything goes fine for the movement outliers, but when it switches to the location outliers, this error message appears. Any idea why this might be? Too many outliers?
<img width="441" alt="Screen Shot 2020-05-01 at 22 53 10" src="https://user-images.githubusercontent.com/57539512/80844673-257b9980-8bff-11ea-8c31-71e7f7356423.png">
