### ISSUE TITLE
Issue with polygon ROI

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#259]
Hello,

Did you release an update to solve the issue I faced last week? Unfortunately, I went ahead with another project meantime, and so my H5 file has the same error regarding polygons, can I send it to you?

Thank you, 
Best,

**Comment by sronilsson** [comment]
Hi @DorianBattivelli! Yes I should have done - send it to me and I will fix it and check the bug against your H5 file again.

**Comment by sronilsson** [comment]
Also, could you show me a screengrab or copy/paste of the error and I can make sure it is the same error as last week?

**Comment by DorianBattivelli** [comment]
Well after your answer about the update, I updated the program, and run ROI analysis. It looks that no ROI is missing, so I think the fix worked during ROI analysis !

Thank you !

**Comment by sronilsson** [comment]
Thank you @DorianBattivelli - if you see any issues, please let me know though!
