### ISSUE TITLE
"Visualise pose-estimation" tool not working

### ISSUE THREAD

**Issue by alisabak** [sgoldenlab/simba#266]
Dear SimBA team,

I am trying to use a tool "Visualise pose-estimation", but it opens an empty window (screenshot below) and gives me the following error:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Alisa\anaconda3\envs\simba\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Alisa\anaconda3\envs\simba\lib\site-packages\simba\ui\pop_ups\visualize_pose_in_dir_pop_up.py", line 18, in __init__
    self.circle_size = Entry_Box(settings_frame, 'Circle size', 0, validation='numeric', labelwidth=20)
TypeError: __init__() got multiple values for argument 'labelwidth'`

<img width="302" alt="image" src="https://github.com/sgoldenlab/simba/assets/96051093/15619c6c-a7a9-4bd3-aebe-880a3bae6f4f">

I would greatly appreciate your help!

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Python Version 3.6.13
 - Are you using anaconda? yes

**Comment by sronilsson** [comment]
Thank you @alisabak for reporting, we appreciate it! If you upgrade simba to version `1.63.0` with `pip install simba-uw-tf-dev --upgrade` or `pip install simba-uw-tf-dev==1.63.0`, how does it look on your end?

**Comment by alisabak** [comment]
Thank you for such a quick fix! It works now.

Would it be possible to visualize tracking for individual videos? I takes a lot of time to generate videos for the whole project.

**Comment by sronilsson** [comment]
Thanks @alisabak - if you temporarily move some files out of the input directory and only keep the ones you want to visualize in the input folder, you will only get some videos. 

But yes, looking at this method, it looks a little dated and slow, no options to multi-process... I will see if I can update it and let you.

**Comment by sronilsson** [comment]
If you update SimBA again you should see this: 

<img width="641" alt="image" src="https://github.com/sgoldenlab/simba/assets/34761092/e8f821b1-cee6-478f-9e47-d1e5749ea27c">

You still can't visualize a single video in this method (it has to be a directory). But: if you select a higher number of cores in the `Core count` dropdown it will go much faster (follow progress in main OS terminal). 

Sometimes users just want to check if the pose-estimation looks good following smoothing/interpolation using this method, and they may not need the entire video. If that's the case, use the `Video output sample sizes (s)` dropdown. Here, if you select e.g., 100, then only the first 100s of each video will be created and things will be a little faster.. Let us know if somethings missing Thanks again

**Comment by alisabak** [comment]
Thank you @sronilsson, that is exactly what I needed!
