### ISSUE TITLE
Error when extecuting SimBA.py

### ISSUE THREAD

**Issue by Ejdrup** [sgoldenlab/simba#27]
When executing SimBA.py I get the following error:

My input:
`C:\ProgramData\simba\simba>python SimBA.py`
Error output:
```
C:\ProgramData\simba\simba>python SimBA.py
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 960, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2020-04-27 14:43:13.667999: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
```

Passing:
```
python
import numpy as np
np.__version__
```
returns 1.14.5, which is what is specified in the requirements.txt.

**Comment by Ejdrup** [comment]
After chewing myself through every requirement that wasn't the correct version I finally got it to work. In short, the supplied requirements.txt did not contain a setup of versions that worked for me.

**Comment by sgoldenlab** [comment]
Hi @Ejdrup thanks for reporting this - yes SimBA requires numpy 1.18.1, which seems to be the numpy version specified in the requirements.txt. 

For anyone else seeing this error at startup, run:
`pip install numpy==1.18.1`

If the numpy install failed, there is risk the installation of correct versions of pandas/pytables also may have failed which could cause errors further down the line. For the correct versions of pandas/pytables, run:

`pip install pandas==0.25.3`
`pip install tables==3.5.1`

Thanks again
