### ISSUE TITLE
SIMBA FEATURE NUMBER MISMATCH ERROR

### ISSUE THREAD

**Issue by 13281306705** [sgoldenlab/simba#276]
Hello, I'm sorry to bother you. When I clicked on 'Run Model' under the 'Run machine model' option in simba, I encountered an error:      SIMBA FEATURE NUMBER MISMATCH ERROR: Mismatch in the number of features in input file D:/simbaAndDeepLabCut/123/loxy/models/generated_ Models/run. sav, and what is expected by the model run The model expects 153 features The data contains 155 features. Do you know what caused this?

**Comment by sronilsson** [comment]
Hi @13281306705! Do you have an error msg from the operating system terminal? 

This error happens when you build a model using the data files inside  the `project_folder/csv/targets_inserted` directory, and each file in this directory contains 153 features (all columns minus the annotation columns and the body-part columns). 

You then try to run the model on your data inside the `project_folder/csv/machine_results` directory, and SimBA finds 155 columns in a file. Do you see two columns that may have sneaked in by mistake in a `project_folder/csv/machine_results` file?

Note: The error msg reads, **SIMBA FEATURE NUMBER MISMATCH ERROR: Mismatch in the number of features in input file D:/simbaAndDeepLabCut/123/loxy/models/generated_ Models/run. sav** It is a error msg bug, which I will fix now, and shouldn't affect the program or cause the error. It should read **SIMBA FEATURE NUMBER MISMATCH ERROR: Mismatch in the number of features in input file TheVideoFileNameYourTrying toAnalyze*

**Comment by sronilsson** [comment]
... is it possible you selected a file to use in validation that lives in `project_folder/csv/targets_inserted` rather than in `project_folder/csv/features_extracted` ?

**Comment by 13281306705** [comment]
> ... is it possible you selected a file to use in validation that lives in `project_folder/csv/targets_inserted` rather than in `project_folder/csv/features_extracted` ?…您是否选择了一个位于 `project_folder/csv/targets_inserted` 而非 `project_folder/csv/features_extracted` 中的文件用于验证？

> 
Hello, this is the detailed error message:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda3\envs\simba\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 372, in <lambda>
    button_runvalidmodel = Button(label_model_validation, text='RUN MODEL', fg='blue', command=lambda: self.validate_model_first_step())
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 566, in validate_model_first_step
    clf_path=self.modelfile.file_path)
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\model\inference_validation.py", line 48, in __init__
    data_df = read_df(input_file_path, self.file_type)
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\utils\read_write.py", line 87, in read_df
    raise InvalidFileTypeError(msg=f'{file_path} is not a valid CSV file')
simba.utils.errors.InvalidFileTypeError: D:/simbaAndDeepLabCut/123/lxy/project_folder/csv/input_csv/mouse.csv is not a valid CSV file
Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\anaconda3\envs\simba\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 372, in <lambda>
    button_runvalidmodel = Button(label_model_validation, text='RUN MODEL', fg='blue', command=lambda: self.validate_model_first_step())
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 566, in validate_model_first_step
    clf_path=self.modelfile.file_path)
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\model\inference_validation.py", line 53, in __init__
    output_df[probability_col_name] = self.clf_predict_proba(clf=clf, x_df=data_df, model_name=classifier_name, data_path=clf_path)
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\mixins\train_model_mixin.py", line 971, in clf_predict_proba
    raise FeatureNumberMismatchError(f'Mismatch in the number of features in input file {data_path}, and what is expected by the model {model_name}. The model expects {str(clf.n_features_)} features. The data contains {len(x_df.columns)} features.')
simba.utils.errors.FeatureNumberMismatchError: Mismatch in the number of features in input file D:/simbaAndDeepLabCut/123/lxy/models/generated_models/run.sav, and what is expected by the model run. The model expects 153 features. The data contains 155 features.
Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\anaconda3\envs\simba\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 372, in <lambda>
    button_runvalidmodel = Button(label_model_validation, text='RUN MODEL', fg='blue', command=lambda: self.validate_model_first_step())
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 566, in validate_model_first_step
    clf_path=self.modelfile.file_path)
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\model\inference_validation.py", line 53, in __init__
    output_df[probability_col_name] = self.clf_predict_proba(clf=clf, x_df=data_df, model_name=classifier_name, data_path=clf_path)
  File "d:\anaconda3\envs\simba\lib\site-packages\simba\mixins\train_model_mixin.py", line 971, in clf_predict_proba
    raise FeatureNumberMismatchError(f'Mismatch in the number of features in input file {data_path}, and what is expected by the model {model_name}. The model expects {str(clf.n_features_)} features. The data contains {len(x_df.columns)} features.')
simba.utils.errors.FeatureNumberMismatchError: Mismatch in the number of features in input file D:/simbaAndDeepLabCut/123/lxy/models/generated_models/run.sav, and what is expected by the model run. The model expects 153 features. The data contains 155 features.

After listening to your description, I roughly understand the reason for the error. Indeed, I chose project_ folder/csv/targets_ Inserted for validation.Thank you very much for your answer.

**Comment by sronilsson** [comment]
Got it! Yes, its likely that those files contain two additional columns (your behavior annotations) which we don't want when running validation.
