### ISSUE TITLE
ROIs H5 file convertion 

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#279]
Hello, 

Could you please tell me how to convert the H5 ROIs definition file in CSV or a text file ? And provide a way to easily inteerpret the numbers there? 

Thank you, 
Best,

**Comment by sronilsson** [comment]
Hi @DorianBattivelli - good point, we are missing a method for this. Let me type one up and get back to you.

**Comment by sronilsson** [comment]
@DorianBattivelli The function would output separate files for different shape types like this. Is that that what you are looking for? 

[polygons_20230809094913.csv](https://github.com/sgoldenlab/simba/files/12303441/polygons_20230809094913.csv)
[rectangles_20230809094913.csv](https://github.com/sgoldenlab/simba/files/12303442/rectangles_20230809094913.csv)

**Comment by sronilsson** [comment]
It exist in the tools menu if you upgrade SimBA. Let me know if anything is missing or if want other formatting options and we can insert it.


<img width="1086" alt="image" src="https://github.com/sgoldenlab/simba/assets/34761092/278cec44-dae9-492f-b2e4-bc8094657d2e">

**Comment by DorianBattivelli** [comment]
Super, it's exactly what I was looking for, 

Thank you, 
Best,
