### ISSUE TITLE
no ROI_features_summary csv file created

### ISSUE THREAD

**Issue by filos93** [sgoldenlab/simba#290]
**Describe the bug**
Hey, thanks so much for the fantastic software and all the hard work, I have a problem with the creation of the ROI_features_summary CSV file. After I analyze roi aggregates, extract features, and then append roi data to features, I cannot get any ROI_features_summary CSV file. I do not get any error message back, I just do not get the file. As I am using the latest version of SimBA (version 1.73.3), I would like to know if you do not get such file anymore in the latest version or if I have to run some additional steps. Please, let me know. Thanks in advance.

**To Reproduce**
1. Draw a rectangle roi
2. Analyze roi data aggregates
3. append roi data to features (once extracted)
4. no error, but no ROI summary csv file generated 

**Expected behavior**
I would expect to get a ROI_features_summary_####.csv file as mentioned in https://github.com/sgoldenlab/simba/blob/master/docs/ROI_tutorial.md#part-3-generating-features-from-roi-data

**Screenshots**
n/a.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version 3.6
 - Are you using anaconda? yes, I created a virtual env
 

**Additional context**
I would like to use the info from the ROI summary csv file especially for ROI directionality analysis (I used similar bp labelling that include nose, left ear, and right ear tracking as specified by you), in particular the sum of time (in seconds) that each animal spent directed towards the ROI in my video

**Comment by sronilsson** [comment]
Hi @filos93 - thank you for reporting this and good catch! Looking at the code, it looks like this file output was lost in translation, probably when we introduced the user option to include ROI features based on body-parts **and/or** ROI features based on animals, I will insert it again and let you know.

**Comment by sronilsson** [comment]
@filos93 if you upgrade to simba 1.73.5 with `pip install simba-uw-tf-dev --upgrade`, how does it look on your end? 

Thanks
Simon

**Comment by filos93** [comment]
@sronilsson I upgraded to the latest version (v. 1.73.5) and it worked perfectly, the ROI_features_summary CSV file was created also including directionality info (I attached screenshots for others)
![Screenshot (803)](https://github.com/sgoldenlab/simba/assets/64312024/420692d5-175a-442f-9e80-de9e6c681a1e)
![Screenshot (804)](https://github.com/sgoldenlab/simba/assets/64312024/e4e3ee30-6a64-4857-a750-1ae690ecd6dc)
Thank you so much for all the support
