### ISSUE TITLE
superimpose frame count on video

### ISSUE THREAD

**Issue by filos93** [sgoldenlab/simba#292]
**Describe the bug**
I would like to superimpose frame count on a video, however, I keep getting the same error message "Fontconfig error: Cannot load default config file: No such file: (null)", the SimBA GUI tells me that the video is generated and I can see it in the folder but it has 0 bytes, any idea how to solve this? thanks in advance 

**To Reproduce**
1. Go to 'SimBA GUI
2. Click on 'Tools'
3. Scroll down to 'Superimpose frame numbers on video'
4. Browse 'VIDEO PATH' and RUN (no GPU used)

**Expected behavior**
I would expect to get frame number overlay on the video.

**Screenshots**
in attachment

**Desktop (please complete the following information):**
 - Windows 11
 - Python Version 3.6.13
 - Are you using anaconda? Yes, created a virtual env with SimBA
 

**Additional context**
n/a.

![Screenshot (829)](https://github.com/sgoldenlab/simba/assets/64312024/fdde8513-b1af-4167-9cf2-f89f7df6f2b2)
![Screenshot (830)](https://github.com/sgoldenlab/simba/assets/64312024/f2fb23f4-6cb7-4422-892e-f80cfb5b57a2)

**Comment by sronilsson** [comment]
Thanks for reporting this @filos93 ! Let me see if I can recreate it and insert a fix.

**Comment by sronilsson** [comment]
Hi @filos93 - I tried to recreate your error, but I couldn't, neither on Windows10 or MacOS (I don't have access to Win11 at the moment). 

I tried to insert a fix nevertheless, if you update SimBA again (`pip install simba-uw-tf-dev --upgrade) what do you see?

 The fix is (i) use the font that comes with SimBA, (ii) if that font can't be found, then use Arial.ttf located in `C:/Windows/fonts` (as far I know it is located in `C:/Windows/fonts` in Win11), (iii) if Arial can't be found, use the first font found in `C:/Windows/fonts`.

**Comment by filos93** [comment]
hey @sronilsson thanks for the support, unfortunately I could not make it work even upgrading, SimBA tells me the file is generated but when I check it is a 0-byte file, the terminal continues to generate the same error message of "Fontconfig error: Cannot load default config file". I attached some screenshots about what I get in the terminal, how it looks in SimBA and how the code looks to me, hope these can help us, please let me know

![Screenshot (840)](https://github.com/sgoldenlab/simba/assets/64312024/7b810de8-5462-4395-8a4c-ba6fbaa10265)
![Screenshot (837)](https://github.com/sgoldenlab/simba/assets/64312024/8af94281-1455-405e-bffd-bee4ab84edd4)
![Screenshot (841)](https://github.com/sgoldenlab/simba/assets/64312024/c2162c1c-ff71-4875-b0bf-49e1555dd724)

**Comment by sronilsson** [comment]
Thanks for testing @filos93 - lets see how this could come about. 

If you look at the path that SimBA is printing out in the file explorer:

<img width="524" alt="image" src="https://github.com/sgoldenlab/simba/assets/34761092/3b003f33-f8c5-4502-ab01-fd3eef1a5722">

Does this file exist on your system?

**Comment by filos93** [comment]
@sronilsson the file "UbuntuMono-Regular" exists and it is 186kb, I don't think is corrupted, I attached some screenshots to help, thanks 

![Screenshot (843)](https://github.com/sgoldenlab/simba/assets/64312024/eb2cef56-bbf4-4eee-9c1c-2386d30d5336)
![Screenshot (844)](https://github.com/sgoldenlab/simba/assets/64312024/0a842e43-d8f8-4bb0-8d11-f184781c4380)

**Comment by sronilsson** [comment]
That all looks in order.. I don't get - yet- how this can happen. I am going to have to borrow and troubleshoot on a Win11 computer today and see if I can recreate this error myself.

**Comment by sronilsson** [comment]
Alright @filos93, I think I might have figured it out.. On Windows, the paths should be expressed with `/` and not `\` and the drive initial should be omitted. At least that helped me remove the font config warning on my end.
If that fails FFMpeg appears to pick system default font, so I don't know why that didn't happen in your case so I am still a little unsure. 

If you do `pip install simba-uw-tf-dev --upgrade`to version 1.74.5, how does it look?

**Comment by filos93** [comment]
hey @sronilsson it worked thank you so much :) the only thing the SimBA GUI did not tell me that the video was created and I could not see the video at first, when I tried to superimpose again I was able to find the video in the right folder within SimBA, so I had to move the video when using SimBA to another location and at that point I could see the video, this was just to let you and the other users know, again thanks a lot for all your support!!

![Screenshot (851)](https://github.com/sgoldenlab/simba/assets/64312024/f1d2af63-0ab6-4910-b443-7366b3b6aa92)
![Screenshot (849)](https://github.com/sgoldenlab/simba/assets/64312024/43134089-099b-4dfc-9a33-ca070d2b7ecb)
![Screenshot (850)](https://github.com/sgoldenlab/simba/assets/64312024/d4681f08-ce7a-4eba-b71a-30099aeca6c7)

**Comment by sronilsson** [comment]
Ah good point @filos93, seem to have dropped the print statement in the speed of things. I added it in version `1.74.6` but please let me know if any more issues or oddeties pop up. 

Simon

**Comment by filos93** [comment]
hey @sronilsson thank you so much, everything worked perfectly, really thanks for all the troubleshooting and the support :)

![Screenshot (853)](https://github.com/sgoldenlab/simba/assets/64312024/63c5eeb5-fd27-41ce-9ff9-1d888763e120)
![Screenshot (854)](https://github.com/sgoldenlab/simba/assets/64312024/80df7cb6-a4cc-4ca8-8a2e-d2338a2713d3)
