### ISSUE TITLE
Stopped while assigning IDs to two animals

### ISSUE THREAD

**Issue by linab8** [sgoldenlab/simba#300]
Hi! I was assigning identities to two animals in SimBa. After I clicked X for a couple of times (because the frames weren't good enough for me to figure out the IDs),  the small screen for assigning identity closed, and I was left with this (picture).
Is there a way to continue assigning IDs because I fear that if I leave the app and load the project, it'll skip this step, as has once happened already so I had to start a new project.

1. FInished creating project config and importing videos
2. Clicked to Import DLC .H5
3. Assigned ID to 70/253 videos
4. Clicked X a few times in one video
5. Error

![Capture](https://github.com/sgoldenlab/simba/assets/148640900/4fcacb6c-bbb7-4901-a64d-1b7e76398ce3)

**Comment by sronilsson** [comment]
Hi @linab8! SimBA seems to have trouble with one of your files. Would you mind sharing the error you are seeing in the operating system terminal where you launched Simba when this happens either as a screengrab or copy paste it here?

**Comment by linab8** [comment]
Hi! Thank you for your answer, here's a screenshot of the terminal. @sronilsson 
![error](https://github.com/sgoldenlab/simba/assets/148640900/e63a0a57-833d-40cb-819f-2dd866e1c701)

**Comment by sronilsson** [comment]
Thanks @linab8! I can tell you what I think is happening, and I will insert something in the code that presents a interpretable error message and prevent this from happening.  

Each time you click to go `X` to go to another frame, SimBA goes 50 frames forward in the video. You click and eventually you get to frame `15050`. Next, SimBA tries to pull up your DeepLabCut tracking data for frame `15050` to display it on the screen. However, I suspect that the DeepLabCut tracking data for this video has data for fewer than `15050` frames. So SimBA can't find the data for frame number `15050`, and it breaks down.

**Comment by linab8** [comment]
Thank you for the info, it makes sense now! Do you know if there's a way to continue assigning IDs from this video onward or the only option is to start everything from scratch? @sronilsson

**Comment by sronilsson** [comment]
One possible way:

When you import data, you select a folder that contains DeepLabCut tracking data in. SimBA will search that folder for DeepLabCut .h5 files and loop over each one it finds and import it into your SimBA project. 

If you remove the h5 files from that selected folder which you have already imported, then SimBA shouldn't find them and should not try to import them again.

**Comment by linab8** [comment]
Thank you! It worked! @sronilsson
