### ISSUE TITLE
I can't extract frames

### ISSUE THREAD

**Issue by linab8** [sgoldenlab/simba#302]
Hello! I finished assigning IDs to multiple animals in Simba, but when I click on "Extract Frames" nothing happens. There's nothing going on in the Simba console nor in the command prompt, and the folder in which the frames should be is empty.

1. I uploaded the videos
2. Uploaded H5 files
3. Assigned IDs
4. Clicked on Extract Frames
5. Nothing happens

![extract](https://github.com/sgoldenlab/simba/assets/148640900/e0fe4aeb-f429-4d9c-8b1b-aa5dfc102571)
 
However, I see that it isn't necessary to extract frames any more, but I wasn't sure if I should skip it since the tutorials still mention extracting.

**Comment by sronilsson** [comment]
Hi @linab8 - there is no need to extract frames! You can proceed without that step
