### ISSUE TITLE
MetaKeys ImportError

### ISSUE THREAD

**Issue by rjd55** [sgoldenlab/simba#328]
I am trying to follow this notebook to use SimBA as python file: https://simba-uw-tf-dev.readthedocs.io/en/latest/nb/CLI%20Example%201.html

I haven't changed too much, apart from paths and the video settings. The problem comes from this line `InferenceBatch(config_path=CONFIG_PATH).run()`. Which causes this error: `from simba.utils.enums import (ConfigKey, Defaults, Dtypes, MetaKeys, Methods, ImportError: cannot import name 'MetaKeys' from 'simba.utils.enums' (/simba-master/simba/utils/enums.py)
`
I see that the MetaKeys are not defined in the enums.py. What are the MetaKeys and how do I define them?

Many thanks

**Comment by sronilsson** [comment]
Thanks @rjd55  - yes I think I know this one. There where a bunch of enums that where duplicated, so we recently removed some and placed them under a single enum class. 

Did you install simba by cloning the repo? I see that these updates are present in the pip package, but not the repo for some reason but I will fix that.

**Comment by sronilsson** [comment]
@rjd55 - I've update the repo now. If you run the latest version of simba (installed either through repo or pip) how does it look?

**Comment by rjd55** [comment]
Hi, I haven't checked through pip. But works with the cloned repo. Thank you!
