### ISSUE TITLE
Simba installation issue on Win10

### ISSUE THREAD

**Issue by adamltyson** [sgoldenlab/simba#33]
You might know about this bug, and I know I'm not installing simba as per the instructions (using a conda environment etc.), but it seems like it should be an acceptable way to install it.

**Describe the bug**
Installing simba on Windows 10 in a conda environment fails due to geos DLL import error.

**To Reproduce**
```
conda create --name simba_bug_test python=3.6
conda activate simba_bug_test
git clone -b master https://github.com/sgoldenlab/simba.git
pip install -r simba\simba\requirements.txt
conda install cudatoolkit=10.0 cudnn
cd simba\simba
python SimBA.py
```
gives:
```
  File "C:\Users\adam.\.conda\envs\simba_bug_test\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\adam\.conda\envs\simba_bug_test\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\adam\.conda\envs\simba_bug_test\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
If I try:
```
pip uninstall shapely
pip install shapely
```
Then the error persists. However, if I install shapely from conda forge `conda install -c conda-forge shapely`, then simba loads.

_N.B. it's also a bit annoying that simba has to be run from `simba\simba`_ 

**Desktop (please complete the following information):**
 - Python Version **3.6.10**
 - Are you using anaconda? yep (well miniconda)

**Comment by sgoldenlab** [comment]
Hi @adamltyson - yes, shapely can cause issues at times - I've had a few if these raised and closed, could you try the fix in this link, and let me know if it works? 

https://github.com/sgoldenlab/simba/issues/11#issuecomment-596805732

*N.B. I will look into the simba/simba annoyance, see what others think - perhaps best to get a pip package*

**Comment by adamltyson** [comment]
Sorry I should have checked the closed issues. It's working for me by installing from conda, so from my POV all is fine. I can invisage other potential users giving up at this point though.

Just my 2c - I find distributing via pypi really convenient, and great to keep track of versions. If you ask me (which you didn't), I would:
* Set simba\simba\SimBA.py as a console entry point. 
* Add the images etc. to the manifest so you can reference them by location in the package. This might fix a lot of the mac/linux incompatibilities too
* Distribute via PyPI
* profit

Happy to submit a PR sometime if you like.

P.S. Really impressed with SimBA. I'm trying it out to present at lab meeting, and so far everything is super easy to use.

**Comment by sgoldenlab** [comment]
Thanks @adamltyson - and the first three of the 2c's have been on my mind for some time. It has just been the question of time an getting it done. With your nudge I'll see what we can get done this week. Thanks again

**Comment by sgoldenlab** [comment]
Hey @adamltyson - we've got a 'pip install' option up:

https://github.com/sgoldenlab/simba/blob/master/docs/installation.md

Would you mind trying it and see if it works OK on your end?

Thanks!

**Comment by adamltyson** [comment]
Hi,

If (after cuda & cudnn installation),  I try `pip install simba-uw-tf`, I get this error on Win 10 (similar on Ubuntu 18.04):

```
ERROR: tensorflow-gpu 1.14.0 has requirement protobuf>=3.6.1, but you'll have protobuf 3.6.0 which is incompatible.
ERROR: deeplabcut 2.0.9 has requirement imageio~=2.3.0, but you'll have imageio 2.8.0 which is incompatible.
ERROR: deeplabcut 2.0.9 has requirement numpy~=1.14.5, but you'll have numpy 1.18.1 which is incompatible.
ERROR: deeplabcut 2.0.9 has requirement python-dateutil~=2.7.3, but you'll have python-dateutil 2.8.1 which is incompatible.
ERROR: deeplabcut 2.0.9 has requirement scikit-learn~=0.19.2, but you'll have scikit-learn 0.22.2 which is incompatible.
ERROR: deeplabcut 2.0.9 has requirement six~=1.11.0, but you'll have six 1.14.0 which is incompatible.
ERROR: deeplabcut 2.0.9 has requirement wheel~=0.31.1, but you'll have wheel 0.34.2 which is incompatible.
```

**Comment by inoejj** [comment]
I have no problem installing and running simba-uw-no-tf. Were you installing both simba-uw-no-tf and simba-uw-tf on the same virtual environment?

**Comment by adamltyson** [comment]
I was, but the same thing happens in a fresh conda env, and is only fixed by reinstalling shapely from conda-forge.

**Comment by MMathisLab** [comment]
Is there a reason you pin `deeplabcut==2.0.9`? I would strongly suggest an update to at least 2.1.8.2; many important updates, bug fixes, etc in the past year.

**Comment by sgoldenlab** [comment]
Hi @MMathisLab - I will look over this and make it compatible asap. But I think it is primarily the pandas >= 1.0.0 dependency that made it more than a quick fix for me
