### ISSUE TITLE
Creation configuration project problem

### ISSUE THREAD

**Issue by Monica9577** [sgoldenlab/simba#331]
**Describe the bug**
When creating a new project, when I click on create a new configuration project, nothing happens in the main console of simba. And the folder where is suposed to be the new project lacks the configuration file.

**To Reproduce**

1. Open Anaconda
2. Open simba
3. go to file
4. create a new project
5. select the project directory and project name
6. add number of classifiers 
7. instert names of classifiers
8. Select tracking method and body points
9. create config file

Code error:
(NEW_SIMBA) C:\Users\monip>simba
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\monip\anaconda3\envs\NEW_SIMBA\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\monip\anaconda3\envs\NEW_SIMBA\lib\site-packages\simba\ui\create_project_ui.py", line 216, in <lambda>
    command=lambda: self.run(),
  File "C:\Users\monip\anaconda3\envs\NEW_SIMBA\lib\site-packages\simba\ui\create_project_ui.py", line 348, in run
    file_type=self.file_type_dropdown.getChoices(),
  File "C:\Users\monip\anaconda3\envs\NEW_SIMBA\lib\site-packages\simba\utils\config_creator.py", line 59, in __init__
    self.__create_configparser_config()
  File "C:\Users\monip\anaconda3\envs\NEW_SIMBA\lib\site-packages\simba\utils\config_creator.py", line 195, in __create_configparser_config
    ] = Dtypes.NONE.value
  File "C:\Users\monip\anaconda3\envs\NEW_SIMBA\lib\enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: CLASSIFIER

**Expected behavior**
The main console should show a succesfull project creation. And the configuration file should appear inside the "project_folder"

<img width="847" alt="Captura de pantalla 2024-02-15 224737" src="https://github.com/sgoldenlab/simba/assets/160180401/99a42bab-47d1-44df-9ce7-3b3046028c8e">

<img width="559" alt="image" src="https://github.com/sgoldenlab/simba/assets/160180401/73e24741-ad8e-4203-8dbd-394acb683f6b">

<img width="538" alt="image" src="https://github.com/sgoldenlab/simba/assets/160180401/10c52206-f862-4327-b312-1ce89ce4aa70">

**Desktop **
 - OS: Windows 11
 - Python Version  3.6.13
 - Are you using anaconda? Yes

**Comment by sronilsson** [comment]
Got it, thanks for letting me know @Monica9577 ! 

If you update simba to the latest version (using `pip install simba-uw-tf-dev --upgrade`) - does that fix the issue?

**Comment by Monica9577** [comment]
No, unfortunatelly it doesn't fix it

**Comment by phildong** [comment]
just want to add I'm having the exact same issue.
I'm on `simba-uw-tf-dev 1.85.2` and ubuntu 22.04.

**Comment by Monica9577** [comment]
Yes, I'm also on simba-uw-tf-dev 1.85.2 , with anaconda (also updated)

**Comment by sronilsson** [comment]
Thanks @Monica9577 and @phildong - I appreciate it. It's a bug you caught. I was able to recreate it and I inserted the fix in version `1.85.3` - if `pip install simba-uw-tf-dev --upgrade` didn't get you that version - can tou try `pip install simba-uw-tf-dev==1.85.3` and let me know how it looks on your end?

**Comment by Monica9577** [comment]
It's working now 
Thank you !

I used pip install simba-uw-tf-dev --upgrade and it installed the 1.85.3 version

**Comment by sronilsson** [comment]
Thanks @Monica9577 👍🏻  - please let me know if anything else comes up. @phildong - please let me.know if you see anything different

**Comment by phildong** [comment]
same here. I re-created my environment and I can confirm this bug is gone in `simba-uw-tf-dev 1.85.5`. Thank you @sronilsson !

**Comment by sronilsson** [comment]
thanks for letting me know @phildong !
