### ISSUE TITLE
Impossible to create ROI analysis

### ISSUE THREAD

**Issue by Monica9577** [sgoldenlab/simba#332]
**Describe the bug**
When trying to create ROI analysis, it doesn't create it 
- Error:
![2024-02-21](https://github.com/sgoldenlab/simba/assets/160180401/33f059e2-ac1f-44ca-a187-55de1dd6c6d4)

**To Reproduce**
After loading the project
import tracking data and videos
add the video parameters
draw ROIs (and save)
In analyse ROI data: click on analyse ROI data: aggregates

**Expected behavior**
A statement will be printed in the main SimBA terminal window noting that the process is complete. The ROI descriptive statistics can be found in the Project_folder/logs directory in two time-stamped files.

**Desktop (please complete the following information):**
 - OS: windows 10 (IntelCore I7; nividia gforce gpu)
 - Python Version 3.6.8
 - Are you using anaconda: Yes
 

**Additional context**
I already have the last version of Simba (1.85.5)

**Comment by sronilsson** [comment]
Thanks @Monica9577 - you caught a bug, that was likely introduced last week, I appreciate it! How does it look if you update SimBA with `pip install simba-uw-tf-dev --upgrade` version 1.85.6?

**Comment by Monica9577** [comment]
Yes, now is working 

But when I create a ROI video Features, it does all the process but the video is not in the folder it says its supposed to be

**Comment by sronilsson** [comment]
Thanks Monica - let me check on that too. FYI there was a bunch of updates last week that leaked in without being properly tested.. sorry about this.

**Comment by sronilsson** [comment]
@Monica9577 - when you get a chance, could you test in version 1.85.7? I've reverted to the old files and confirmed it works on my end but please let me know how it runs for you.

**Comment by Monica9577** [comment]
Now it works perfectly !!!

Thank you very much for your invaluable help, you and your team are doing a wonderful job.

**Comment by sronilsson** [comment]
Cheers @Monica9577 ! I think we have smoothened over must bugs from that kerfuffle,  but please let me know if you bump into more issues so we can fix those too, I don't have enough tests implemented yet, so your reports are very valuable
