### ISSUE TITLE
Running Simba as singularity container on HPC cluster

### ISSUE THREAD

**Issue by singhsaluja** [sgoldenlab/simba#34]
Hello, we are trying to run Simba as a singularity container on our cluster, the pip install fails (wxpython 4.0.1 fails to build because of older version of libgtk), we don't have root privileges on the machine so we decided to use singularity container instead. 

The official 'pip3 install simba-uw-tf' ran fine and the binary was built but when we try to launch Simba get get the error(s):

> ` ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
> 
> Singularity simba.sif:~/scratch> simba
> Traceback (most recent call last):
>   File "/usr/local/bin/simba", line 7, in <module>
>     from simba.SimBA import main
>   File "/usr/local/lib/python3.6/dist-packages/simba/SimBA.py", line 94, in <module>
>     from simba.dpk_script.train_model import trainDPKmodel
>   File "/usr/local/lib/python3.6/dist-packages/simba/dpk_script/train_model.py", line 6, in <module>
>     np.random.bit_generator = np.random._bit_generator
> AttributeError: module 'numpy.random' has no attribute '_bit_generator'

Here is the singularity recipe file we used:

> Bootstrap: docker
> From: ubuntu:18.04
> 
> %post
> 	apt-get -y update  && DEBIAN_FRONTEND=noninteractive
> 	apt-get install python3-pip -y
> 	apt-get install git -y
> 	DEBIAN_FRONTEND="noninteractive" apt-get install tzdata python3-tk -y
> 	apt-get install make gcc libgtk-3-dev libwebkitgtk-dev libwebkitgtk-3.0-dev libgstreamer-gl1.0-0 freeglut3 freeglut3-dev python-gst-1.0 python3-gst-1.0 libglib2.0-dev libgstreamer-plugins-base1.0-dev -y
> 	pip3 install simba-uw-tf
> 	pip3 install tk

Would it be possible to build a docker container for Simba, or any tips?

**Comment by sgoldenlab** [comment]
Hi @singhsaluja - don't have a solution to this situation, but, some of the error messages arefamiliar. 

First, we have written SimBA for Win only at this point and I do not know how it behaves in Linux. 

The numpy AttributeError: make sure you are running numpy==1.18.1 and tensorflow-gpu==1.14.1 - if you already are - then this has helped me in different situations (non-SimBA related), for the same error msg, in the past: https://github.com/aleju/imgaug/issues/537#issuecomment-569880719, I'd stick the `np.random.bit_generator = np.random._bit_generator` after all imports in SimBA.py

For the tk error, I have not encountered this, it seems to be related to import of matplotlib: https://stackoverflow.com/questions/55811545/importerror-cannot-load-backend-tkagg-which-requires-the-tk-interactive-fra 

Matplotlib is used in the following script and imported on the following lines:
# dpk_script\train_model.py: 7
# gantt.py: 2
# labelling_aggression.py: 8
# line_plot.py: 4
# plot_heatmap.py: 3
# prob_graph.py: 4
# sklearn_DLC_RF_train_model.py: 17
# train_model\train_model_user_defined.py: 24
# train_model_2.py: 23
# train_multiple_models_from_meta.py: 15
# validate_model_on_single_video.py: 13

I would try to adopt the matplotlib import as discussed in the thread and see if that starts it.

Thanks

**Comment by MMathisLab** [comment]
To run deeplabcut on docker/singularity, i.e. headless, you must `export DLClight=True` before import. https://github.com/DeepLabCut/Docker4DeepLabCut2.0
