### ISSUE TITLE
Simba Create Project

### ISSUE THREAD

**Issue by Pinh13** [sgoldenlab/simba#35]
Hi

I installed the Simba (pip install simba-uw-no-tf) in my local. then i launched "simba".  I am trying to create a project, after filling all fields the following error came out:

Traceback (most recent call last):
File "C:\users\...\appdata\local\programspython\python37\lib\thinter\__init__.py", line 1705, in __call__
return self.func(*args)
File "C:\users\...\appdata\local\programs\python\python37\lib\site-packages\simba\simba.py", line 3056, in make_projectini
with open(no animalsPath, "r", encoding='utf8') as f:
FileNotFoundError: [errno 2] No such file or directory: 'C:\\users\\...\\pose_configurations\\no_animals\\no_animals.csv

In fact the pose configurations folder is empty. 
What should I do?

**Comment by inoejj** [comment]
@Pinh13, thank you for reporting this bug. I fixed the bug and you can now download it using `pip install simba-uw-no-tf==1.1.7.

Please do not hesitate to let me know if you have anymore issue.

Thank you!
