### ISSUE TITLE
Impossible to run simba on Mac os

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#37]
Hello, 

Thank you for the new release of Simba. 
I tried to install it on my mac using "pip install simba-uw-no-tf" command. 

During the installation I noticed a bug: whereas this command should specify for intallation without TensorFlow, an error message appeared:

"Could not find a version that satisfies the requirement tensorflow_gpu==1.14.0..."

I added '#' before the tensorflow line in requirments, and that fixed the issue. 

Nevertheless, I can not launch the program from my terminal. 
Once cd in my simba folder, I tried both: "simba.py" and "pythonw simba.py" commands. 

Here the error message returned: 

![b95a3806-9308-4a56-b941-532f8d33f5c8](https://user-images.githubusercontent.com/66886884/84579069-19bcee80-adcb-11ea-99e8-ccc61b800eef.jpg)

FYI: I'm using python 3.7.6, with anaconda. I'm also using DeepLabCut 2.2.b5. Finally one friend tried also to install Simba on her Macos, and she had the same error. 

Have you some suggestion to fix the bug? 

Thank you very much!
Best,
Dorian

**Comment by sgoldenlab** [comment]
Hi @DorianBattivelli – thanks for looking into SimBA! At the moment we only support Windows use and I’m aware of Mac/Linux issues in relation to the paths, which appears to be what’s preventing the boot on your machine.

Ensuring Mac/Linux compatibility is not a priority right now. Is there any chance you could find a windows machine, or would running SimBA through a virtual windows environment e.g., virtualbox or vmware,  be an alternative for you? That would prevent these errors you are seeing from showing up.

**Comment by DorianBattivelli** [comment]
Hi @sgoldenlab, 

Thank you for your answer. I will try to install it on a windows computer, 

Best, 
Dorian

**Comment by sgoldenlab** [comment]
@DorianBattivelli - let me know how it goes!
