### ISSUE TITLE
Plotly Interface is not available

### ISSUE THREAD

**Issue by wallawhitecoat** [sgoldenlab/simba#373]
Hi, I was wondering why the plotly interface does not work when I attempt to open it. Here are my settings, 
![image](https://github.com/user-attachments/assets/7640050e-25eb-42bf-bd36-d1dddde27990)
![image](https://github.com/user-attachments/assets/5ccb7e4d-16ad-441c-8fda-a450826d84c0)

I attempted to download plotly in case the vrs. I had was not correct, but it says that I already have it in miniconda3. 
![image](https://github.com/user-attachments/assets/010a7242-a915-4b71-bcea-00af9bb5da80)

I also attempted to open it by adding a "SimBA Groups file (CSV)" file modeled after the simba example in this [link](https://github.com/sgoldenlab/simba/blob/master/misc/SimBA_Dash_tutorial_Group_information.csv). It printed this error in the prompt and then SimBA quit.
![image](https://github.com/user-attachments/assets/09bb0c37-dc6e-4859-8987-29887906436c)
Here is what this file looks like, I'm not sure if simba isn't recognizing a file because it is not labelled dash_daq or if this is happening for another reason 
![image](https://github.com/user-attachments/assets/59ee27d0-9acf-475e-b1e5-593d27ae4723)
Any help would be greatly appreciated, thank you!

Windows 10, version 22H2
Python Version [3.10.14]
using miniconda3 Version [24.4.0]

**Comment by sronilsson** [comment]
Hi @wallawhitecoat!

The plotly dashboard was written by people that now moved on to other things, and I haven't had a chance to maintain it myself and, without maintenance it breaks rather quickly...  😬  I started to look over their code, and put up the `SimBA plotly interface is not available` statement in GUI in meantime.

**Comment by sronilsson** [comment]
... should you need it, you could go back to version <0.8.0.  But there are other stuff in those early years that make things wobbly.

**Comment by wallawhitecoat** [comment]
Ok, no worries!
