### ISSUE TITLE
Conflicting Dependencies + Failure to Run

### ISSUE THREAD

**Issue by akh8zm** [sgoldenlab/simba#38]
Hello! This is my first time writing an issue, so feel free to request lots of clarification.

I'm running the most recent version of Anaconda and attempting to install Simba. I've followed the instructions [here](https://github.com/sgoldenlab/simba/blob/master/docs/installation.md#install-simba-standalone-package-without-tensorflow-or-integrated-deeplabcutdeepposekit-support) for installing the standalone package w/o tf. I've been trying to resolve this for the past few hours to no avail.

**Describe the bug**
Simba will not run and has trouble installing.

**To Reproduce**
1. Create environment with python 3.6: `conda create --name new_env python==3.6`
2. Activate environment: `conda activate new_env`
3. Within `new_env`, run `pip install simba-uw-no-tf`. This is using pip version 20.1.1. Everything appears to build correctly except with the following warning:
** `ERROR: imbalanced-learn 0.7.0 has requirement scikit-learn>=0.23, but you'll have scikit-learn 0.22.2 which is incompatible.`
4. Ignoring that, run `simba` in `new_env`. This fails and produces a long traceback. 
**`Traceback (most recent call last):`
`File "c:\programdata\anaconda3\envs\new_env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)`
 ` File "c:\programdata\anaconda3\envs\new_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)`
`  File "C:\ProgramData\Anaconda3\envs\new_env\Scripts\simba.exe\__main__.py", line 4, in <module>`
 ` File "c:\programdata\anaconda3\envs\new_env\lib\site-packages\simba\SimBA.py", line 47, in <module>
    from simba.ROI_freehand_draw_3 import roiFreehand`
 ` File "c:\programdata\anaconda3\envs\new_env\lib\site-packages\simba\ROI_freehand_draw_3.py", line 6, in <module>
    from shapely.geometry import Polygon`
 ` File "c:\programdata\anaconda3\envs\new_env\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE`
 ` File "c:\programdata\anaconda3\envs\new_env\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence`
 ` File "c:\programdata\anaconda3\envs\new_env\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos`
`  File "c:\programdata\anaconda3\envs\new_env\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))`
`  File "c:\programdata\anaconda3\envs\new_env\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)`
`OSError: [WinError 126] The specified module could not be found`

**Expected behavior**
Expect no conflicting dependencies and simba to start when `simba` is run in `new_env`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.6.0 in `new_env`, 3.8 in base environ
 - Are you using anaconda? Yes
 
**Things I have tried**
- making sure shapely is installed in `new_env`
- same thing with Python 3.7 and 3.8 (has even more issues)
- Interestingly, imbalanced-learn 0.7 has listed on their [pypi site](https://pypi.org/project/imbalanced-learn/) that it is compatible with scikit-learn versions >= 0.22...I tried installing scikit-learn version 0.23 anyways, which conflicts with simba but satisfies imbalanced-learn. Produces same error when trying to run `simba`. 
- same thing with imbalanced-learn 0.62 in the hopes it doesn't need scikit-learn 0.23... same error when trying to run `simba`

Any help/thoughts much appreciated!

**Comment by sgoldenlab** [comment]
Hi @akh8zm - this is most likely a Shapely issue - the same issue and error msg has been reported and solved a few times in the past and unrelated to imblearn / scikit.

https://github.com/sgoldenlab/simba/issues/12#issue-583261742

https://github.com/sgoldenlab/simba/issues/11#issuecomment-596805732

https://github.com/sgoldenlab/simba/issues/33#issue-617328532

I think it relates to some modules of the Shapely package not meant to be run in python. 

I'd try some of the following to see if you can get it started: Remove shapely if installed: `conda remove shapely` and install it again `conda install shapely` and see if that works. 

Otherwise, the fix that has been working for me is the second link above - download the wheel yourself and install it.

Let me know if that helps!

**Comment by akh8zm** [comment]
Thanks for the prompt reply! I removed and reinstalled shapely as you said using conda, didn't work and produced new error message. I'm gonna post the error message just for completeness.

`Traceback (most recent call last):`
`  File "c:\programdata\anaconda3\envs\new_env\lib\runpy.py", line 193, in _run_module_as_main  "__main__", mod_spec)`
`  File "c:\programdata\anaconda3\envs\new_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)`
`  File "C:\ProgramData\Anaconda3\envs\new_env\Scripts\simba.exe\__main__.py", line 4, in <module>`
`  File "c:\programdata\anaconda3\envs\new_env\lib\site-packages\simba\SimBA.py", line 90, in <module>
    from simba.sleap_bottom_up_convert import importSLEAPbottomUP`
`  File "c:\programdata\anaconda3\envs\new_env\lib\site-packages\simba\sleap_bottom_up_convert.py", line 1, in <module>
    import h5py`
`ModuleNotFoundError: No module named 'h5py'`

I next tried to download the wheel directly from the link you said, installed it using pip and reinstalled simba. Running `simba` results in the same error message as above. 

In the install documentation for simba-no-tf it says "This does not require a GPU, or local installations of DeepLabCut, DeepPoseKit, or SLEAP.", but since I'm getting an error missing a module, is there something else I need to install? I'm gonna keep trying to troubleshoot with my limited skills 😄

**Comment by sgoldenlab** [comment]
You are almost there! For some reason h5py hasn't installed in your environment either. 

You fixed the shapely error. Once that is done, run:

`pip install h5py`

and try and launch SimBA again and let me know if that fixes it!

**Comment by akh8zm** [comment]
oh my gosh it worked! Thank you so much. 
For posterity, I created a new environment and did:
```
conda install shapely
pip install simba-uw-no-tf
pip install h5py
simba
```

**Comment by sgoldenlab** [comment]
Great - let me know if you get into any more issues @akh8zm
