### ISSUE TITLE
Path not working on MacOS

### ISSUE THREAD

**Issue by EvenGu** [sgoldenlab/simba#39]
**Describe the bug**
Some of your scripts use backslashes for generating a path, which does not work on MacOS.
For example,  in the create_project_init.py, 
```project_folder = str(directory +'\\' + project_name + '\\project_folder')```
It would be better to use ```os.path.join()```

The backslashes resulted in folders like this: 
![image](https://user-images.githubusercontent.com/8534966/85917709-7d630500-b82a-11ea-9911-b20b2f3437b7.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python Version [e.g. 3.6.0]
 - Are you using anaconda?
 

**Additional context**

**Comment by sgoldenlab** [comment]
Hi @EvenGu - currently we only support Windows. I.e., check this recent issue for suggested work arounds (e.g., virtual Win environment for now) :

https://github.com/sgoldenlab/simba/issues/37#issuecomment-643699314

There been a lot of Mac/Linux users reaching out about issues like this, and I know some may be working on updating the SimBA code to ensure Mac/Linux compatibility and when this is available I will let you know.
