### ISSUE TITLE
Cannot extract frames

### ISSUE THREAD

**Issue by asacson** [sgoldenlab/simba#40]
Hi, First of all thank you for creating SIMBA! This is my 1st approach to this kind of tracking programs and I'm just learning to use the program.
I'm running SIMBA w/TF in Windows 10 with:

- Intel i7 (8th gen)
- NVIDIA GeForce MX250 GPU
- 16GB RAM

I created a DLC project with one video, and when I want to extract the frames in this video (w/automatic form and uniform algorithm) I get the following in my anaconda prompt:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\agost\anaconda3\envs\dlc-gpu\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\agost\anaconda3\envs\dlc-gpu\lib\site-packages\simba\SimBA.py", line 2148, in dlc_extractframes_command
    select_numfram2pick(config_path,self.label_numframes2pick.entry_get)
NameError: name 'select_numfram2pick' is not defined

```

**Comment by sgoldenlab** [comment]
Hi @asacson - thanks for trying SimBA and thanks for reporting this, it's very helpful. Can you download the latest version of SimBA using `pip install simba-uw-tf --upgrade` (version 1.2.3.11), load your project, and try to extract frames and let me know if it works now? Thanks again!

**Comment by asacson** [comment]
Hi, thank you very much for your help! That did work but now I have another problem, when I try to check the labelled frames SimBA crashes and enters in 'not responding' mode. I don't get any traceback in SimBA nor in anaconda prompt

**Comment by asacson** [comment]
Thank you very much for the quick response, it's working now.
