### ISSUE TITLE
About the heatmap error

### ISSUE THREAD

**Issue by gxkjj** [sgoldenlab/simba#404]
![image](https://github.com/user-attachments/assets/c8145994-b52b-4bff-8a14-5b84fd9a7f6c)
when i run the heatmap, i got the error, after that i  have a only way to do closing the simba. 
Please help me to fix this.

**Comment by sronilsson** [comment]
Thanks for reporting @gxkjj - appreciate it. 

If you update simba to the latest version (2.4.5) with `pip install simba-uw-tf-dev --upgrade`, do you still see the same error, or du you see any other error message, or the same error message?

**Comment by gxkjj** [comment]
Thank you very much. It's working fine. @sronilsson
