### ISSUE TITLE
Issue when uploading bx.h5 files. 

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#45]
Hello, 

I am working on a maDLC project, and I have an error message when I try to import my h5 files on Simba. 

Here the screenshot:
![Untitled](https://user-images.githubusercontent.com/66886884/87858369-baa04b80-c92d-11ea-816f-f6fc917ff169.png)

Would someone have a suggestion to fix this problem?

FYI: I labelled the body parts through DLC 2.b.5 on windows 7, then run the training and analysis on colab, modifying the first cell code to use DLC 2.b.7, and now I tried to switch on Simba on two different windows computer, one with windows7 the other with windows 10. Nothing works, always the same error.

Thank you for the help, 
Best, 
Dorian

**Comment by sgoldenlab** [comment]
Hi @DorianBattivelli - sorry about this and thanks for reporting it. The issue most likely comes from SimBA trying to read the resolution of your video, to make sure the circles are visualized at appropriate size  (not too big / not too small), and it can't find the resolution or the video. 

To get this working, do you happen to see any error msg in the main SimBA terminal printed at the same time as this error msg? 

Are your videos in .mp4 and/or .avi format?

**Comment by DorianBattivelli** [comment]
Thank you for the help,

No, I did not see any error message in the main Simba terminal. I just have the "Importing 8 multi-animal DLC h5 files to teh current project".
 I am working on avi files,

Thank you

**Comment by sgoldenlab** [comment]
@DorianBattivelli Thanks, let me see if I can fix it - I think it could be an Avi issue with the code.

**Comment by sgoldenlab** [comment]
@DorianBattivelli - sorry there was a line in there that hardcoded it to look for an mp4, which likely caused the issue - either (1) download the latest SimBA `pip install simba-uw-tf==1.2.5` or `pip install simba-uw-no-tf==1.2.5`, and I should have fixed it, or (2) Convert your videos to mp4 (https://github.com/sgoldenlab/simba/blob/master/docs/Tutorial_tools.md#change-video-format) - let me know if that fixes it or not

**Comment by DorianBattivelli** [comment]
@sgoldenlab Both solutions perfectly fixed the problem. Everything is working now, thank you so much!

**Comment by sgoldenlab** [comment]
Great and thanks for letting me know !
