### ISSUE TITLE
Impossible to set video parameters.

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#46]
Hello,

I'm using multi-animal pose-estimation data in SimBA. I already extracted the frames, and should now set the video parameters. But here the error message my prompt returns:

![Untitled](https://user-images.githubusercontent.com/66886884/87948623-3ffa3c00-caa5-11ea-9043-0d4793a01abf.png)

Consequently, no video row appear, and I cannot define the scales on my videos.

Would someone please have a suggestion to fix this problem?

FYI: I'm using the 1.2.5 simba version and get the same error on windows 7 and 10. My videos are .avi. 

Thank you, 
Best, 
Dorian

**Comment by DorianBattivelli** [comment]
I fixed the bug. 
The extension of the video files were in capital letters, while it should not.

I also report here another bug: my files in the csv input folder have been generated with avi extension, and so I had to modify them manually in "çsv" to make it work.

Thank you, 
Best, 
Dorian

**Comment by sgoldenlab** [comment]
Thanks @DorianBattivelli - that's exactly what I was going to ask you (about the capital letters) - I was looking through the code and saw that this could happen, I will push a fix for this now. 

I will also fix the issue in the import of the CSV, it's likely to be due to the same capitalization reason.

Thanks again!

**Comment by sgoldenlab** [comment]
@DorianBattivelli - I've uploaded a fix (version 1.2.6 now) - the fix is to rename all file extensions to lowercase (e.g., ".AVI" or ".MP4" becomes ".avi" or ".mp4") when imported into SimBA. Let me know if you bump into any more issues like this. Thanks!

**Comment by DorianBattivelli** [comment]
@sgoldenlab thank you so much,
Best, 
Dorian
