### ISSUE TITLE
Pointer to folder with dlc files

### ISSUE THREAD

**Issue by akaye** [sgoldenlab/simba#47]
Hi, I'm using SimBA on some DLC output files, which I had to move to a different drive post-labelling. Now I'm not able to train the network.

Is there a config file with the project pointing to the DLC files I can access somewhere to edit to the new directory?

**Comment by sgoldenlab** [comment]
Hi @akaye - just to be able to troubleshoot this, are you using DLC within the SimBA GUI (https://github.com/sgoldenlab/simba/blob/master/docs/Tutorial_DLC.md) or are you using DLC separately from SimBA? It will help me understand what's going on, thanks!

**Comment by akaye** [comment]
We used DLC separately

**Comment by sgoldenlab** [comment]
One more question! When you say 'post-labelling' - do you mean after labelling the frames in SimBA (labelling behaviors) or do you mean body-part labelling in DLC?

**Comment by akaye** [comment]
Post-labelling behaviors (frames in SimBA) we had to move some of the source files because of hard drive space issues, I'm wondering if I can redirect the source file pointer to the new location

**Comment by sgoldenlab** [comment]
@akaye thanks I think I get it now. The project paths are saved inside your project `project_config.ini` file. What I would normally do is open the file in notepad++, and do a control+F search and replace, replacing the old path substrings in the entire file with the new path substring. 

You'll see a [General settings] heading with a `project_path` entry at the top, this is the most important. But to be sure all functions in SimBA works I'd make sure I'd replace any old paths in this file. 

So e.g.,
**Search for**
C:\myoldprojectpath\
**Replace with**
Z:\mynewprojectpath\

Let me know it that works

**Comment by emmonseb** [comment]
Hi @sgoldenlab,

I'm the collaborator of @akaye who ran into the project path issue yesterday--thank you very much for resolving that! 

Unfortunately it seems like the issue we're having is related to something else entirely. Suggestions for how to address the below error?

<img width="1662" alt="Screen Shot 2020-07-22 at 11 59 15 AM" src="https://user-images.githubusercontent.com/68665127/88225593-5ed90980-cc30-11ea-9f8a-e3b661414c2c.png">

**Comment by sgoldenlab** [comment]
Hi @emmonseb! There seems to have been a mis-reading in SimBA for what body-parts your project contains, it could have happened when you created the project. To figure out what's going on, could you open this file in your project `project_folder\logs\measures\pose_configs\bp_names` - and send a screenshot to me? This file should contain a list of the body parts that you are using in your project and might look like this: 

![image](https://user-images.githubusercontent.com/50497030/88230216-da35bd80-cc26-11ea-86a1-ed41ce9e747f.png)

Do the listed body-part in your file seem familiar? Otherwise, I'd suggest eauther to update the body-parts in this file to the correct ones, or try and create a new project and let me know if the error persists.

**Comment by emmonseb** [comment]
Here's what I see in `project_folder\logs\measures\pose_configs\bp_names'

<img width="136" alt="Screen Shot 2020-07-22 at 4 25 07 PM" src="https://user-images.githubusercontent.com/68665127/88230681-77e5b880-cc38-11ea-9f73-a41bbbb3ee21.png">

These names correspond to the body parts that I used for my DLC tracking, though I worded them differently. I tried changing the Excel file to the abbreviations that I used, reran, and had the same issue.

If I create a new project will I be able to reference and use the outlier corrections, extracted features, and labeled frames from my past project?

Thanks for all of your help!

**Comment by sgoldenlab** [comment]
I see, thanks - to help me understand how to fix this, did you used a user-defined pose-configuration or did you set it to an in-built one? The body-parts I am seeing corresponds with this built in one. 

![image](https://user-images.githubusercontent.com/50497030/88232005-f6872980-cc29-11ea-9643-e85d2e2948b6.png)

To give you an an idea why this is happening - SimBA tries to build a model by grabbing your CSV files in your `project_folder/csv/targets_inserted' directory and that works fine. However, it SimBA then tries to remove your pose-estimation columns and just keep the features. SimBA begins, for example, to look for a column called, for example, 'Ear_left_x' to discard it, and it can't find it, thereby the error. If you open your csv file in excel (if it is not to large) you can take a peek on what your body-parts in fact are called, which may help you troubleshoot what have gone wrong,  i.e.: 

![image](https://user-images.githubusercontent.com/50497030/88232426-af4d6880-cc2a-11ea-84f2-6cce34053a30.png)

**Comment by emmonseb** [comment]
Such helpful and clear guidance, thank you. I made the relevant changes and things are humming along nicely.

In case it's helpful for someone else, it seems that the default names given by SimBA for this layout are:
<img width="137" alt="Screen Shot 2020-07-22 at 5 01 31 PM" src="https://user-images.githubusercontent.com/68665127/88233484-5fc46800-cc3d-11ea-8f66-44ddc8f55f8c.png">

Thanks again, I really appreciate your thorough and responsive help!

**Comment by sgoldenlab** [comment]
👍 thanks for letting me know, and please let me know if you bump into any other issues
