### ISSUE TITLE
Issue with graphviz not being recognized

### ISSUE THREAD

**Issue by emmonseb** [sgoldenlab/simba#48]
Hi again, @sgoldenlab, I had hoped it would be longer before I pestered you again!

The "Train Machine Model" step ran well for a few minutes before running into the below error:
<img width="1388" alt="Screen Shot 2020-07-22 at 5 13 08 PM" src="https://user-images.githubusercontent.com/68665127/88234755-24c33400-cc3f-11ea-8409-3b63a399cc41.png">

Thoughts on how to circumvent this? I did a bit of looking around other forums (not related to SimBA) and found a suggestion that I add Graphviz to the Windows path. Thanks in advance for your help!

**Comment by sgoldenlab** [comment]
Haha @emmonseb - keep em' coming! :)

To install graphiz, there is a guide that I found useful that you can access through this menu in SimBA: 

![image](https://user-images.githubusercontent.com/50497030/88235909-b0819400-cc30-11ea-9c73-6a850eaf2c55.png)

To make sure it's working, you need to add it to the environmental paths in windows, in the same way as (I presume) you have already added FFmpeg to the path. It's not directly part of python, so you can't do a `pip` install. 

To circumvent this issue, you can also untick this box in SimBA to not generate a decision tree visualization using graphviz:

![image](https://user-images.githubusercontent.com/50497030/88236229-5f25d480-cc31-11ea-883f-7f31c4a90cf9.png)

**Comment by emmonseb** [comment]
Thanks @sgoldenlab! I'm trying it without the graphviz requirement for now, and am now getting this exception:
<img width="1452" alt="Screen Shot 2020-07-22 at 6 06 50 PM" src="https://user-images.githubusercontent.com/68665127/88238167-905ccf80-cc46-11ea-8778-489473308e2a.png">

When this does eventually create a model, where will the .sav file be stored? I looked over the tutorial pretty thoroughly and wasn't able to find the location. Thanks!

**Comment by sgoldenlab** [comment]
@emmonseb - this error is produced by your settings in this entry box:
![image](https://user-images.githubusercontent.com/50497030/88238819-9303f880-cc37-11ea-9cee-7ada706b8ae1.png)

If you have ticked this box, the entry box should become un-greyed out and allow you to insert an integer number ("How many features do you want to display in your feature importance graph?"). It seems like SimBA can't find the integer. Did you enter a value in this box after ticking the tick-box?

**Comment by emmonseb** [comment]
Wow, talk about a dumb mistake, sorry about that! When I had previously done the settings I had put a number in but overlooked it this time. I'm re-running it now.

Thanks for your patience!

**Comment by sgoldenlab** [comment]
It's an easy miss to make, I should insert a error message that catches it.
