### ISSUE TITLE
portability

### ISSUE THREAD

**Issue by rkoot** [sgoldenlab/simba#5]
I try to run SimBA.py on OpenSUSE 15.1 x64 and ran into various portability errors. Mostly it's case-sensitivity (ie TheGoldenLab.PNG -> TheGoldenLab.png) and various instances of '\\' in the code. 
As both linux, mac and windows works fine with '/' as directory delimiter, I think it would be nice to change the \\'s to /

**Comment by sgoldenlab** [comment]
Thanks for pointing this out @rkoot - very helpful - it has been added to the list
