### ISSUE TITLE
Issue for ROI analyze. 

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#50]
Hello, 

I'm using SimBA with data obtained from multi animal pose estimation from DLC. 
I have been able to extract my frames, to scale the video and to draw the ROIs. But when I want to run the ROI analysis (2 animals, one body part), there is an error. Here a screen shot of the prompt: 

<img width="889" alt="Schermata 2020-07-23 alle 18 06 04" src="https://user-images.githubusercontent.com/66886884/88310128-97034980-cd0f-11ea-9b14-bf92ab99d98f.png">

I'm analyzing 4 videos, and used the function "apply to all" after drawing the ROI of the first video. The first video seems ok, but the issue occurs at the second video: 

<img width="490" alt="Schermata 2020-07-23 alle 18 19 27" src="https://user-images.githubusercontent.com/66886884/88311593-602e3300-cd11-11ea-926b-77644d392e0f.png">

Someone would have a solution to help me fixing this issue? 

FYI: I'm using SimBA 1.2.5 on windows 7. My videos are ".avi".
I already successfully run ROI analysis with the same program configuration (but never using "apply to all" function) with other videos. So I don't know why this time it is not working. 

Thank you, 
Best, 
Dorian

**Comment by sgoldenlab** [comment]
Hi @DorianBattivelli - i tried to re-create it here (with and w/o "apply to all") but it ran through so at this moment i don't think it's a bug. The issue is SimBA trying to grab the current X,Y coordinate of the body-part of the animal. And it then, just to make sure, tries to convert it to an integer value (in case it turns out to be a float value), but it turns out to be a NaN, can't work with that, and it breaks. 

If you go to the `project_folder\csv\outlier_corrected_movement_location\cEFp1_30.csv` and open it up, can you see anything differently compared to the other files - is there any reason this file would have empty entries / cells? Was this file processed the same way as the others through pose-estimation and outlier correction?

If you analyze this file only, not using the "apply to all" function, does it work?

**Comment by DorianBattivelli** [comment]
@sgoldenlab Thank you for the answer. 

I check the project_folder\csv\outlier_corrected_movement_location\cEFp1_30.csv file, I did not notice any difference expect its size: 4.5 mo while the 3 others are around 7.5 mo.

**Comment by DorianBattivelli** [comment]
I will try later to draw each video without the "apply to all " function, and I'll let you know, 

Thank you, 
Best, 
Dorian

**Comment by sgoldenlab** [comment]
@DorianBattivelli alright let me know! If the video is the same length as the others it's should be the same file size as the rest, and it should be a single header row in all files. I'll insert something that catches NaN errors in the next update

**Comment by DorianBattivelli** [comment]
They are all 15 min videos, so with the same length. Strange so their file sizes are different. 
I failed to draw manually the other ROI, since when I click "reset" next to _30, _45 and _60 video, I have this message:

<img width="519" alt="Schermata 2020-07-23 alle 18 59 31" src="https://user-images.githubusercontent.com/66886884/88315674-e39e5300-cd16-11ea-900b-ec6a703f081b.png">

It seems that is considers that no ROI is saved for these videos. But when I click draw, the ROI drew ont the first video appear. Is that normal? 

Btw, I confirm that I have a single header row in all files.

**Comment by DorianBattivelli** [comment]
Actually, casting a more attentive look, I see that the cEFp1_30 is full of empty cells. I don't know why. 

Here how is the situation: 
<img width="1415" alt="Schermata 2020-07-23 alle 19 25 50" src="https://user-images.githubusercontent.com/66886884/88318032-7096db80-cd1a-11ea-8e7c-6fdda891a6a1.png">

The other excel files are full. 
Have you an idea of the reason why it is like that?

**Comment by sgoldenlab** [comment]
Thanks @DorianBattivelli - I will have to come back to this in the afternoon, but no - that is not normal and should not happen, and I have a feeling I have another .avi / .mp4 bug on my hands with is separate from your original error. You could check this by converting your avi's to mp4's in your videos folder and run it again in the meantime but I will let you know.

**Comment by sgoldenlab** [comment]
If you look in your original DLC input file in your `project_folder/csv/input_csv`, is that file also missing values?

**Comment by DorianBattivelli** [comment]
Yes, this one also has missing values. While the files related to the other videos have not.

**Comment by DorianBattivelli** [comment]
Ok, I will try the mp4 solution later and let you know, thank you

**Comment by sgoldenlab** [comment]
Can you go back and check the very original file, in the DLC project, I think something could have gone wrong when you ran it through DLC potentially

**Comment by DorianBattivelli** [comment]
Do you mean the bx.h5 file?

**Comment by sgoldenlab** [comment]
Ah yes, forgot it was multi animal - yes, something has gone astray with this file - either it has not been converted properly to csv or something went wrong when it was generated in DLC.

**Comment by DorianBattivelli** [comment]
Ok, I'll re run DLC to generate it again, and will let you know if it fixed the problem.

**Comment by sgoldenlab** [comment]
@DorianBattivelli - I've pushed an update that should fix the reset issue you were seeing with your .avi files - that should be taken care of if you upgrade SimBA to version 1.2.7

**Comment by DorianBattivelli** [comment]
Thank you for the release. 
I regenerated a h5 file from dlc, and tried to analyze ROI on SimBA: it works perfectly. Thank you for the help, 
Best, 
Dorian

**Comment by sgoldenlab** [comment]
I am happy to hear that!
