### ISSUE TITLE
 name 'deeplabcut' is not defined

### ISSUE THREAD

**Issue by neugun** [sgoldenlab/simba#51]
**Describe the bug** When I run simba and error about dlc appears.
(deeplabcut-py36) D:\Users\Administrator\Documents>simba
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\deeplabcut-py36\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\programdata\anaconda3\envs\deeplabcut-py36\lib\site-packages\simba\SimBA.py", line 1904, in <lambda>
    button_generatetempyaml_single = Button(label_tempyamlsingle,text='Add single video',command=lambda:generatetempyaml(self.label_set_configpath.file_path,self.label_genyamlsinglevideo.file_path))
  File "c:\programdata\anaconda3\envs\deeplabcut-py36\lib\site-packages\simba\dlc_change_yamlfile.py", line 15, in generatetempyaml
    deeplabcut.add_new_videos(tempyaml,[videolist],copy_videos=True)
NameError: name 'deeplabcut' is not defined

**Desktop (please complete the following information):**
 - windows 10
 - Python Version [ 3.6.0]
 - Are you using anaconda? yes
 intalled with SimBAxTF.

Do you have any ideas? Thanks!

**Comment by sgoldenlab** [comment]
Hi @neugun - it seems DeepLabCut may not be installed in the environment from which you are launching SimBAxTF. Within the SimBA environment, could you try doing a `pip install deeplabcut==2.09` followed typing `simba` and let me know if it launches?

**Comment by neugun** [comment]
Hi! @sgoldenlab  I  rerun conda install shapely, and it is finally work!  Thanks to your reply!
