### ISSUE TITLE
Issue importing .slp files. 

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#54]
Hello,

@sgoldenlab sorry for this new request, but I'm actually unable to import slp files:

<img width="973" alt="Schermata 2020-07-27 alle 17 31 42" src="https://user-images.githubusercontent.com/66886884/88560962-12763b00-d02f-11ea-8efe-9bf929bb6eff.png">

Would you have some suggestion to fix that? 
Thank you, 
Best, 
Dorian

**Comment by sgoldenlab** [comment]
Hi @DorianBattivelli! Let me see if I can recreate it - are you using the SLEAP bottom up or the SLEAP top down architecture?

**Comment by DorianBattivelli** [comment]
The bottom-up one.

**Comment by sgoldenlab** [comment]
Is there any body-parts in you SLP file that, that you tracked, but did not specify as you were generating the project? For example in this menu:

![image](https://user-images.githubusercontent.com/50497030/88575711-27d07280-cff9-11ea-8a65-b60966c77e9a.png)

Or did you use one of the built in body-part configurations?

**Comment by DorianBattivelli** [comment]
Actually, I never dealt with the pose config window in simba. At which point should it pop out? 
I defined the bp and the skeleton on SLEAP, and all have been defined.

**Comment by sgoldenlab** [comment]
Thanks - another issue opened that bump into the same error - I will check it out with the files @L-Jacinto shared with me.

**Comment by DorianBattivelli** [comment]
Ok, thank you!

**Comment by sgoldenlab** [comment]
@DorianBattivelli - check this response. Let me know if it makes sense and if it imports for you or not. 

https://github.com/sgoldenlab/simba/issues/53#issuecomment-664597813

**Comment by DorianBattivelli** [comment]
Thank you for the feedback. I installed the new version, but it still fails to upload my .slp file. 
Do you confirm that the one to use is the VIDEONAME.predictions.slp generated in my video folder after the inference is done? 

Here the error: 
<img width="976" alt="Schermata 2020-07-27 alle 22 50 09" src="https://user-images.githubusercontent.com/66886884/88590769-8af2f100-d05b-11ea-8b39-633b3e64f54f.png">

**Comment by sgoldenlab** [comment]
Still happens hmm.. can you just double check, which SimBA version you are running - is it 1.2.10?

**Comment by DorianBattivelli** [comment]
Theoretically yes, I just created a new environment and installed the last version inside. Can you please tell me the command to check the version I'm actually using?

**Comment by DorianBattivelli** [comment]
When I go in my site-packages folder, I see a simba-uw-no-tf 1.2.10.dist.info, so I think yes, I'm using the last version.

**Comment by sgoldenlab** [comment]
I'd do `pip uninstall simba-uw-tf`

then I'd

I'd do `pip install simba-uw-tf==1.2.10` for example, or `simba-uw-no-tf==1.2.10` 

The errors for the other user seems to be persisting in a different form - I'm not sure why but will look at it later https://github.com/sgoldenlab/simba/issues/53#issuecomment-664624443

**Comment by DorianBattivelli** [comment]
Well, I run the command, but the error still occurs.

**Comment by sgoldenlab** [comment]
Alright - sorry to have to do this again! But would you mind sharing an slp file and the associated video, easier to trouble shoot. Thanks

**Comment by DorianBattivelli** [comment]
No problem, I added a subfolder called "slp_issue" in the SimBA_CSV we already share. 
ps: I tried both with .avi and .AVI in the title of the slp file, it does not change anything. 

Thank you again for the help.

**Comment by sgoldenlab** [comment]
Hey @DorianBattivelli - yes it is not an issue with the AVI's, the error occurs prior to this and at the moment, I cannot find an easy solution. This is the error: 

In your SLP file all the animal detections get assigned a track. For example, in your first frame, SLP finds two tracks named `1857` and `1858`, which is all good. These tracks  persist for a few frames but then SLEAP finds new tracks, with new identities, and SimBA struggles to to which tracks are relevant, and which isn't in the end, and therefore fails to create the correct number of headings in the output data frame. For example, in frame 1-2 it looks good, but then already at frame 3 we have an issue, with a third track available:  

![image](https://user-images.githubusercontent.com/50497030/88697092-f028ff80-d0b8-11ea-987c-bc2120132021.png)

SimBA could handle this by dropping the track with the lowest probability, but then we encounter another issue: the top 2 tracks in many images keep changing names, we don't know who is who any more: for example in the second to last frame the top two tracks are called `1912` and `1922` - and I can't tell, for example, if the original  `1858` is track `1922` or `1912`, or neither of them There may be a fix for this (beyond better tracking but I don't know how to handle it in SimBA at the moment... 🤔)

**Comment by DorianBattivelli** [comment]
Ok, so it's definitely a problem with the quality of my videos. I'll try to generate models with higher quality, thank you anyway,
Best
Dorian
