### ISSUE TITLE
Error in Extract Features Rolling Filter

### ISSUE THREAD

**Issue by lucytian828** [sgoldenlab/simba#56]
**Describe the bug**
I'm doing a test run using an hour long mp4 file and DLC labels for 1 animal, 8 body parts. Extract Features appears to be working until it hits "Calculating rolling windows: medians, medians, and sums..." at which I get the following error: 

[
![Simba error](https://user-images.githubusercontent.com/43044612/88926680-f1366a00-d23b-11ea-94cc-71ca0008c952.jpg)
](url)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.6.2
 - Are you using anaconda? Yes

**Comment by sgoldenlab** [comment]
Hi @lucytian828 - the first thing that comes to mind is the fps of your video. Is it less than 15 fps? SimBA tries to divide the frames into rolling bins, with the smallest being 66ms, (fps / 15) if you can't do this (for example a single frame is longer than 66ms) this would happen. If that's the case we can modify the feature extraction script.

**Comment by lucytian828** [comment]
That would be the issue. The fps is slightly less than 15.

**Comment by sgoldenlab** [comment]
@lucytian828 - there's currently no way of modifying the rolling window sized directly in the `project_config.ini` but I will include it in the future. 

To get rid of, or add/change rolling window sized navigate to SimBAs feature extraction scripts. On my computer they are in this path but it will be slightly different for you as you are using Anaconda: `C:\Python36\Lib\site-packages\simba\features_scripts`.

Next, open the feature extraction script you are using. One animal and 8bps would be the `extract_features_8bp.py` script. The critical line you need to edit is line 34, and specifically the last value in this list:

![image](https://user-images.githubusercontent.com/50497030/88941929-73c02900-d23e-11ea-9d87-497e0d104752.png)

Currently it says 15, which means it tries to divide your fps with 15 - and it returns a value less than 1. Try changing it to 14 and let me know how it goes.

**Comment by lucytian828** [comment]
That did the trick, thanks!
