### ISSUE TITLE
Problem of switching identities. 

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#57]
Hello again ;)

I improved my model significantly I guess (increasing the labeled frames, the number of iterations on dlc and using another camera to increase the resolution - I have now a 640x480 video).

The problem I have now appear when I play the ROI tracking video. 
The identity dot (back body part) regularly switches from one animal to another when mice are close.
Here an illustration of a sequence when it switches: 

![id1](https://user-images.githubusercontent.com/66886884/89524081-36cad800-d7e4-11ea-9eb4-6757518580f7.png)

![id2](https://user-images.githubusercontent.com/66886884/89524090-3af6f580-d7e4-11ea-9f7b-7d34c27f6b5a.png)

We shaved a spot on the back on one mouse to avoid this problem, but it did not fix it.
Have you any suggestion to solve this issue? Do you think increasing the shaving or adding extra physical distinctions can help?

Thank you,
Best
Dorian

**Comment by sgoldenlab** [comment]
Hi Dorian - I know these issues rather well, but I say try the DLC gitter or dlc issue tracker for this problem - they will have a far better answer than me for their software. 

Generally, ID switches are still an issue for me when I use maDLC and have videos with a lot of occlusion (e.g. a lot of heavy fighting between animals). When animals are more friendly with each other, the idea is that you should be able to solve the switches with a combination of (i) a lot accurate annotations, (ii) a well connected skeleton (connect nearly all bodyparts), (iii) correcting any identity switches using their in-built interactive tracklets tool and feed it back into the model.

**Comment by DorianBattivelli** [comment]
Hi @sgoldenlab,

Thank you for your answer and your suggestions. I also wrote a post on the dlc GitHub. 
I'm working on territoriality, so fights are an important part of the behaviors I would like to score. I hope that increasing the shaving will improve the reliability of the tracking. 

Best, 
Dorian

**Comment by sgoldenlab** [comment]
Hi @DorianBattivelli  - yes we are facing similar issues so far with maDLC, and I've spent a fair bit of time on it (and we've tried shavings, but not extensively) - and we've yet to get it to work satisfactory when animals are fighting a lot. The solution I think, is the tracklets interface (but it does not work well in Windows, at least in the 2.2b5/ 2.2b6 versions).
