### ISSUE TITLE
ROI that changes with every frame

### ISSUE THREAD

**Issue by blogeman** [sgoldenlab/simba#59]
Thanks for the great tool, excited to start using SIMBA. It appears that currently only static ROI's are supported, am I correct? I'm interested in nest building and have been using a MASK-RCNN based approach to identify the changing shape of the nest in every frame of a video. The output is a Shapely polygon which I use to create a dataframe with the columns containing polygon x,y and each frame is a row (just like the output from DLC). Is there a way that I could import this continually evolving polygon feature as an ROI?

Thanks!

**Comment by sgoldenlab** [comment]
Hello @blogeman! - that's cool! And sure, it can be imported as a feature (but not through the GUI... )

You are correct, only static ROI's work. 

In SimBA, once you have labelled your images for the behaviors of interest, there will be a CSV file for every annotated video in the `project_folder/csv/target_inserted` directory. SimBA will use all the columns (minus the annotations and pose-estimation body-part locations) as features. If you can append your mask information as one or several additional columns within these files, then those columns will also be used used, automatically, in SimBA, when creating the classifiers.

I think the mask vertices can be represented as lists of various lengths, and it wouldn't work if you create, for example, two new columns in the  `project_folder/csv/target_inserted` files that each contain a list for every frame (the x, y cords of all the vertices). I don't know if it would be relevant, but if you instead had single values that somehow represent you nest mask features it would work nicely for behavioral predictions (i.e., nest_area mm2 or pixels). 

I don't know what you are looking to score but if you are only interested in if the animal body-part(s) are inside your mask rcnn region, then SimBA can't help at the moment, the code doesn't update the ROI coordinates for new frames, it assumes it is static. If that's what you are interested in you can check line 131-136 in ROI_analysis_2.py in SimBA to see how I did it - shapely has a function to check if a coordinate is in a polygon but my code only reads in the vertices once. 

pointList = []
for point in vertices:
    pointList.append(geometry.Point(point))
polyGon = geometry.Polygon([[p.x, p.y] for p in pointList])
CurrPoint = Point(int(currentPoints[bodyparts]), int(currentPoints[bodyparts+arrayIndex]))
**polyGonStatus = (polyGon.contains(CurrPoint))**

**Comment by blogeman** [comment]
Thanks for the help @sgoldenlab. I'll try using the total area of the polygon as an appended feature like you suggest. The behavior of nest building should have a high permutation importance to the total nesting material area as the animal collects the material and localizes it into a single nest (aka total area decreases as the nest is built).
