### ISSUE TITLE
Error with Generate / Save csv on Label Behavior Page

### ISSUE THREAD

**Issue by ahabchopra** [sgoldenlab/simba#64]
Hi - having an issue with the Label Behavior portion of the SimBA process. Although I am able to successfully extract frames and label behaviors, I seem to get a repeated error when it comes time to Generate/Save CSV. Screenshot of the terminal attached below. Let me know if there are any suggestions I can try! 
![Capture](https://user-images.githubusercontent.com/43099772/91525569-cb9a9000-e8cf-11ea-83a6-48bd45878034.PNG)

**Comment by sgoldenlab** [comment]
Hello @ahabchopra - thanks for the screenshot very helpful. Check out this suggested solution to a user that reported similar issues recently: https://github.com/sgoldenlab/simba/issues/55#issuecomment-665910732.

When you have completed your labels for `video_40` using the labelling GUI and press `Generate/Save CSV`, SimBA tries to append the labels to the CSV file containing the extracted features from `video_40` which will be located in the `project_folder/csv/features_extracted` directory. If SimBA can't find the `project_folder/csv/features_extracted/video_40.csv` file, then it can't append your annotations, and you will see the error message you are seeing. Before starting to label  behaviours, make sure to extract the features by clicking on this button:

![image](https://user-images.githubusercontent.com/50497030/91566644-d3225f00-e8f8-11ea-9629-8fc9beb0d428.png)

Let me know if this helps you pass the error or not, thanks!

**Comment by ahabchopra** [comment]
Hi @sgoldenlab! Thanks for the quick response 👍. I actually saw the earlier thread, but it didn't resolve the error. When I try to "extract features," the SimBA GUI displays something along the lines of "0 features extracted." If it would help to have a screenshot of this I can rerun and paste it here - let me know.

**Comment by sgoldenlab** [comment]
@ahabchopra I see, then it makes sense :) if you look in your `project_folder/csv/features_extracted` directory it is probably empty. 

To extract features, we first have to correct any gross pose-estimation tracking outliers (or tell the code to skip the outlier correction step). The feature extraction step looks in the `project_folder/csv/outlier_corrected_movement_location` folder, and extracts features from any files that have had tracking inaccuracies corrected first, and then creates new CSVs and places them in the `project_folder/csv/features_extracted` folder. Did you go through the step of clicking any of these buttons?

![image](https://user-images.githubusercontent.com/50497030/91600384-b6981e00-e91c-11ea-8820-59292e5e4af5.png)

**Comment by ahabchopra** [comment]
@sgoldenlab - sorry should have clarified my earlier steps. After creating a project and extracting frames, I went through the video parameters step (and saved), skipped outlier correction, and then went to extract features. Hope that is more helpful in diagnosing the error. 

If it's relevant, I'm inputting an H5 file from a mutt-animal DLC project.

**Comment by sgoldenlab** [comment]
Cheers @ahabchopra - do you see any files in your `project_folder/csv/input_csv` folder?

**Comment by ahabchopra** [comment]
@sgoldenlab not seeing any files in that folder - is that where the h5 should have been copied?

**Comment by sgoldenlab** [comment]
Yeah, when you go through this step: https://github.com/sgoldenlab/simba/blob/master/docs/Multi_animal_pose.md

At the end of the process, the CSV's, one for each of the h5 files in your project, should be located in that folder. If you go through the steps in the tutorial link again, could you paste me any screenshot of the terminal window at the end of the process that would help me diagnose the problem?

**Comment by ahabchopra** [comment]
@sgoldenlab thanks for all your help! Think it was a combination of going through the tutorial again and reading some more threads that has resolved all of the errors.

**Comment by sgoldenlab** [comment]
@ahabchopra fantastic, let me know if anything else comes up though.
