### ISSUE TITLE
Question on behaviour analysis

### ISSUE THREAD

**Issue by shinhs0506** [sgoldenlab/simba#69]
Hi,

is SimBA capable of detecting behaviours such as locomotion, rearing, sniffing on a single mouse?

Thank you in advance!

**Comment by sgoldenlab** [comment]
Yes, SimBA can be used to generate classifiers for all of these behaviors once they have been pose-estimated by DLC, SLEAP, DPK, etc. Locomotion can be determined using descriptive statistics, with no need for SimBA, but SimBA can still be used to generate and visualize these descriptive features. 

You can download classifiers for sniffing from the SimBA OSF repository, and iterate the model to work under your conditions. The instructions to do this are available in the SimBA documentation (https://github.com/sgoldenlab/simba#pipeline-). 

Others have created rearing classifiers that you could try to start with (https://github.com/saviochan/SimBA-OpenFieldArena).
