### ISSUE TITLE
install issue/question

### ISSUE THREAD

**Issue by eventhorizonzero** [sgoldenlab/simba#7]
First of all, thank you for developing SimBA!

I'm having an install issue that I cant seem to get around with dlc-windowsGPU (windows environment)

(dlc-windowsGPU) C:\Users\xxxxx\simba\simba>simba.py
Traceback (most recent call last):
  File "C:\Users\maplight\simba\simba\SimBA.py", line 5, in <module>
    import deeplabcut
ModuleNotFoundError: No module named 'deeplabcut'

I have all the proper dependencies installed, I'm assuming it's a path I'm missing somewhere. using Anaconda. I have DeepLab installed:

(dlc-windowsGPU) C:\Users\xxxxx\DeepLabCut\

Thank you in advance for any guidance.

**Comment by sgoldenlab** [comment]
Hi @eventhorizonzero! I'm working on finding answer to this. Meanwhile, can you run `conda list` in your dlc-windowsGPU environment, paste the output here, and make sure DeepLabCut is visible in list.

**Comment by inoejj** [comment]
There are multiple ways to solve this issue.

1. You can install deeplabcut using pip install deeplabcut in the terminal.

2. This is probably the better way. Use the terminal in Anaconda(dlc-windowsGPU) and try to run SimBA via the terminal ( python SimBA.py).

Please let me know if this resolve your issue.

**Comment by eventhorizonzero** [comment]
It indeed was missing from the "conda list" output.  after running the pip install it was listed and I was able to run. thank you to you both for the assistance! no idea where my DLC install went off the rails :)

**Comment by sgoldenlab** [comment]
Great! Issue closed.
