### ISSUE TITLE
issue with feature extraction

### ISSUE THREAD

**Issue by filos93** [sgoldenlab/simba#74]
Hey, thanks for the great tool :) when I try to extract features I get this error message: "ValueError: min_periods (1) must be <= window (0)" and nothing shows in the features_extracted folder, everything looks fine with the outlier correction I have the CSV files in the right folders, I'm using maDLC on a single animal and tracking is ok, when I created the project on Simba I defined a new configuration with four bodyparts (left_ear, right_ear, snout, tailbase) and chose multi-tracking then imported h5 tracking data file (sk.h5), everything is ok with setting parameters and run outlier correction steps (I just skipped the roi part). Can you help me, please? Thanks in advance!

**Comment by sgoldenlab** [comment]
Hi @filos93! What comes to mind is that this could happen if the fps of your videos are less than 15. SimBA tries to grab features in rolling windows, with the smalest window being the fps /  15. If you have less than 15fps, that number will be a float lower than 1, and you can't grab a rolling window size that length. Check out out this for more information: https://github.com/sgoldenlab/simba/issues/56

What you want to do (because you have 4 bps, rather than 8 as in the linked issue above), is open the feature extraction script for 4 bodyparts. In the linked issue, I point to changing a value in the `extract_features_8bp.py` file. You want to do **exactly** the same as in the issue, except you want to make the change to the `extract_features_4bp.py`file. 

Hope that makes sense and let me know how it goes!

**Comment by sgoldenlab** [comment]
PS: depending on what version of SimBA you are running, the critical line is either on line 30, or possible line 80, and looks like this: 

`roll_windows_values = [2, 5, 6, 7.5, 15]` - if your fps is less than 15, you want the change the last value (i.e., 15) to your fps (so if your fps is 14, change the last value to 14, for example)

**Comment by filos93** [comment]
Hey, thanks so much for your reply :) I changed code as you specified, unfortunately, I keep getting the same error: "ValueError: min_periods (1) must be <= window (0)" and I'm unable to get features extracted. Some other suggestions or things I could do/adjust? Thanks again

**Comment by sronilsson** [comment]
@filos93 ah, to understand better, what's the fps of your videos? And what does your roll_windows_values list look like?

**Comment by filos93** [comment]
Hey, thanks again for help, the fps of my video is 14 and these are from my video_info csv file: Video | fps | Resolution_width | Resolution_height | Distance_in_mm | pixels/mm -- | -- | -- | -- | -- | -- Test66 | 14 | 360 | 476 | 140 | 2. Then, this is from extract_features_user_defined.pyfile: roll_windows = [ ] roll_windows_values = [2, 5, 6, 7.5, 14] loopy = 0 (in roll_windows_values 14 was 15). Simba gui shows: 
Pose-estimation body part setting for feature extraction: user_defined
Extracting features from 1 files...
Processing "Test66". Fps: 14.0. mm/ppx: 2.0
Calculating euclidean distances...
Calculating rolling windows data...
But, then it doesn't go on. Please, let me know how I can fix it. Thank you :)

**Comment by sronilsson** [comment]
Thanks @filos93 - can you post a screenshot or the error msg in the main terminal window?

**Comment by filos93** [comment]
Hey @sronilsson thanks for all your help :) the following is the error msg: 

Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\users\filipppo\anaconda3\envs\simba\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\filipppo\anaconda3\envs\simba\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\filipppo\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 4476, in extractfeatures
    extract_features_wotarget_user_defined(self.projectconfigini)
  File "c:\users\filipppo\anaconda3\envs\simba\lib\site-packages\simba\features_scripts\extract_features_user_defined.py", line 108, in extract_features_wotarget_use
r_defined
    csv_df[colName] = csv_df[selectedCol].rolling(roll_windows[i], min_periods=1).mean()
  File "c:\users\filipppo\anaconda3\envs\simba\lib\site-packages\pandas\core\window.py", line 1877, in mean
    return super().mean(*args, **kwargs)
  File "c:\users\filipppo\anaconda3\envs\simba\lib\site-packages\pandas\core\window.py", line 1180, in mean
    return self._apply("roll_mean", "mean", **kwargs)
  File "c:\users\filipppo\anaconda3\envs\simba\lib\site-packages\pandas\core\window.py", line 965, in _apply
    result = calc(values)
  File "c:\users\filipppo\anaconda3\envs\simba\lib\site-packages\pandas\core\window.py", line 958, in calc
    x, window, min_periods=self.min_periods, closed=self.closed
  File "c:\users\filipppo\anaconda3\envs\simba\lib\site-packages\pandas\core\window.py", line 939, in func
    return cfunc(arg, window, minp, index_as_array, closed, **kwargs)
  File "pandas/_libs/window.pyx", line 578, in pandas._libs.window.roll_mean
  File "pandas/_libs/window.pyx", line 349, in pandas._libs.window.get_window_indexer
  File "pandas/_libs/window.pyx", line 149, in pandas._libs.window.MockFixedWindowIndexer.__init__
  File "pandas/_libs/window.pyx", line 72, in pandas._libs.window._check_minp
ValueError: min_periods (1) must be <= window (0)

**Comment by sgoldenlab** [comment]
Hey @filos93 - hmm, strange.. let's figure out that might be going on, that should have fixed it. Inside your feature extraction script (extract_features_user_defined.py), can you insert once line (Line 46 in the image below: print(fps)) and tell me whats printed outs - if your fps is 14 you should see `14` being printed. The most immediate way to explain this is that the fps of the video is either not stored as `14` in your video_config.csv file in the project log folder, or that the largest roll_window_values value is larger than 14.  


![image](https://user-images.githubusercontent.com/50497030/97096927-43630d80-1628-11eb-9672-9fffa973a59c.png)

**Comment by filos93** [comment]
hey @sgoldenlab I changed 14 to 15 fps in my video_info csv file and it worked! don't know why Simba gui was telling me video fps was 14 when it was 15, anyway many thanks for all your help :)
