### ISSUE TITLE
Evaluation reports will be overwrite when run train model twice

### ISSUE THREAD

**Issue by Yating-L** [sgoldenlab/simba#75]
The model evaluation tools generate precision recall curve and learning Curve for each model but the filenames only include the behavior name, for example, for behavior attack, we will get attack_precision_recall. If I re-run training step, attack_precision_recall will be overwrite.

I think like the other files, we should append the index number to the filename of the precision recall curve and learning Curve.

**Comment by sgoldenlab** [comment]
@Yating-L , I have added your suggestion to the script. Please upgrade to the latest version 1.2.29 and let me know if it works on your end.

**Comment by Yating-L** [comment]
It worked! Thank you for fixing this.

**Comment by Yating-L** [comment]
I got a KeyError when run RF model after I updated to 1.2.29. 
<img width="775" alt="Screen Shot 2020-10-23 at 7 50 26 AM" src="https://user-images.githubusercontent.com/8609589/97005948-bd01db00-1504-11eb-8da4-039f880e683e.png">
