### ISSUE TITLE
I got a KeyError when run RF model after I updated to 1.2.29.

### ISSUE THREAD

**Issue by Yating-L** [sgoldenlab/simba#76]
I got a KeyError when run RF model after I updated to 1.2.29. 
<img width="775" alt="Screen Shot 2020-10-23 at 7 50 26 AM" src="https://user-images.githubusercontent.com/8609589/97005948-bd01db00-1504-11eb-8da4-039f880e683e.png">

_Originally posted by @Yating-L in https://github.com/sgoldenlab/simba/issues/75#issuecomment-715322269_

**Comment by sgoldenlab** [comment]
Hi Yating, what is your pose_estimation_body_parts in your project_config.ini?

This can be found under *create ensemble settings* --> pose_estimation_body_parts 

![image](https://user-images.githubusercontent.com/50497030/97033384-1fb0a200-1518-11eb-84ca-b57ce6ae8dce.png)

**Comment by Yating-L** [comment]
pose_estimation_body_parts = 8

**Comment by sgoldenlab** [comment]
@Yating-L , please change it to user_defined as shown in the image for now and see if it works. Meanwhile I will try to find out what causes it to change to 8. 

When creating the project, did you define your own bodyparts? Or did you use the pre-made schematics? 

Best,
JJ

**Comment by Yating-L** [comment]
I created the project using the pre-made schematics, 1 animals 8 bps. I guess it may due to the project was created with the earlier version of SimBA, pose_estimation_body_parts was set to 8 at that time?

Thanks!

**Comment by sgoldenlab** [comment]
Ahh, I see. Does changing the pose_estimation_body_parts to  user_defined in project_config.ini works for you?

**Comment by Yating-L** [comment]
I don't have access to the lab computer now. I will try it out on Monday and let you know. Thanks!
