### ISSUE TITLE
SLEAP File Import Error

### ISSUE THREAD

**Issue by MattKDawson** [sgoldenlab/simba#78]
HI again @sgoldenlab !

I see a new error when attempting to import tracking data from SLEAP, which I will paste below. I am currently running the dev version of SimBA. Any help you can provide is greatly appreciated :)

(simba_env) C:\Users\matth>simba
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:901)
warning: C:/Users/matth/Documents/Modeling/SimBA\test\project_folder\videos\social_.mp4 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:902)
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\matth\anaconda3\envs\simba_env\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\matth\anaconda3\envs\simba_env\lib\site-packages\simba\SimBA.py", line 3048, in importh5
    importSLEAPbottomUP(self.configinifile,self.h5path.folder_path,idlist)
  File "c:\users\matth\anaconda3\envs\simba_env\lib\site-packages\simba\sleap_bottom_up_convert.py", line 176, in importSLEAPbottomUP
    circleScale, fontScale, spacingScale = int(myRadius / (myResolution / maxResDimension)), float(myFontScale / (myResolution / maxResDimension)), int(mySpaceScale / (myResolution / maxResDimension))
ZeroDivisionError: division by zero

**Comment by sgoldenlab** [comment]
@MattKDawson , can you send me one .slp file so I can test it out on my side?

**Comment by MattKDawson** [comment]
Hi @sgoldenlab !

I will email you a .slp file for you to use :) . In SimBA, I always import the video files first before the tracking data. I also see the following message in the main SimBA window when attempting to import the .slp file:

```
Converting .slp into csv dataframes...
Processing social_.slp...
Warning: The video name could not be found in the .SLP meta-data table
SimBA therefore gives the imported CSV the same name as the SLP file.
To be sure that SimBAs slp import function works, make sure the .SLP file and the associated video file has the same file name - e.g., "Video1.slp" and "Video1.slp" borefore importing the videos and SLP files to SimBA.
```
Thanks again for all your help with this! :)

**Comment by Sunday77** [comment]
Hi @sgoldenlab ,

I'm having the exactly same issue here. My video and .slp file having the same name, and I've imported video first and then .SLP file. However, it still give me the warning:
Warning: The video name could not be found in the .SLP meta-data table
SimBA therefore gives the imported CSV the same name as the SLP file.
To be sure that SimBAs slp import function works, make sure the .SLP file and the associated video file has the same file name - e.g., "Video1.slp" and "Video1.slp" borefore importing the videos and SLP files to SimBA.

As a result, I failed to see .csv file generated in the project folder. The video is imported fine as I can see all frames in project folder. Would be really appreciate with any help with this issue! Thanks!

**Comment by sgoldenlab** [comment]
@Sunday77 , would you mind sending the video and .slp file to jchoong@uw.edu so I can troubleshoot it? 

Thank you for reporting,
JJ

**Comment by smidm** [comment]
I've had the same issue when the imported video file had a different name than the video filename referenced in the SLP file (and the generated CSV file (disregarding the extension)). I've renamed the imported video file in `<project name>/project_folder/videos` to the same name as generated CSV in `<project name>/project_folder/csv/input_csv/`. It works now.
