### ISSUE TITLE
dependency conflict with scikit-learning

### ISSUE THREAD

**Issue by mauricev** [sgoldenlab/simba#80]
**Describe the bug**
imbalanced-learn 0.7.0 requires scikit-learn>=0.23 but simba-uw-no-tf 1.2.33 requires scikit-learn==0.22.2.

**To Reproduce**
Install simba-uw-no-tf according to the regular Anaconda instructions

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.6
 - Are you using anaconda? Yes
 
Is this conflict really significant? Simba launches OK, but we haven't put through any data yet.

**Comment by sronilsson** [comment]
Hey @mauricev - no need to worry about these warnings at all - they won't disrupt any function in SimBA. 

As you start putting data through and hit any snags, just open up another issue or let us know on the gitter chat https://gitter.im/SimBA-Resource/community
