### ISSUE TITLE
There are frames are not classified as containing the behavior event when the probability are above threshold

### ISSUE THREAD

**Issue by Yating-L** [sgoldenlab/simba#81]
When I set the minimum bout to 5ms and threshold to 0.8, I found there're some frames are not annotated as the behavior event, but the probability > threshold[
<img width="268" alt="Screen Shot 2020-11-25 at 4 40 24 PM" src="https://user-images.githubusercontent.com/8609589/100289591-dd2b1c80-2f3e-11eb-91f6-62a2c20568d4.png">
](url)

**Comment by sronilsson** [comment]
Hi @Yating-L - what is the frame rate of the video in your screenshot?

**Comment by Yating-L** [comment]
The frame rate is 15 FPS. Yes, column V1 is the frame number.

**Comment by sronilsson** [comment]
@Yating-L - at 15fps, a single frame represents 66.6 (or 67ms), and a min bout of 5ms should therefore score every frame above 0.8 probability as containing the behavior, in other words a min bout of 5ms is equivalent to not having a min bout at all, or 0ms. 

Is it possible that the specific video is registered in the logs/video_config.csv file with a different fps than 15? 

The min bout entry box in the SimBA GUI accepts the min bout length in milliseconds. Did you put `5` in this box? I'm asking as it could possibly be explained if `500` for example was put in this entry box.

**Comment by Yating-L** [comment]
I checked the logs/video_info.csv file, fps is 15. I actually changed the min bout in project_config file not SimBA GUI at 
[Minimum_bout_lengths]
min_bout_1 = 5

Yes, there're frames classified as containing the behavior. The total number of behavior events is less than that when setting min bout to 200ms.

**Comment by Yating-L** [comment]
And in the "Video parameters" tab, it says the fps of all my videos is 14, I have to manually correct it to 15 for all videos

**Comment by Yating-L** [comment]
I use SimBA version 1.2

I have the same issue when min_bout_1 = 0. The number of frames with probability > 0.8 is 79, but the number of jumping events is 51.

**Comment by sgoldenlab** [comment]
Thanks @Yating-L  - could you update SimBA (version 1.2.9.2) and see if it persists? 

There was a legacy hardcoded line in there, which did not allow positive classification in a single, or two consecutive frames, those classifications were removed by default. Your animal should now be able to rear for a single or two consecutive frames, if your min_bout length is sufficiently short. Let me know how it goes.

**Comment by Yating-L** [comment]
It works now. Thank you for fixing this!
