### ISSUE TITLE
failed to install simba in linux

### ISSUE THREAD

**Issue by Wutaijing9** [sgoldenlab/simba#84]
**Describe the bug**
when I try to install simba in linux system, incompatible occurs

**To Reproduce**
As recommended, 
Firstly, Run pip install pip==20.1.1
Next, run pip install simba-uw-tf
![screenshot](https://user-images.githubusercontent.com/32728290/103969143-4047da00-51a0-11eb-832f-932e5ee5fc2b.png)

Then I tried pip install simba-uw-tf --no-dependencies
![screenshot_1](https://user-images.githubusercontent.com/32728290/103969513-05927180-51a1-11eb-8f9f-74a51b7fd4c8.png)
But when I try to install dlc, no dlc satified the requirements of simba. 
![screenshot_2](https://user-images.githubusercontent.com/32728290/103970141-81d98480-51a2-11eb-8464-f902b6b6b573.png)
And THEN I go throuth requiments of dlc and simba
dlc requires pandas >= 1.0.1, while simba requires pandas 0.25.3
![screenshot_3](https://user-images.githubusercontent.com/32728290/103970246-bb11f480-51a2-11eb-8d9c-32d0fa3decc7.png)

**Desktop (please complete the following information):**
 - ubantu20.04
 - Python3.6
 - anaconda3

Do you have any other suggestions?

**Comment by sronilsson** [comment]
Hi @Wutaijing9 - first, if you are in Linux - use the simba dev version - `pip install simba-uw-tf-dev`, not the simba-uw-tf or simba-uw-no-tf versions. 

The clash you are seeing is because simba-uw-tf wraps around deeplabcut==2.0.9, which does not require pandas >=1.0. However, I recommend using the DLC interface to generate your tracking, rather than the simba-dlc interface. More info here: https://github.com/sgoldenlab/simba/blob/master/docs/Tutorial_DLC.md

**Comment by Wutaijing9** [comment]
> Hi @Wutaijing9 - first, if you are in Linux - use the simba dev version - `pip install simba-uw-tf-dev`, not the simba-uw-tf or simba-uw-no-tf versions.
> 
> The clash you are seeing is because simba-uw-tf wraps around deeplabcut==2.0.9, which does not require pandas >=1.0. However, I recommend using the DLC interface to generate your tracking, rather than the simba-dlc interface. More info here: https://github.com/sgoldenlab/simba/blob/master/docs/Tutorial_DLC.md

I do try simba-uw-tf-dev. 
pip install https://files.pythonhosted.org/packages/f7/cb/69a7a1dfc31068d3b96bf69822fda9140267e63e4983544573017b579a67/Simba_UW_tf_dev-0.77.1-py3-none-any.whl
(Since pip install simba-uw-tf-dev reported a lot of bugs, even tried no dependencies)
It did not work when I launch simba. Do you have any more suggesdtions?
![screenshot_4](https://user-images.githubusercontent.com/32728290/104005785-99cff900-51e0-11eb-9a91-02dd03f4321e.png)

**Comment by sgoldenlab** [comment]
@Wutaijing9. Please delete the environment and try again use pip install simba-uw-tf-dev==0.77.1

On Linux, somehow the installation of pip install simba-uw-tf-dev is defaulted to version 0.44 which is outdated.

Please let me know if that works for you.

**Comment by Wutaijing9** [comment]
> @Wutaijing9. Please delete the environment and try again use pip install simba-uw-tf-dev==0.77.1
> 
> On Linux, somehow the installation of pip install simba-uw-tf-dev is defaulted to version 0.44 which is outdated.
> 
> Please let me know if that works for you.

This reduced bugs compared to simba-uw-tf-dev. And bugs it reported were as follows
![screenshot_5](https://user-images.githubusercontent.com/32728290/104147872-08909a80-540b-11eb-8ee0-6d52e716a27b.png)

**Comment by sronilsson** [comment]
@Wutaijing9 - you still get the same TclError preventing boot?

**Comment by Wutaijing9** [comment]
> @Wutaijing9 - you still get the same TclError preventing boot?
Yes.

**Comment by Wutaijing9** [comment]
> @Wutaijing9 - you still get the same TclError preventing boot?
Excited thouth I don't know why.
NO MORE BUGS REPORTED NOW.
conda create py37 -n python=3.7.3
pip install simba-uw-tf-dev==0.77.1

simba could launch with no bugs reported


before 
conda create py36 -n python=3.6.0
pip install simba-uw-tf-dev==0.77.1
get TclError preventing boot.

**Comment by sgoldenlab** [comment]
Thanks for letting us know!
