### ISSUE TITLE
ROI visualization font size

### ISSUE THREAD

**Issue by filos93** [sgoldenlab/simba#85]
Hey, thanks again for the great software! This is more of a question than an issue. How can I change the font size in the ROI visualization particularly the font of "timer" and "entries" because right now they are a bit fuzzy and I cannot read them well. Please, let me know.

**Comment by filos93** [comment]
oh never mind found what I needed in the simba script "ROI_plot" (ie, user\anaconda3\envs\simba\Lib\site-packages\simba\ROI_plot.py) and changed that using Notepad ++, I'll close this "issue" then, thanks again

**Comment by sgoldenlab** [comment]
For anyone else looking into this, it's this row in ROI_plot.py:

![image](https://user-images.githubusercontent.com/50497030/104920407-952be300-594c-11eb-90b3-d895627fdfc8.png)

Tweak the last value to modify the font scaling, decrease it and the font should get smaller.
