### ISSUE TITLE
Data plot and wrong body parts selection

### ISSUE THREAD

**Issue by filos93** [sgoldenlab/simba#86]
Hey, I run into an issue with Data plot visualization. When I hit the "generate data plot" button in the GUI it gives me in terminal (Anaconda Prompt) a "KeyError: 'movement_Mouse_2_No_2'", indeed when I try to select body parts in the GUI they are wrong like truncated. In particular, the "Select body part" button shows me the wrong body parts (eg, "Mouse_2_No" instead of "Mouse_2_Nose" as it is in the project_bp_names.csv file). How can I fix it? Thank you so much again.

**Comment by sgoldenlab** [comment]
Hey @filos93 - sounds like a bug - which version of SimBA are you using?

**Comment by filos93** [comment]
Hey @sgoldenlab thanks for reply, I'm using the dev version ie, pip install simba-uw-tf-dev, should I change it?

**Comment by sgoldenlab** [comment]
No, keep that one @filos93 - is it the latest version? I just want to be sure I am searching for the big in the correct place.

**Comment by filos93** [comment]
Hey @sgoldenlab my version is 0.77.6 Should be the latest right?

**Comment by sgoldenlab** [comment]
Yep, that's the latest. Thanks, I will get back to you, i'll see if I can recreate

**Comment by sgoldenlab** [comment]
@filos93 - can you update to version 0.77.7 and see if thats fixed? 

Heads up, this part of the code hasn't been updated for a while and can still only handle two animals, if you have more you'll only get the data for animal 1 I believe.

**Comment by filos93** [comment]
Hey @sgoldenlab I updated my version, that fixes the bug in the GUI but I still get a KeyError in the terminal (ie, "KeyError: 'movement_Mouse_1_Ear_left_2'), I'll attach a screenshot maybe that can help. Thanks again for your help and your patience.
![Screenshot (22)](https://user-images.githubusercontent.com/64312024/104953360-8d108980-59c6-11eb-989d-dfe4b6d07f07.png)

**Comment by sronilsson** [comment]
Ah thanks for letting me know.. just to confirm, you don't have more than 2 animals? And are the same body parts tracked on all the animals?

**Comment by filos93** [comment]
yes two animals and tracked bodyparts are the same, here's the list: "Mouse_1_Ear_left, Mouse_1_Ear_right, Mouse_1_Nose, Mouse_1_Tail_base, Mouse_2_Ear_left, Mouse_2_Ear_right, Mouse_2_Nose, Mouse_2_Tail_base" from my project_bp_names csv file

**Comment by filos93** [comment]
the other visualizations (eg, Gantt plot, path plot) works well, it's just with Data plot visualization the issue

**Comment by sgoldenlab** [comment]
@filos93 - let's try one more time, could you update to 0.77.8 and see if that solves it?

**Comment by filos93** [comment]
Hey @sgoldenlab I found the error in the data_plot.py lines: 61,63,105, you have to change "movement_" to "Movement_" (eg, if noAnimals == 2: move1ColName = "Movement_" + SelectedBp + '_1'" so simba can find the "Movement_" in the features_extracted.csv file, after you do that everything works fine, I was able to generate the data plot! I'll attach a screnshot from the lines I changed in Notepad ++ maybe can help
![Screenshot (25)](https://user-images.githubusercontent.com/64312024/104969805-cefef700-59e9-11eb-9d97-44da47ecb41c.png)
![Screenshot (26)](https://user-images.githubusercontent.com/64312024/104969810-d0302400-59e9-11eb-88c8-7292021bb606.png)

. Thanks again :)

**Comment by sronilsson** [comment]
Super helpful, ta!
