### ISSUE TITLE
Simple-use case

### ISSUE THREAD

**Issue by catubc** [sgoldenlab/simba#87]
Hello
I've got several hundred hours of 4 or 6-gerbil videos that we are in the process of annotating using SLEAP (DLC did not do as well on them).

We are considering investing time in learning how to use simba, but the documentation is a bit overwhelming and it's not clear how to build our use case from the provided steps.

We essentially have the .slp files (or .csv files) and would like to know how to load them for a quick test (without adjusting all the parameters).

What do you recommend?  Is there a simple-cause that we could use?  Do you have a python notebook that goes through a basic .slp or .csv?

Ok, thanks so much,
catubc

**Comment by sgoldenlab** [comment]
Hello @catubc - I don't know your exact use case (e.g., what behaviours you are classifying) but there is nothing obvious that comes to mind that would prevent you from doing this - a lot comes down to the accuracy of the pose and keeping ID swaps at a minimum - although how much ID swaps matters again comes down to what you are aiming to do.  

For a trial I'd recommend 

(i) installing the SimBA development wheel - `pip install simba-uw-tf-dev`. 

(ii) take a **short** couple of video scored by SLEAP - maybe no more than a couple thousand frames. Create a SimBA project and import this single video as documented [HERE](https://github.com/sgoldenlab/simba/blob/master/docs/Multi_animal_pose.md). As you create the SimBA project you see a dropdown option for `workflow file type` which can be either `CSV` or `parquet`. With the size of your later data I'd recommend going for the parquet option - with hundreds of of hours of video then CSVs will cost you in terms of space and time. 

(iii) Once your project is created, and SLEAP pose is imported into your project, begin at this step of [Scenario 1](https://github.com/sgoldenlab/simba/blob/master/docs/Scenario1.md#part-2-load-project-1). But again, what specifically happens next depends on your use case - if you are interested in non-classification stuff it's possible you'd be better off looking [here](https://github.com/sgoldenlab/simba/blob/master/docs/ROI_tutorial.md) or [here](https://github.com/sgoldenlab/simba/blob/master/docs/directionality_between_animals.md). What are you looking to score? 

If you are looking to generate classifiers, then make sure the short videos you are importing has a good amount of behaviors that you are interested in, so you are not just feeding in no-behavior examples.  

Unfortunately we designed SimBA to be GUI based, not as many objects as there should be - there is no going back right now and no notebooks to offer at the moment 🤷 . We are however happy to respond to any issues and explain/update code if there is something missing as you are troubleshooting and working through it.
