### ISSUE TITLE
Sklearn visualizations of single videos

### ISSUE THREAD

**Issue by AyusoAa** [sgoldenlab/simba#89]
Dear SimBA developers, 
I'd like to generate one single exemplary video with sklearn visualization of model predictions, instead I SimBA generates visualizations of all videos at once, if I am right. 
Would it be possible to add such feature, similar to the ROI visualizations?
Best,
Irene

**Comment by sgoldenlab** [comment]
Hello @AyusoAa ! Yes we are on it and I will let you know when it's done - if you cannot wait: SimBA grabs all of the videos directly in the `project_folder/csv/machine_results` and plots the results when you click the sklearn visualization. If you want to do just a select few, put the videos you do **not** want the visualize in a temporarily folder somewhere else, and then move them back.

**Comment by sgoldenlab** [comment]
@AyusoAa, I have implemented what you have suggested. Please update to simba-uw-tf==1.3.3 and let us know if that works for you.

**Comment by sronilsson** [comment]
Note you should see it in the dev version too - 
![image](https://user-images.githubusercontent.com/34761092/107108125-94b79700-67ea-11eb-9b25-08fcacff962f.png)

**Comment by sgoldenlab** [comment]
@AyusoAa - did this update work as expected?

**Comment by AyusoAa** [comment]
It does work! Thank you so much for your attention and work :)
