### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by DanePatey** [sgoldenlab/simba#9]
**Describe the bug**
After entering the command

git clone -b SimBA_no_DLC https://github.com/sgoldenlab/simba.git

files are updated correctly, then after the command

pip install -r simba/SimBA/requirements.txt

I receive the error

ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Under the correct directory, then running the command

python SimBA.py 

produces the following

Traceback (most recent call last):
  File "SimBA.py", line 8, in <module>
    from tkinter_functions import *
ModuleNotFoundError: No module named 'tkinter_functions'

Any advice would be appreciated.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sgoldenlab** [comment]
Hi @DanePatey - to solve this, there seems to be two option: https://stackoverflow.com/questions/49911550/how-to-upgrade-disutils-package-pyyaml

I suggest running: 
pip install --upgrade pip==9.0.1

and then try again with: pip install -r simba/SimBA/requirements.txt

Let me know how it goes!

**Comment by DanePatey** [comment]
Hi @sgoldenlab 
Running 

pip install --upgrade pip==9.0.1

gives the following

Requirement already up-to-date: pip==9.0.1 in c:\users\lilab.uw-mxl8522rkv\anaconda3\lib\site-packages

So the package is already up to date. 
Now when running 
python SimBA.py i get the following as an output

Traceback (most recent call last):
  File "SimBA.py", line 8, in <module>
    from tkinter_functions import *
  File "C:\Users\LiLab.UW-MXL8522RKV\Anaconda3\simba\simba\tkinter_functions.py", line 4, in <module>
    import cv2
  File "C:\Users\LiLab.UW-MXL8522RKV\Anaconda3\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by sgoldenlab** [comment]
@DanePatey - you seem to be missing OpenCV . Run pip install opencv-python.

If the error persist, check this which the discuss the error in FAQ: https://pypi.org/project/opencv-python/

**Comment by DanePatey** [comment]
@sgoldenlab 

Sorry for the late reply back.
after running
pip install opencv-python
I get a return of the requirement is already satisfied.
Then running 
python simba.py
still gives the same issue.
Am I missing something where I need to have done all of this in a particular conda environment or something?

**Comment by sgoldenlab** [comment]
Did you pip install in your conda environment, or did you do in the windows terminal outside of the conda environment to install opencv? Be sure you are in your conda environment. 

Also, in your conda environment, you can run "conda list" - make sure that you can see opencv in the printed list.

**Comment by sgoldenlab** [comment]
Closing issue.
