### ISSUE TITLE
ROI data analysis

### ISSUE THREAD

**Issue by Wutaijing9** [sgoldenlab/simba#92]
**This was amazing to replace manual behavior annotation. 
When analyzing ROI data, I got cumulative entry times and cumulative spending time. But this was not enough for further analysis. I need to know the exact time and frame mouse entry and exit from the ROI area, like from frame 675 mouse begin to entry in the ROI area and frame #700 mouse exit from it OR the exact time.
Could you add this feature in ROI analysis? Thanks a lot!

**Comment by sgoldenlab** [comment]
Hello @Wutaijing9 ! 

Yes, what we can do is generate a sub-folder in the project logs folder, containing one CSV output file per video analyzed, the file lists the animal ID together with the shape and entry and exit frame.. the individual CSV files would look like this. Do you think that would work?

If the animal does not exit the ROI before the end of the video, the Exit_frame would be read as `-1`. 

![Screen Shot 2021-02-26 at 6 13 27 AM](https://user-images.githubusercontent.com/50497030/109311142-43ebfa80-77fa-11eb-8643-3c3fc17a8c8d.png)

**Comment by sgoldenlab** [comment]
If you update to the latest simba-uw-tf-dev version, you should have access to it. It is documented at the end of Part II of this tutorial : https://github.com/sgoldenlab/simba/blob/master/docs/ROI_tutorial.md#part-2-analyzing-roi-data 

Lat me know if it works!
